#
# Macro file for the initialization phase of "exampleN02.cc"
# when runing in interactive mode
#
# Sets some default verbose
#
/control/verbose 2
/run/verbose 2
#
# create empty scene
#
/vis/open VRML2FILE
/vis/scene/create
/vis/drawVolume
#
# Create a scene handler for a specific graphics system
# (Edit the next line(s) to choose another graphic system)
#
#/vis/open OGLIX
#
####/vis/open DAWNFILE
#
# draw scene
#
#/vis/viewer/set/viewpointThetaPhi 90 180 deg
#/vis/viewer/zoom 1.4
#/vis/viewer/flush
#
# for drawing the tracks
# (if too many tracks cause core dump => storeTrajectory 0)
#/tracking/storeTrajectory 1
#/vis/scene/endOfEventAction accumulate

#/vis/scene/create
#/vis/scene/add/volume
#/vis/sceneHandler/create RayTracer
##/vis/drawVolume Target
##/vis/specify Target
#/vis/viewer/create
#/vis/viewer/set/viewpointThetaPhi 90.0 0.0 deg
##/vis/viewer/set/viewpointVector 0.5 0.5 0.1 cm
#/vis/rayTracer/headAngle 30 deg
##/vis/viewer/pan -240 0 cm
##/vis/viewer/zoom 0.8
#/vis/viewer/flush
##/vis/scene/endOfEventAction accumulate
##/vis/rayTracer/trace
/tracking/verbose 2
/run/beamOn 1
