#
#  Test particle range
#
/control/verbose 2
/run/verbose 2
/tracking/verbose 1
/event/verbose 0
/test31/verbose 0
#
/test31/physics/cutGamma    95 cm
/test31/physics/cutElectron 95 cm
#/test31/physics/MaxStep     0.2 mm
#
#/test31/physics/addPhysics standard
/test31/physics/addPhysics  model
#
/test31/AbsorberMaterial    Aluminum
/test31/AbsorberThick       1000 cm
/test31/NumberOfAbsorbers   1
/test31/maxDeltaEnergy      1.0 MeV
/test31/WorldMaterial       Vacuum
/test31/HistoName           hbook.paw
/test31/HistoNumber         0
#/test31/NumberOfEvents      1
/test31/gun/beamE           0.01 MeV
#
#/gun/particle e-
/gun/particle proton
#/gun/particle alpha
#/gun/particle IonC12
#
/run/initialize
/run/beamOn 0
#
/process/inactivate   phot
/process/inactivate   compt
/process/inactivate   conv
/process/inactivate   eBrem
/process/inactivate   msc
#
#/process/eLoss/StepFunction 0.183 170 micrometer
/process/eLoss/fluct     false
#/process/eLoss/integral  false
/run/beamOn 1
