#================================================
# Macro file for the Ion test of "test31.cc"
#         10.04.01 V.Ivanchneko
#================================================
/control/verbose 2
/run/verbose 1
/tracking/verbose 0
/event/verbose 0
/test31/verbose 0
#
/testem/phys/setCuts         100000. mm
#/testem/phys/stepMax        0.1 mm
/testem/phys/addPhysics      emstandard
#/testem/phys/addPhysics      emstandard_opt2
/test31/AbsorberMaterial     G4_WATER
/test31/AbsorberThick        10 mm
/test31/NumberOfAbsorbers    60
/test31/maxDeltaEnergy       1.0 MeV
/test31/WorldMaterial        G4_Galactic
/test31/HistoNumber          7
/testem/histo/fileName       pos_st
/test31/verbose              0
#/process/eLoss/preciseRange  true
/run/initialize
#
#/gun/particle e+
#/gun/particle gamma
#/gun/particle proton
#/gun/particle alpha
/gun/particle ion
/gun/ion 6 12
/gun/particle ion
/gun/ion 18 40
/gun/particle ion
/gun/ion 82  208
/run/beamOn 1000
#/run/exit
#
