#================================================
# Macro file for the Ion test of "test31.cc"
#         10.04.01 V.Ivanchneko
#================================================
/control/verbose 2
/run/verbose 1
/tracking/verbose 1
/event/verbose 0
/test31/verbose 0
#
/testem/phys/setCuts         100000. mm
#/testem/phys/stepMax        0.1 mm
/testem/phys/addPhysics      emstandard
#/testem/phys/addPhysics      emstandard_opt2
#/testem/phys/addPhysics      livermore
#/test31/AbsorberMaterial     Beryllium
/test31/AbsorberMaterial     G4_WATER
#/test31/AbsorberMaterial     Tangsten
/test31/AbsorberThick        10 mm
/test31/NumberOfAbsorbers    60
/test31/maxDeltaEnergy       1.0 MeV
/test31/WorldMaterial        G4_Galactic
#/testem/histo/fileName       pos_st70.aida
#/testem/histo/fileName       pos_leMA.aida
#/testem/histo/fileType       xml
/test31/HistoNumber          0
/test31/verbose              0
#/process/eLoss/preciseRange  true
/run/initialize
#
#/gun/particle e+
#/gun/particle gamma
#/gun/particle proton
#/gun/particle alpha
/gun/particle ion
/gun/ion 6 12
/gun/particle ion
/gun/ion 18 40
/gun/particle ion
/gun/ion 82  208
/run/beamOn 1
#/run/exit
#
#/testem/histo/fileName       dedx_31.aida
#/testem/histo/fileType       xml
#/testem/calc/verbose 1
#/testem/calc/hist  proton Beryllium hIoni dedx 1
#/testem/calc/hist  proton Aluminum  hIoni dedx 2
#/testem/calc/hist  proton Iron      hIoni dedx 3
#/testem/calc/hist  proton Tangsten  hIoni dedx 4
#/testem/calc/hist  alpha Beryllium ionIoni dedx 5
#/testem/calc/hist  alpha Aluminum  ionIoni dedx 6
#/testem/calc/hist  alpha Iron      ionIoni dedx 7
#/testem/calc/hist  alpha Tangsten  ionIoni dedx 8
#
#/testem/calc/list  -1 
#/testem/calc/save
#
