#================================================
# Macro file for the Ion test of "test31.cc"
#         10.04.01 V.Ivanchneko
#================================================
/control/verbose 2
/run/verbose 1
/tracking/verbose 0
/event/verbose 0
/test31/verbose 0
#
/testem/phys/setCuts         0.1 mm
#/testem/phys/stepMax        0.1 mm
/testem/phys/addPhysics      standard
/test31/AbsorberMaterial     Silicon
/test31/AbsorberThick        10 mm
/test31/NumberOfAbsorbers    60
/test31/maxDeltaEnergy       1.0 MeV
/test31/WorldMaterial        Vacuum
/test31/HistoName            el_st_3.paw
/test31/HistoNumber          5
/test31/NumberOfEvents       0
/test31/gun/beamE            1000.0 MeV
/run/initialize
#
/gun/particle e-
#/gun/particle gamma
#/gun/particle proton
#/gun/particle alpha
#/gun/energy 10.0 MeV
#
/run/beamOn 1000

