#================================================
# Macro file for the Ion test of "test31.cc"
#         21.03.06 V.Ivanchneko
#================================================
/control/verbose 2
/run/verbose 1
/tracking/verbose 0
/event/verbose 0
/test31/verbose 0
#
/testem/phys/setCuts         1.0 mm
#/testem/phys/stepMax         10 mm
/testem/phys/addPhysics      emstandard
#/testem/phys/addPhysics      g4v52
/test31/AbsorberMaterial     G4_Fe
/test31/AbsorberThick        10 mm
/test31/NumberOfAbsorbers    10
/test31/maxDeltaEnergy       100.0 MeV
/test31/WorldMaterial        G4_Galactic
/testem/histo/fileName       extra.paw
/test31/HistoNumber          7
/test31/gun/beamE            5.0 GeV
#/process/eLoss/verbose  0
/run/initialize
#
/gun/particle mu+
/gun/energy 10.0 GeV
#
/run/beamOn 10

