#================================================
# Macro file for the Ion test of "test31.cc"
#         10.04.01 V.Ivanchneko
#================================================
/control/verbose 2
/run/verbose 1
/tracking/verbose 0
/event/verbose 0
/test31/verbose 0
#
/testem/phys/setCuts         0.0001 mm
#/testem/phys/setCuts         1000 mm
#/testem/phys/stepMax            0.1 mm
/testem/phys/addPhysics      emstandard
#/testem/phys/addPhysics      pai
#/testem/phys/addPhysics     livermore
/test31/AbsorberMaterial     G4_WATER
#/test31/AbsorberMaterial    G4_Pb
/test31/AbsorberThick        1 mm
/test31/NumberOfAbsorbers    300
/test31/maxDeltaEnergy       0.01 MeV
/test31/WorldMaterial        G4_AIR
#/testem/histo/fileName       h2o_st_p100MeV.paw
/testem/histo/fileName       h2o_pai_p10MeV1.paw
/test31/HistoNumber          5
/run/initialize
#
#/gun/particle mu+
#/gun/particle gamma
/gun/particle proton
#/gun/particle alpha
/gun/energy 10.0 MeV
#
/run/beamOn 1000
#
