#================================================
# Macro file for the Ion test of "test31.cc"
#         10.04.01 V.Ivanchneko
#================================================
/control/verbose 2
/run/verbose 1
/tracking/verbose 0
/event/verbose 0
/test31/verbose 0
#
/testem/phys/setCuts         0.1 mm
#/testem/phys/setCuts         1000 mm
#/testem/phys/MaxStep        0.1 mm
/testem/phys/addPhysics      standard
#/testem/phys/addPhysics      g4v52
#/testem/phys/addPhysics      lowenergy
/test31/AbsorberMaterial     Water
#/test31/AbsorberMaterial     Lead
/test31/AbsorberThick        1 mm
/test31/NumberOfAbsorbers    300
/test31/maxDeltaEnergy       0.5 MeV
/test31/WorldMaterial        Vacuum
/test31/HistoName            h2o_st_p200mev.paw
#/test31/HistoName            h2o_le_1.paw
#/test31/HistoName            h2o_52_1.paw
/test31/HistoNumber          5
/test31/NumberOfEvents       0
/test31/gun/beamE            200.0 MeV
/process/eLoss/verbose       0
/run/initialize
#
#/gun/particle mu+
#/gun/particle gamma
/gun/particle proton
#/gun/particle alpha
#/gun/energy 10.0 MeV
#
/run/beamOn 10000

