#================================================
# Macro file for the Ion test of "test31.cc"
#         10.04.01 V.Ivanchneko
#================================================
/control/verbose 2
/run/verbose 1
/tracking/verbose 0
/event/verbose 0
/test31/verbose 0
#
/testem/phys/setCuts         1.0 mm
/testem/phys/stepMax        1 mm
/testem/phys/addPhysics      emstandard
/test31/AbsorberMaterial     G4_Pb
/test31/AbsorberThick        10 mm
/test31/NumberOfAbsorbers    1
/test31/maxDeltaEnergy       10.0 MeV
/test31/WorldMaterial        Vacuum
/testem/histo/fileName       pb.paw
/test31/HistoNumber          5
/test31/gun/beamE            100.0 MeV
/process/eLoss/verbose  0
/run/initialize
#
/gun/particle mu+
#/gun/particle gamma
#/gun/particle proton
#/gun/particle alpha
#/gun/energy 10.0 MeV
#
/run/beamOn 1000

