#================================================
# Macro file for the Ion test of "test31.cc"
#         10.04.01 V.Ivanchneko
#================================================
/control/verbose 2
/run/verbose 1
/tracking/verbose 1
/event/verbose 0
/test31/verbose 0
#
/testem/phys/setCuts         1.0 mm
/testem/phys/stepMax        1 mm
/testem/phys/addPhysics      standard
#/testem/phys/addPhysics      g4v52
/test31/AbsorberMaterial     Lead
/test31/AbsorberThick        10 mm
/test31/NumberOfAbsorbers    1
/test31/maxDeltaEnergy       10.0 MeV
/test31/WorldMaterial        Vacuum
/test31/HistoName            mu_st_100.paw
/test31/HistoNumber          5
/test31/NumberOfEvents       0
/test31/gun/beamE            100.0 MeV
/process/eLoss/verbose  3
/run/initialize
#
/gun/particle mu+
#/gun/particle gamma
#/gun/particle proton
#/gun/particle alpha
#/gun/energy 10.0 MeV
#
/run/beamOn 10

