#================================================
# Macro file for the Ion test of "test31.cc"
#         10.04.01 V.Ivanchneko
#================================================
/control/verbose 2
/run/verbose 2
/tracking/verbose 0
/event/verbose 0
/test31/verbose 0
#
/testem/phys/setCuts         0.1 mm
#/testem/phys/stepMax        0.1 mm
/testem/phys/addPhysics      emstandard
/test31/AbsorberMaterial     G4_Si
/test31/AbsorberThick        10 mm
/test31/NumberOfAbsorbers    60
/test31/maxDeltaEnergy       1.0 MeV
/test31/WorldMaterial        Vacuum
/testem/histo/fileName       pos_st70.paw
/testem/histo/fileType       hbook
/test31/HistoNumber          5
/test31/verbose              0
#/process/eLoss/preciseRange  true
/run/initialize
#
/gun/particle e+
#/gun/particle gamma
#/gun/particle proton
#/gun/particle alpha
/gun/energy 100.0 MeV
#
/run/beamOn 1000

