#================================================
# Macro file for the Ion test of "test31.cc"
#         10.04.01 V.Ivanchneko
#================================================
/control/verbose 2
/run/verbose 1
/tracking/verbose 0
/event/verbose 0
/test31/verbose 0
#
/testem/phys/setCuts         0.001 mm
#/testem/phys/stepMax        0.1 mm
#/testem/phys/addPhysics      standard
/testem/phys/addPhysics      g4v52
#/testem/phys/addPhysics      standard70
#/testem/phys/addPhysics      lowenergy
#/testem/phys/addPhysics      lowenergyMA

/test31/AbsorberMaterial     Iron
/test31/AbsorberThick        0.0077 mm
/testem/histo/fileName       fe_52_1mum.paw

#/test31/AbsorberMaterial     Tantalum
#/test31/AbsorberThick        0.00458 mm
#/test31/HistoName            ta_st_1.paw

/testem/histo/fileType       hbook
#/testem/histo/fileType       xml

/test31/NumberOfAbsorbers    100
/test31/maxDeltaEnergy       0.5 MeV
/test31/WorldMaterial        Vacuum
/test31/HistoNumber          2
/test31/gun/beamE            1.0 MeV
#
#/process/eLoss/preciseRange  true
/run/initialize
#
/gun/particle e-
#/gun/particle gamma
#/gun/particle proton
#/gun/particle alpha
#/gun/energy 10.0 MeV
#
/run/beamOn 10000

