# $Id: storeTables.mac,v 1.3 2006-04-28 18:05:26 vnivanch Exp $
#
# Macro file for "test31.cc"
# 
/control/verbose 2
/run/verbose 1
/tracking/verbose 0
/event/verbose 0
/test31/verbose 0
#
/testem/phys/setCuts         1. mm
#/testem/phys/stepMax        0.1 mm
/testem/phys/addPhysics      standard
#/testem/phys/addPhysics     g4v52
#/testem/phys/addPhysics     standard70
#/testem/phys/addPhysics      lowenergy
#/test31/AbsorberMaterial    Beryllium
/test31/AbsorberMaterial     G4_W
/test31/AbsorberThick        10 mm
/test31/NumberOfAbsorbers    60
/test31/maxDeltaEnergy       1.0 MeV
#/test31/WorldMaterial        Vacuum
/test31/WorldMaterial        G4_Be
#
/gun/particle e-
/gun/energy 1 GeV
/run/initialize
/run/beamOn 1
#
/control/shell mkdir -p DataLE62He
/run/particle/setStoredInAscii 1
/run/particle/storePhysicsTable DataLE62He
#
