# $Id: storeTables.mac,v 1.1 2004-09-21 10:43:47 vnivanch Exp $
#
# Macro file for "testEm3.cc"
# 
/control/verbose 2
/run/verbose 1
/tracking/verbose 0
/event/verbose 0
/test31/verbose 0
#
/testem/phys/setCuts         1. mm
#/testem/phys/stepMax        0.1 mm
#/testem/phys/addPhysics      standard
#/testem/phys/addPhysics     g4v52
#/testem/phys/addPhysics     standard70
/testem/phys/addPhysics      lowenergy
#/testem/phys/addPhysics      lowenergyMA
#/test31/AbsorberMaterial    Beryllium
/test31/AbsorberMaterial     Tangsten
/test31/AbsorberThick        10 mm
/test31/NumberOfAbsorbers    60
/test31/maxDeltaEnergy       1.0 MeV
#/test31/WorldMaterial        Vacuum
/test31/WorldMaterial        Beryllium
#
/gun/particle e-
/gun/energy 1 GeV
/run/initialize
/run/beamOn 0
#
/control/shell mkdir -p DataLE62He
/run/particle/setStoredInAscii 1
/run/particle/storePhysicsTable DataLE62He
#
