#
# Macro file for the initialization phase of "TestEm9.cc"
#
# Sets some default verbose
# and initializes the graphic.
#
/control/verbose 1
/run/verbose 1
/testem/verbose 0
#
/testem/target1Material       Be
/testem/target2Material       He
/testem/target1Z              3 mm
/testem/target2Z              0.1 mm
#
/gun/particle e-
/gun/energy 50.0 MeV
/run/initialize
/testem/histoNumber           0
#
# Create empty scene ("world" is default)
/vis/scene/create
#
# Create a scene handler for a specific graphics system
# Edit the next line(s) to choose another graphic system
#
/vis/open OGLIX
#/vis/open OGLIXm
#
#/vis/open DAWNFILE
#
# Draw scene
/vis/viewer/set/viewpointThetaPhi 90 180 deg
/vis/viewer/zoom 1.2
/vis/viewer/flush
#
# for drawing the tracks
# if too many tracks cause core dump => storeTrajectory 0
/tracking/storeTrajectory 1
/vis/scene/endOfEventAction accumulate
#
#/testem/event/drawTracks all
#/testem/event/drawTracks charged

