#
# Macro file for the initialization phase of "test31.cc"
#
/testem/phys/setCuts         0.1 mm
#/testem/phys/stepMax        0.1 mm
/testem/phys/addPhysics      emstandard
/test31/AbsorberMaterial     G4_Si
/test31/AbsorberThick        10 mm
/test31/NumberOfAbsorbers    60
/test31/maxDeltaEnergy       1.0 MeV
/test31/WorldMaterial        G4_AIR
/test31/HistoNumber          5
/test31/gun/beamE            1000.0 MeV
/run/initialize
#
# Sets some default verbose
# and initializes the graphic.
#
# Create empty scene ("world" is default)
/vis/scene/create
#
# Create a scene handler for a specific graphics system
# Edit the next line(s) to choose another graphic system
#
####/vis/open DAWNFILE
/vis/open OGLIX
#
# Draw scene
/vis/viewer/set/viewpointThetaPhi -90 0 deg
/vis/viewer/zoom 1.4
/vis/viewer/flush
#
# for drawing the tracks
# if too many tracks cause core dump => storeTrajectory 0
/tracking/storeTrajectory 1
/vis/scene/endOfEventAction accumulate
#
#/testem/event/drawTracks all
