#
# Macro file for "TestEm14.cc"
# (can be run in batch, without graphic)
#
# e+ e- ---> gamma gamma
#
/control/verbose 2
/run/verbose 2
#
/testem/det/setMat Aluminium
#
/run/initialize
#
/process/inactivate eIoni
/process/inactivate eBrem
#
/gun/particle e+
/gun/energy 100 MeV
#
/analysis/setFileName anni
/analysis/h1/set 5  210  0. 105. MeV	#energy  of gamma  
/analysis/h1/set 6  200 -1. +1. none	#costeta of gamma
#
##/tracking/verbose 2
##/run/beamOn 1
#
/run/beamOn 100000
