# $Id: run06.mac,v 1.1 1999-08-05 11:14:04 maire Exp $
#
# Macro file for "TestEm3.cc" 
# (can be run in batch, without graphic)
#
# Fer-Silicium 10 layers; electron 2, 4, 6 GeV
#
# SICAPO Collaboration. NIM A345 (244-249) Oct.93
#
/control/verbose 2
#
/calor/setNbOfLayers 10
/calor/setNbOfAbsor 4
/calor/setAbsor 0 Iron    35.7 mm
/calor/setAbsor 1 NemaG10  0.2 mm
/calor/setAbsor 2 Silicium 0.4 mm
/calor/setAbsor 3 NemaG10  1.0 mm
/calor/setSizeYZ 16. cm
/calor/update
/gun/setDefault
#
/run/particle/setCut 1 mm
/run/initialize
#
/run/verbose 2
/event/drawTracks none
/event/printModulo 10
#/run/save on
#
/gun/particle e-
/gun/energy 6 GeV
/run/beamOn 500

