# $Id: run07.mac,v 1.1 1999-08-18 14:29:10 maire Exp $
#
# Macro file for "TestEm3.cc" 
# (can be run in batch, without graphic)
#
# LiquidArgon-Lead 2 layers; proton 500 MeV
#
/control/verbose 2
#
/calor/setNbOfLayers 2
/calor/setNbOfAbsor 2
/calor/setAbsor 0 liquidArgon 4 mm
/calor/setAbsor 1 Lead 4 mm
/calor/setSizeYZ 16 mm
/calor/update
/gun/setDefault
#
/run/particle/setCut 0.15 mm
/run/initialize
#
/run/verbose 2
/event/drawTracks none
/event/printModulo 100
#/run/save on
#
/gun/particle proton
/gun/energy 500 MeV
/run/beamOn 1000
