# $Id: run02.mac,v 1.2 1999-07-23 14:29:37 maire Exp $
#
# Macro file for "TestEm3.cc" 
# (can be run in batch, without graphic)
#
# Tungsten-Silicium 50 layers; electron 1 GeV
#
/control/verbose 2
#
/calor/setNbOfLayers 50
/calor/setNbOfAbsor 2
/calor/setAbsor 0 Tungsten 2 mm
/calor/setAbsor 1 Silicium 0.3 mm
/calor/update
/gun/setDefault
#
/run/particle/setCut 100 mum
/run/initialize
#
/run/verbose 2
/event/drawTracks none
/event/printModulo 100
#/run/save on
#
/gun/particle e-
/gun/energy 1 GeV
/run/beamOn 100
