########################################
#
# drawing projections
#
######/score/drawProjection boxMesh_1 eDep
######/score/drawProjection boxMesh_1 nOfStepGamma
######/score/drawProjection boxMesh_1 nOfStepEMinus
######/score/drawProjection boxMesh_1 nOfStepEPlus
#
########################################
#
# drawing slices
#
/score/colorMap/setMinMax ! 0. 400.
/control/loop drawSlice.mac iColumn 0 29 7
#
########################################
#
