# $Id: GNUmakefile,v 1.1 2006-02-27 10:05:24 kmura Exp $
# ===========================================================
#   Makefile for building local library
#
# ===========================================================
include ../../../config/config.gmk

MODULE := libXXX#

include $(G4PY_INSTALL)/config/mylib.gmk

