/control/verbose 2
/run/verbose 1
#
/gunExample/selectGunAction 4
#
/analysis/setFileName run4
/analysis/h1/set 4  100  0. 10.  mm       #vertex dN/dr for gun #4
/analysis/h1/set 5  90   0. 180 deg       #vertex dN/dteta for gun #4
/analysis/h1/set 6  180  0. 360 deg       #vertex dN/dphi for gun  #4
/analysis/h1/set 7  90   0. 180 deg       #moment dN/dalfa for gun #4
/analysis/h1/set 8  180  0. 360 deg       #moment dN/dpsi for gun  #4
#
/run/beamOn 1000000
