// This code implementation is the intellectual property of
// the RD44 GEANT4 collaboration.
//
// By copying, distributing or modifying the Program (or any work
// based on the Program) you indicate your acceptance of this statement,
// and all its terms.
//
// $Id: G4TrackFastVector.hh,v 1.1 1999-01-07 16:14:24 gunter Exp $
// GEANT4 tag $Name: not supported by cvs2svn $
//
// 
// ------------------------------------------------------------
//	GEANT 4 class header file 
//
//	For information related to this code contact:
//	CERN, CN Division, ASD group
//	History: first implementation, based on object model of
//	8 Mar 1997, H.Kurashige
// ------------------------------------------------------------

#ifndef G4TrackFastVector_h
#define G4TrackFastVector_h 1

#include "globals.hh"
#include "G4ios.hh"

class G4Track;
#include "G4FastVector.hh"

const G4int G4TrackFastVectorSize = 512;
class G4TrackFastVector:
      public G4FastVector<G4Track,G4TrackFastVectorSize>
{};
//  Contains pointers to G4Track objects which are
//  generated by either primary or secondary interaction.

#endif

