###################################################
# Visualization of detector geometry and events  
###################################################

# create empty scene
/vis/scene/create

# Create a scene handler for a specific graphics system
/vis/open OGLIX

# draw scene
/vis/viewer/zoom 1.4
/vis/viewer/flush

# (if you prefer refreshing each event, comment out next line)
/vis/scene/endOfEventAction accumulate
