#-*-python-*-

Application = "G4Analysis"

WorkerInitData = {
    'G4ApplicationComponentName' : "G4Brachy",
    'initMacroFile' : """
/control/verbose 1
/run/verbose 0
/event/verbose 0
/source/switch Iodium
/run/energy Iodium
/run/initialize
"""
}

JobInitData = {
    'runParams' : {
       'seed' : 0 ,
       'eventNumber' : 5000,
       'macroFileTemplate': "/run/beamOn " },
    'eventsPerWorker' : 500,
    'workerInit' : WorkerInitData
    }

