/vis/modeling/trajectories/drawByParticleID-0/default/setDrawStepPts false

# end time of chemistry in ns (change units in chemistry.loop
/control/alias endTime 95
/vis/viewer/set/timeWindow/startTime 0 ps
#/vis/viewer/set/timeWindow/endTime 1 ps

/vis/viewer/set/timeWindow/fadeFactor 0
/vis/viewer/set/timeWindow/displayHeadTime true -0.1 -0.8 24 1.0 0.0 0.0
/control/alias timeWindow 5
/control/loop movie_chemistry.loop startTime -{timeWindow} {endTime} 1

