# $Id: phot.mac,v 1.3 2003/10/06 10:02:20 maire Exp $
#
# Macro file for "TestEm1.cc"
# (can be run in batch, without graphic)
#
#  PhotoElectricEffect; Gamma 1 Mev
#
/control/verbose 2
/run/verbose 2
#
/testem/det/setMat Germanium
/testem/det/setSize 1 cm
#
/run/initialize
#
/testem/gun/setDefault 1
/gun/particle gamma
/gun/energy 1 MeV
/testem/gun/rndm  0.8
#
/tracking/verbose 1
#
#/run/particle/applyCuts
#
#/run/beamOn 100000
