# $Id: photon.mac,v 1.1 2006-01-24 18:29:07 maire Exp $
#
# Macro file for "TestEm1.cc"
#
#  Photon beam; 300 keV
#  For interactive visualisation
#
/control/verbose 2
/run/verbose 2
#
/testem/det/setMat Germanium
/testem/det/setSize 1 cm
#
/run/initialize
#
/control/execute vis.mac
#
/testem/gun/setDefault 
/gun/particle gamma
/gun/energy 300 keV
# spread beam spot
/testem/gun/rndm 0.8
#
/tracking/verbose 1
#
/run/beamOn 20
