# $Id: range.mac,v 1.4 2005/06/01 10:20:12 maire Exp $
#
# Macro file for "TestEm1.cc"
# 
# compute the range of primary particle
#
/control/verbose 2
/run/verbose 2
#
/testem/det/setMat Water
/testem/det/setSize 10 cm
#
/testem/phys/addPhysics  standard
/testem/phys/setCuts 1 km
#
/run/initialize
#
/process/inactivate msc
/process/eLoss/fluct false
#
/testem/gun/setDefault
/gun/particle proton
/gun/energy 100 MeV
#
/testem/event/printModulo 1000
#
/run/beamOn 1000
