# $Id: run07.mac,v 1.4 2002-03-08 13:43:28 maire Exp $
#
# Macro file for "TestEm1.cc"
# (can be run in batch, without graphic)
#
# Gamma conversion and e+ annihilation; gamma 100 MeV
#
/control/verbose 2
#
/run/particle/setGCut  95 cm
/run/particle/setECut  30 mm
#
/run/initialize
#
/process/inactivate phot
/process/inactivate compt
/process/inactivate msc
#
/process/eLoss/StepFunction 0.183 170 micrometer
#
/run/verbose 2
#
/gun/particle gamma
/gun/energy 100 MeV
/run/beamOn 1000
