# $Id: run05.mac,v 1.5 2002-12-11 14:19:18 maire Exp $
#
# Macro file for "TestEm1.cc"
# (can be run in batch, without graphic)
#
# full Brems only; e- 1 GeV
#
/control/verbose 2
#
/testem/phys/setGCut  2.2 mm
/testem/phys/setECut  95 cm
#
/run/initialize
#
/process/inactivate phot
/process/inactivate compt
/process/inactivate conv
/process/inactivate msc
#
/process/eLoss/StepFunction 0.183 170 micrometer
#
/run/verbose 2
#
/gun/particle e-
/gun/energy 1 GeV
/run/beamOn 100
