# $Id: run08.mac,v 1.4 2002-03-08 13:43:28 maire Exp $
#
# Macro file for "TestEm1.cc"
# (can be run in batch, without graphic)
#
# electron 100 MeV; all processes
#
/control/verbose 2
#
/run/particle/setGCut  2.2 mm
/run/particle/setECut  6.05 micrometer
#
/run/initialize    
#
/process/eLoss/StepFunction 0.183 170 micrometer
#
/run/verbose 2
#
/gun/particle e-
/gun/energy 100 MeV
/run/beamOn 100
