# $Id: run04.mac,v 1.3 2001-10-26 12:51:21 maire Exp $
#
# Macro file for "TestEm1.cc"
# (can be run in batch, without graphic)
#
# full Ionisation only; e- 100 MeV
#
/control/verbose 2
#
/run/initialize
#
/process/eLoss/StepFunction 0.183 170 micrometer
/calor/cutG  95 cm
/calor/cutE  100. micrometer
#
/process/inactivate phot
/process/inactivate compt
/process/inactivate conv
/process/inactivate msc
#
/run/verbose 2
#
/gun/particle e-
/gun/energy 100 MeV
/run/beamOn 100
