# $Id: run07.mac,v 1.5 2002-12-11 14:19:18 maire Exp $
#
# Macro file for "TestEm1.cc"
# (can be run in batch, without graphic)
#
# Gamma conversion and e+ annihilation; gamma 100 MeV
#
/control/verbose 2
#
/testem/phys/setGCut  95 cm
/testem/phys/setECut  30 mm
#
/run/initialize
#
/process/inactivate phot
/process/inactivate compt
/process/inactivate msc
#
/process/eLoss/StepFunction 0.183 170 micrometer
#
/run/verbose 2
#
/gun/particle gamma
/gun/energy 100 MeV
/run/beamOn 1000
