# $Id: run03.mac,v 1.4 2002-03-08 13:43:28 maire Exp $
#
# Macro file for "TestEm1.cc"
# (can be run in batch, without graphic)
#
# Eloss+Muls only; no fluctuation; e- 10 MeV
#
/control/verbose 2
#
/run/particle/setGCut  95 cm
/run/particle/setECut  95 cm
#
/run/initialize
#
/process/inactivate phot
/process/inactivate compt
/process/inactivate conv
#
/process/eLoss/StepFunction 0.183 170 micrometer
/process/eLoss/fluct 0
#
/run/verbose 2
#
/gun/particle e-
/gun/energy 10 MeV
/run/beamOn 100
