# $Id: run06.mac,v 1.3 2001-10-31 15:36:44 maire Exp $
#
# Macro file for "TestEm1.cc"
# (can be run in batch, without graphic)
#
# Compton + PhotoElectricEffect; Gamma 10 Mev
#
/control/verbose 2
#
/calor/cutG  95 cm
/calor/cutE  95 cm
#
/run/initialize
#
/process/inactivate conv
/process/inactivate msc
#
/process/eLoss/StepFunction 0.183 170 micrometer
#
/run/verbose 2
#
/gun/particle gamma
/gun/energy 10 MeV
/run/beamOn 1000
