# $Id: run02.mac,v 1.2 2001-10-26 12:51:21 maire Exp $
#
# Macro file for "TestEm1.cc"
# (can be run in batch, without graphic)
#
# Eloss only; glandz fluctuations; e- 1 GeV
#
/control/verbose 2
#
/run/initialize
#
/process/eLoss/StepFunction 0.183 170 micrometer
/calor/cutG  95 cm
/calor/cutE  95 cm
#
/process/inactivate phot
/process/inactivate compt
/process/inactivate conv
/process/inactivate msc
/process/eLoss/fluct 1
#
/run/verbose 2
#
/gun/particle e-
/gun/energy 1 GeV
/run/beamOn 100
