# $Id: run05.mac,v 1.3 2001-10-31 15:36:44 maire Exp $
#
# Macro file for "TestEm1.cc"
# (can be run in batch, without graphic)
#
# full Brems only; e- 1 GeV
#
/control/verbose 2
#
/calor/cutG  2.2 mm
/calor/cutE  95 cm
#
/run/initialize
#
/process/inactivate phot
/process/inactivate compt
/process/inactivate conv
/process/inactivate msc
#
/process/eLoss/StepFunction 0.183 170 micrometer
#
/run/verbose 2
#
/gun/particle e-
/gun/energy 1 GeV
/run/beamOn 100
