//---------------------------------------
//        Macro file for test30
//         examine PostStepDoIt
//        for hadronic physics
//      Created: 13.03.2002 V.Ivanchenko
//---------------------------------------
#verbose
0
#events
100000
//--------Proton_processes
#particle
alpha
//--------
#material
Al
#energy(MeV)
140.
#sigmae(MeV)
0.5
#emax(MeV)
150.
#nbinse
50
#nbinsd
50
#elim(MeV)
1.
#nangle
5
#angles
20. 30. 45. 60. 120.
#dangle
5.
//--------
#generator
binary
#paw
bin.paw
#run
//--------Exit
#exit
