#
/control/execute vis.mac
#
########################################
#
#/score/verbose 10
#
/score/create/cylinderMesh cylinderMesh_1
#
/score/mesh/cylinderSize 100. 100. cm
/score/mesh/translate/xyz 0. 0. 0. cm
#                Nr Nz Nphi
/score/mesh/nBin 30 30 30

#
/score/quantity/energyDeposit eDepPS
/score/quantity/nOfStep nOfStepPSgamma
/score/filter/particle gammaFilter gamma
/score/quantity/nOfStep nOfStepPSeMinus
/score/filter/particle eMinusFilter e-
/score/quantity/nOfStep nOfStepPSePlus
/score/filter/particle ePlusFilter e+
#
/score/close
#
########################################
#
/score/list
#
#/vis/disable
#/run/beamOn 200
/run/beamOn 10
#/vis/enable
#
########################################
#
#/vis/scene/create
#/vis/sceneHandler/attach scene-2
#/vis/viewer/flush
#/vis/drawVolume
#/score/colorMap/setMinMax ! 0. 800.
#/control/loop test4a.mac iColumn 0 29 6
#
#/vis/drawVolume 
#/score/dumpQuantityToFile cylinderMesh_1 eDepPS eDep.txt
#/vis/drawVolume 
#/score/drawProjection cylinderMesh_1 nOfStepPSgamma
/vis/drawVolume 
/score/drawProjection cylinderMesh_1 eDepPS
/vis/drawVolume 
/control/loop test7a.mac iColumn 0 29 6
/vis/drawVolume 
/control/loop test7b.mac iColumn 0 29 6
/vis/drawVolume 
/control/loop test7c.mac iColumn 0 29 6

