#
/control/execute vis.mac
#
########################################
#
#/score/verbose 10
/score/create/cylinderMesh cylinderMesh_1
#
/score/mesh/cylinderSize 100. 100. cm
/score/mesh/translate/xyz 0. 0. 0. cm
#                Nr Nz Nphi
#/score/mesh/nBin 2 2 3
#/score/mesh/nBin 10 10 12
/score/mesh/nBin 30 30 30

#
/score/quantity/energyDeposit eDepPS
/score/quantity/nOfStep nOfStepPSgamma
/score/filter/particle gammaFilter gamma
/score/quantity/nOfStep nOfStepPSeMinus
/score/filter/particle eMinusFilter e-
/score/quantity/nOfStep nOfStepPSePlus
/score/filter/particle ePlusFilter e+
#
/score/close
#
########################################
#
/score/list
#
/run/beamOn 100
#
########################################
#
#/vis/scene/create
#/vis/sceneHandler/attach scene-2
#/vis/viewer/flush
#/vis/drawVolume worlds
#/score/colorMap/setMinMax ! 0. 800.
#/control/loop test4a.mac iColumn 0 29 7
#
#/score/dumpQuantityToFile cylinderMesh_1 eDepPS eDep.txt
/score/drawProjection cylinderMesh_1 nOfStepPSgamma
#/score/drawProjection cylinderMesh_1 eDepPS


