#
/control/execute vis.mac
#
########################################
#
/score/create/boxMesh boxMesh_1
#
/score/mesh/boxSize 1. 1. 1. m
/score/mesh/nBin 10 10 10
#
/score/quantity/energyDeposit eDepPS
/score/quantity/nOfStep nOfStepPSgamma
/score/filter/particle gammaFilter gamma
/score/quantity/nOfStep nOfStepPSeMinus
/score/filter/particle eMinusFilter e-
/score/quantity/nOfStep nOfStepPSePlus
/score/filter/particle ePlusFilter e+
#
/score/close
#
########################################
#
/score/create/boxMesh boxMesh_2
#
/score/mesh/boxSize 100. 100. 20. cm
/score/mesh/nBin 50 50 20
#
/score/quantity/energyDeposit eDepPS
/score/quantity/nOfStep nOfStepPSgamma
/score/filter/particle gammaFilter gamma
/score/quantity/nOfStep nOfStepPSeMinus
/score/filter/particle eMinusFilter e-
/score/quantity/nOfStep nOfStepPSePlus
/score/filter/particle ePlusFilter e+
#
/score/close
#
########################################
#
/score/list
#
/vis/disable
/run/beamOn 100
/vis/enable
#
########################################
#
#/vis/scene/create
#/vis/sceneHandler/attach scene-2
#/vis/viewer/flush
#
/score/drawProjection boxMesh_1 nOfStepPSgamma
#/score/drawProjection boxMesh_2 nOfStepPSgamma ! 11
#
