#
/control/execute vis.mac
/control/verbose 2
#
########################################
#
/score/create/boxMesh boxMesh_1
#
/score/mesh/boxSize 30. 30. 20. cm
/score/mesh/translate/xyz 0. 0. -80. cm
/score/mesh/nBin 20 20 20
#
/score/quantity/energyDeposit eDepPS
/score/quantity/nOfStep nOfStepPSgamma
/score/filter/particle gammaFilter gamma
/score/quantity/nOfStep nOfStepPSeMinus
/score/filter/particle eMinusFilter e-
/score/quantity/nOfStep nOfStepPSePlus
/score/filter/particle ePlusFilter e+
#
/score/close
#
########################################
#
/score/create/boxMesh boxMesh_2
#
/score/mesh/boxSize 60. 60. 30. cm
/score/mesh/translate/xyz 0. 0. -30. cm
/score/mesh/nBin 50 50 25
#
/score/quantity/energyDeposit eDepPS
/score/quantity/nOfStep nOfStepPSgamma
/score/filter/particle gammaFilter gamma
/score/quantity/nOfStep nOfStepPSeMinus
/score/filter/particle eMinusFilter e-
/score/quantity/nOfStep nOfStepPSePlus
/score/filter/particle ePlusFilter e+
#
/score/close
#
########################################
#
/score/create/boxMesh boxMesh_3
#
/score/mesh/boxSize 100. 100. 50. cm
/score/mesh/translate/xyz 0. 0. 50. cm
/score/mesh/nBin 50 50 25
#
/score/quantity/energyDeposit eDepPS
/score/quantity/nOfStep nOfStepPSgamma
/score/filter/particle gammaFilter gamma
/score/quantity/nOfStep nOfStepPSeMinus
/score/filter/particle eMinusFilter e-
/score/quantity/nOfStep nOfStepPSePlus
/score/filter/particle ePlusFilter e+
#
/score/close
#
########################################
#
/score/list
#
/run/beamOn 100
#
########################################
#
/score/drawProjection boxMesh_3 nOfStepPSgamma
/score/drawProjection boxMesh_2 nOfStepPSgamma
/score/drawProjection boxMesh_1 nOfStepPSgamma
#
