#
/score/create/boxMesh boxMesh_1
#
/score/mesh/boxsize 100. 100. 100. cm
#########/score/mesh/nbin 2 2 3
/score/mesh/nbin 50 50 50
#
/score/quantity/eDep eDepPS
/score/quantity/nOfStep nOfStepPSgamma
/score/filter/particle gammaFilter gamma
/score/quantity/nOfStep nOfStepPSeMinus
/score/filter/particle eMinusFilter e-
/score/quantity/nOfStep nOfStepPSePlus
/score/filter/particle ePlusFilter e+
#
/score/close
/score/list
#
/run/constructScoringWorlds
#
