#
# A sample macro of user-defined score writer inherited from G4VScoreWriter 
# class.
#
# Add the following lines
# before main() function in test1.cc
#
#   #include "Tst1UserScoreWirter.hh"
#
# and after G4ScoringManager is instanciated in test1.cc
#
#   scManager->SetScoreWriter(new Tst1UserScoreWriter());
#
# If no user-defined score writer is registered, a default score writer 
# of G4VScoreWriter is invoked. 
#
#
/score/create/boxMesh boxMesh_1
#
/score/mesh/boxSize 100. 100. 100. cm
/score/mesh/translate/xyz 0. 0. 0. cm
/score/mesh/nBin 50 50 50
#
/score/quantity/energyDeposit eDepPS
#
/score/quantity/nOfStep nOfStepPSgamma
/score/filter/particle gammaFilter gamma
#
/score/quantity/nOfStep nOfStepPSeMinus
/score/filter/particle eMinusFilter e-
#
/score/quantity/nOfStep nOfStepPSePlus
/score/filter/particle ePlusFilter e+
#
/score/close
#
/run/constructScoringWorlds
#
/run/beamOn 1000
/score/dumpQuantityToFile boxMesh_1 eDepPS eDep.txt
/score/dumpQuantityToFile boxMesh_1 nOfStepPSgamma nOfStep-Gamma.txt
/score/dumpQuantityToFile boxMesh_1 nOfStepPSeMinus nOfStep-eMinus.txt
/score/dumpQuantityToFile boxMesh_1 nOfStepPSePlus nOfStep-ePlus.txt
#

