#
/control/execute vis.mac
#
########################################
#
/score/create/boxMesh boxMesh_1
#
/score/mesh/boxSize 100. 100. 100. cm
/score/mesh/translate/xyz 0. 0. 0. cm
/score/mesh/nBin 30 30 30
#
/score/quantity/energyDeposit eDepPS
/score/quantity/nOfStep nOfStepPSgamma
/score/filter/particle gammaFilter gamma
/score/quantity/nOfStep nOfStepPSeMinus
/score/filter/particle eMinusFilter e-
/score/quantity/nOfStep nOfStepPSePlus
/score/filter/particle ePlusFilter e+
#
/score/close
#
########################################
#
/score/list
#
/vis/disable
/run/beamOn 100
/vis/enable
#
########################################
#
/vis/scene/create
/vis/sceneHandler/attach scene-2
/vis/viewer/flush
/score/colorMap/setMinMax ! 0. 800.
/control/loop test4a.mac iColumn 0 29 7
#
