#
/control/execute vis.mac
#
########################################
#
/score/create/cylinderMesh cylinderMesh_1
#
/score/mesh/cylinderSize 1. 1. m
/score/mesh/translate/xyz 0. 0. 0. cm
#
/score/mesh/nBin 30 30 30
#
/score/quantity/energyDeposit eDepPS
/score/quantity/nOfStep nOfStepPSgamma
/score/filter/particle gammaFilter gamma
/score/quantity/nOfStep nOfStepPSeMinus
/score/filter/particle eMinusFilter e-
/score/quantity/nOfStep nOfStepPSePlus
/score/filter/particle ePlusFilter e+
#
/score/close
#
########################################
#
/score/list
#
/vis/disable
/run/beamOn 100
/vis/enable
#
########################################
#
/vis/scene/notifyHandlers
/score/drawProjection cylinderMesh_1 nOfStepPSgamma ! 10
/score/drawProjection cylinderMesh_1 nOfStepPSgamma logColorMap 101
/score/drawProjection cylinderMesh_1 eDepPS logColorMap 101
#
