# $Id: exo5q2.mac,v 1.8 2006-03-20 12:26:03 maire Exp $
#
# Macro file for "TestEm3.cc" 
#
# Tungsten 1 layer;
#
/control/verbose 2
#
/testem/det/setNbOfLayers 1
/testem/det/setNbOfAbsor  1
/testem/det/setAbsor 1 Tungsten 50 um
/testem/det/setSizeYZ 70 um
#
/testem/phys/setCuts 5 cm
#
/run/initialize
#
/control/execute vis.mac
#
/testem/gun/setDefault
/gun/particle e-
/gun/energy 600 keV
#
/testem/stepMax/absorber 1 1 um
#
/run/beamOn 1
#
#/testem/gun/rndm 0.5
#/run/beamOn 10
