# $Id: exo5q1.mac,v 1.5 2003/09/23 17:27:32 maire Exp $
#
# Macro file for "TestEm3.cc" 
#
# Aluminium 1 layer;
#
/control/verbose 2
#
/testem/det/setNbOfLayers 1
/testem/det/setNbOfAbsor  1
/testem/det/setAbsor 0 Aluminium 10 cm
/testem/det/setSizeYZ 10 cm
#
/testem/phys/setCuts 5 cm
#
/run/initialize
#
/control/execute vis.mac
#
/testem/gun/setDefault
/gun/particle pi+
/gun/energy 200 MeV
/gun/position -6. +2.5 0. cm
#
#/run/beamOn 10
#
#/gun/energy 1 GeV
