# $Id: exo5q2.mac,v 1.5 2003/09/23 17:27:32 maire Exp $
#
# Macro file for "TestEm3.cc" 
#
# Tungsten 1 layer;
#
/control/verbose 2
#
/testem/det/setNbOfLayers 1
/testem/det/setNbOfAbsor  1
/testem/det/setAbsor 0 Tungsten 50 mum
/testem/det/setSizeYZ 70 mum
#
/testem/phys/setCuts 5 cm
#
/run/initialize
#
/control/execute vis.mac
#
/testem/gun/setDefault
/gun/particle e-
/gun/energy 600 keV
#
/testem/tracking/stepMax 1 mum
#
/run/beamOn 1
#
#/testem/gun/rndm 0.5
#/run/beamOn 10
