# $Id: exo5q2.mac,v 1.2 2002-12-12 11:19:33 maire Exp $
#
# Macro file for "TestEm3.cc" 
#
# Tungsten 1 layer;
#
/control/verbose 2
#
/run/particle/setCut 5 cm
/run/initialize
#
/testem/det/setNbOfLayers 1
/testem/det/setNbOfAbsor 1
/testem/det/setAbsor 0 Tungsten 50 mum
/testem/det/setSizeYZ 70 mum
/testem/det/update
#
/testem/gun/setDefault
#
/control/execute vis.mac
#
/gun/particle e-
/gun/energy 600 keV
#
/testem/tracking/stepMax 1 mum
