# $Id: retrieveTables.mac,v 1.4 2007/05/18 19:00:44 vnivanch Exp $
#
# Macro file for "exampleN03.cc"
# 
# can be run in batch, without graphic
# or interactively: Idle> /control/execute run1.mac
#
/control/verbose 2
#
#  select EM PhysicsList
#
/testem/phys/addPhysics  emstandard
#
/run/particle/retrievePhysicsTable physdata
/run/initialize
#
/gun/particle e-
/gun/energy 1 GeV
#
/run/beamOn 3
#
/run/particle/storePhysicsTable physdata1
#
