# $Id: retrieveTables.mac 66241 2012-12-13 18:34:42Z gunter $
#
# Macro file for "exampleN03.cc"
# 
# can be run in batch, without graphic
# or interactively: Idle> /control/execute run1.mac
#
/control/verbose 2
#
#  select EM PhysicsList
#
/testem/phys/addPhysics  emstandard_opt0
#
/run/particle/retrievePhysicsTable physdata
/run/initialize
/process/eLoss/verbose 1
/process/eLoss/CSDARange true
#
/gun/particle e-
/gun/energy 1 GeV
#
/run/beamOn 3
#
/run/particle/storePhysicsTable physdata1
#
