# $Id: retrieveTables.mac,v 1.5 2008/09/14 17:14:54 vnivanch Exp $
#
# Macro file for "exampleN03.cc"
# 
# can be run in batch, without graphic
# or interactively: Idle> /control/execute run1.mac
#
/control/verbose 2
#
#  select EM PhysicsList
#
/testem/phys/addPhysics  emstandard
#
/run/particle/retrievePhysicsTable physdata
/run/initialize
/process/eLoss/verbose 1
/process/eLoss/CSDARange true
#
/gun/particle e-
/gun/energy 1 GeV
#
/run/beamOn 3
#
/run/particle/storePhysicsTable physdata1
#
