# $Id: run01.mac,v 1.7 2003-03-06 18:16:15 maire Exp $
#
# Macro file for "exampleN03.cc" 
# (can be run in batch, without graphic)
#
# Lead-liquidArgon 50 layers; electron 1 GeV
#
/control/verbose 2
#
#  select EM PhysicsList
#
#/testem/phys/addPhysics  model
/testem/phys/addPhysics  standard
#
#/testem/phys/setCuts 0.5 mm
/run/initialize
#
/run/verbose 2
/event/printModulo 50
#
/gun/particle e-
/gun/energy 1 GeV
/run/beamOn 200
