# $Id: storeTables.mac,v 1.8 2007/05/18 19:00:44 vnivanch Exp $
#
# Macro file for "testEm3.cc"
# 
# can be run in batch, without graphic
# or interactively: Idle> /control/execute run1.mac
#
/control/verbose 2
#
/testem/phys/addPhysics  emstandard
#
/run/initialize
/run/beamOn 3
#
/run/particle/storePhysicsTable physdata
#
/gun/particle e-
/gun/energy 1 GeV
#
#/run/beamOn 3	
#
/run/particle/retrievePhysicsTable physdata
#
/random/resetEngineFrom currentRun.rndm
/run/beamOn 3
#
