# $Id: GNUmakefile,v 1.1 2000-07-24 11:23:46 gcosmo Exp $
# ----------------------------------------------------------------

name := cltog4
G4TARGET := $(name)
G4EXLIB := true

ifndef G4INSTALL
  G4INSTALL = ../../../..
endif

.PHONY: all
all: lib bin

include $(G4INSTALL)/config/binmake.gmk
