//---------------------------------------
//        Macro file for test30
//         examine PostStepDoIt
//        for hadronic physics
//      Created: 13.03.2002 V.Ivanchenko
//---------------------------------------
#verbose
0
#events
100000
//--------Proton_processes
#particle
alpha
//--------
#material
Al
#energy(MeV)
26.8
#sigmae(MeV)
0.5
#emax(MeV)
30.
#nbinse
60
#nbinsd
60
#elim(MeV)
1.
#nangle
5
#angles
30. 60. 90. 120. 150.
#dangle
10.
//--------
#generator
binary
#paw
bin.paw
#run
//--------Exit
#exit
