//---------------------------------------
//        Macro file for test30
//         examine PostStepDoIt 
//        for hadronic physics
//      Created: 13.03.2002 V.Ivanchenko
//--------------------------------------- 
#verbose
0
#events
200000
//--------Proton_processes
#particle
proton
//--------
#material
Be
#energy(MeV)
256.
#emax(MeV)
280.
#nbinse
70
#nbinsd
28
#elim(MeV)
2.
#nangle
5
#angles
7.5 30. 60. 120. 150.
#dangle
5.0
//--------
#generator
kinetic
#paw
kin.paw
#run
//--------Exit
#exit
