/control/verbose 1
/tracking/verbose 0
/run/verbose 0
/event/verbose 0
/physics/addPhysics photon-epdl
/physics/addPhysics electron-eedl
/physics/addPhysics positron-standard
/physics/cutE 0.00118 mm
/physics/facRange 0.005
########
/run/initialize
/target/setTargetMat Beryllium
/target/setTargetThick 1.3 mm
/target/voxelNumber 50
/target/setMaxStep  0.00118 mm
/gun/energy 0.521 MeV
/run/beamOn 50
















