/control/verbose 1
/tracking/verbose 0
/run/verbose 0
/event/verbose 0
/physics/addPhysics photon-standard
/physics/addPhysics electron-standard
/physics/addPhysics positron-standard
#/physics/facRange 0.005
/physics/cutE 0.001674 mm
########
/run/initialize
#/target/voxelNumber 100
/target/setTargetThick 8.37 mm
#/target/voxelNumber 200
/target/setMaxStep  0.001674 mm
/gun/energy 0.521 MeV
#/tracking/verbose 1
/run/beamOn 10








