# # # # # # # # # # # # #
# Example macro
#
#
# Anton.Lechner@cern.ch
# # # # # # # # # # # # #
#
#
# VERBOSE LEVELS
# ---------------
#
/control/verbose  0
/tracking/verbose 0
/run/verbose      0
/event/verbose    0
#
#
# PHYSICS
# -------
# 
/physics/physConstructor Photon-EPDL
/physics/physConstructor Electron-EEDL
/physics/physConstructor Positron-Standard
/physics/prodThreshold   0.0005 mm
#
#
# RUN INITIALIZATION
# ------------------ 
#
/run/initialize
#
#
# TARGET DESCRIPTION
# ------------------
# 
/target/radius      1.27 cm
/target/maxStepSize 0.001 mm
#
# Infinite Slab
/target/layerThickness 0.381 cm
/target/layerMaterial  Aluminium
#
#
# CALORIMETER DESCRIPTION
# -----------------------
#
/target/calThickness 0.01 mm
/target/calPosition  0.005 mm
/target/calPosition  0.015 mm
/target/calPosition  0.025 mm
/target/calPosition  0.035 mm
/target/calPosition  0.045 mm
/target/calPosition  0.055 mm
/target/calPosition  0.065 mm
/target/calPosition  0.075 mm
/target/calPosition  0.085 mm
/target/calPosition  0.095 mm
/target/calPosition  0.105 mm
/target/calPosition  0.115 mm
#
#
# SOURCE DESCRIPTION
# ------------------
#
/source/primEnergy    0.058 MeV
/source/sigmaEnergy   0 keV
/source/sigmaSpatial  0.00 mm
/source/incidentAngle 15.0 deg
#
#
# RUN
# ---
#
/run/beamOn 10










