# $Id: GNUmakefile,v 1.2 2006-04-25 07:54:29 kmura Exp $
# ===========================================================
#   Makefile for building Python module with Boost.Python
#      
# ===========================================================
include ../../config/config.gmk

# python module name
MODULE := test08#

COMPILE_WITH_BOOST := true
include $(G4PY_INSTALL)/config/module.gmk

