//---------------------------------------
//        Macro file for test30
//         examine PostStepDoIt
//        for hadronic physics
//      Created: 13.03.2002 V.Ivanchenko
//---------------------------------------
#verbose
0
#events
1000000
//--------Proton_processes
//#particle
#ion
6 12
//--------
#material
C
#energy(MeV)
3480.
// 12 * 290 MeV
#sigmae(MeV)
0.5
#emax(MeV)
700.
#nbinse
100
#nbinsd
100
#elim(MeV)
1.
#nangle
7
#angles
5. 10. 20. 30. 40. 60. 80.
#dangle
2.
//--------
#generator
binary_ion
#paw
bin.paw
#run
//--------Exit
#exit
