#
/control/verbose 2
/run/verbose 2
#
/testem/det/setMat G4_WATER
/testem/det/setRadius  100 nm
#
/testem/phys/addPhysics  dna_opt2	
#/testem/phys/addPhysics  dna_opt4	
#/testem/phys/addPhysics  dna_opt6	
#
/run/initialize
#
/gun/particle e-
/gun/energy 1 keV
#
/analysis/setFileName dna
/analysis/h1/set 1 50  0.   100 nm	#edep profile
/analysis/h1/set 3 50  0.   300 nm	#true track length
#
/testem/applyAutomaticStepMax true
#
/run/printProgress 1000
#
/run/beamOn 5000
