//---------------------------------------
//        Macro file for test30
//         examine PostStepDoIt 
//        for hadronic physics
//      Created: 13.03.2002 V.Ivanchenko
//--------------------------------------- 
#verbose
0
#events
20000
//--------Proton_processes
#particle
proton
//--------
#material
Fe
#energy(MeV)
597.
#sigmae(MeV)
1.5
#emax(MeV)
600.
#elim(MeV)
2.
#nbinse
200
#nbinsd
80
#nangle
5
#angles
30. 60. 90. 120. 150.
#dangle
10.
//--------
#generator
kinetic
#paw
kin.paw
#run
//---------Exit
#exit



