//---------------------------------------
//        Macro file for test30
//         examine PostStepDoIt 
//        for hadronic physics
//      Created: 13.03.2002 V.Ivanchenko
//--------------------------------------- 
#verbose
0
#events
20000
//--------Proton_processes
#particle
proton
//--------
#material
Fe
#energy(MeV)
597.
#sigmae(MeV)
1.5
#emax(MeV)
600.
#emaxpi(MeV)
300.
#elim(MeV)
2.
#nbinse
120
#nbinsd
60
#nbinspi
30
#nangle
5
#angles
30. 60. 90. 120. 150.
#dangle
10.
//--------
#generator
kinetic
#paw
kin.paw
#run
//---------Exit
#exit



