# $Id: run1.mac,v 1.4 2010-06-06 06:24:26 perl Exp $
#
# Macro file for "LHCbRichSim.cc"
# 
/control/verbose 2
/control/saveHistory
#
#run/verbose 4
#event/verbose 4
#tracking/verbose 5
#process/verbose 4
#particle/process/verbose 4

/hits/list 
/hits/activate
/hits/verbose 4
/tracking/storeTrajectory 1

/gun/particle pi-
/gun/energy 10 GeV

/gun/xvertex 0.000 mm
/gun/yvertex 0.000 mm
/gun/zvertex -20.000 mm

/run/beamOn 2
 




