### E. coli bacterium

#
# See more details on moleculardna specific UI commands:
# - https://geant4-dna.github.io/molecular-docs/docs/overview/configuration
# - https://geant4-dna.github.io/molecular-docs/docs/overview/macro-anatomy
# - the README file
# - the messenger classes of the moleculardna example
#

# Verbosity: settings
/control/verbose 1
/run/verbose 2
/dnageom/verbose 1
#/tracking/verbose 2

# Chemistry: selection of IRT_syn
/process/chem/TimeStepModel IRT_syn

# Chemistry: activation
/chem/activate true

# Chemistry: verbosity
/scheduler/verbose 0

# Chemistry: end time of chemistry stage
/scheduler/endTime 1 us

# Geometry: size of World volume
/world/worldSize 8 um

# Geometry: optimisation of voxelisation
/dnageom/setSmartVoxels 1

# Geometry: creation
# See https://geant4-dna.github.io/molecular-docs/docs/examples/bacterial-cell
#  - Side length for each placement
/dnageom/placementSize 50 50 50 nm
#  - Scaling of XYZ in fractal definition file
/dnageom/fractalScaling 50 50 50 nm
#  - Path to file that defines placement locations
/dnageom/definitionFile geometries/bacteria-XFXFXFX-4.txt
#  - Set placement volumes
/dnageom/placementVolume turn geometries/8strands_50nm_turn.txt
/dnageom/placementVolume turntwist geometries/8strands_50nm_turn.txt true
/dnageom/placementVolume straight geometries/8strands_50nm_straight.txt

# Geometry: distance from base pairs at which radicals are killed
/dnageom/radicalKillDistance 4 nm

# Geometry: deposited energy accumulation range limit to start recording SBs from direct effects
/dnageom/interactionDirectRange 6 angstrom

# Damage: model settings
/dnadamage/directDamageLower 17.5 eV
/dnadamage/directDamageUpper 17.5 eV

/dnadamage/indirectOHBaseChance 1.0
/dnadamage/indirectOHStrandChance 0.4
/dnadamage/inductionOHChance 0.

/dnadamage/indirectHBaseChance 1.0
/dnadamage/indirectHStrandChance 0.4
/dnadamage/inductionHChance 0.0

/dnadamage/indirectEaqBaseChance 1.0
/dnadamage/indirectEaqStrandChance 0.4
/dnadamage/inductionEaqChance 0.0

# Analysis: add ellipsoid chromosomal region of interest, with the name "bacteria"
/chromosome/add bacteria ellipse 900 400 400 0 0 0 nm 0 0 0

# Analysis: save plot data to specified file
#/chromosome/plotData chromosome.txt

# Tests of geometry
#/dnatests/chromosome

# Analysis: save strands in given directory
/analysisDNA/saveStrands false
/analysisDNA/strandDir ./damage_maps/

# Run: initialization
/run/initialize

# Tests of geometry
/dnatests/uniqueid
/dnatests/basepairs

# Run: progress display
/run/printProgress 1

# Source geometry
/gps/pos/type Surface
/gps/pos/shape Ellipsoid
/gps/pos/centre 0 0 0 nm
/gps/pos/halfx 900 nm
/gps/pos/halfy 400 nm
/gps/pos/halfz 400 nm
/gps/ang/type cos

# Source particle and energy
/gps/particle e-
/gps/energy 9.999 keV

# Beam on
/run/beamOn 500
