### Human cell default geometry

#
# See more details on moleculardna specific UI commands:
# - https://geant4-dna.github.io/molecular-docs/docs/overview/configuration
# - https://geant4-dna.github.io/molecular-docs/docs/overview/macro-anatomy
# - the README file
# - the messenger classes of the moleculardna example
#

# Physics: choice of thermalization model
/process/dna/e-SolvationSubType Meesungnoen2002
#/process/dna/e-SolvationSubType Ritchie1994
#/process/dna/e-SolvationSubType Terrisol1990

# Verbosity: settings
/run/verbose 1
/control/verbose 1

# Chemistry: selection of IRT_syn
/process/chem/TimeStepModel IRT_syn

# Chemistry: verbosity
/scheduler/verbose 0

# Chemistry: end time of chemistry stage
/scheduler/endTime 5.0 ns

# Chemistry: set maximum allowed zero time steps
/scheduler/maxNullTimeSteps 10000000

# Geometry: size of World volume
/world/worldSize 50 um

# Geometry: shape of the cell
/cell/radiusSize 14 2.5 14 um

# Geometry: creation
# See https://geant4-dna.github.io/molecular-docs/docs/examples/bacterial-cell
#  - Side length for each placement
/dnageom/placementSize 75 75 75 nm
#  - Scaling of XYZ in fractal definition file
/dnageom/fractalScaling 75 75 75 nm
#  - Path to file that defines placement locations
/dnageom/definitionFile geometries/cube-centred-X-8.txt
#  - Set placement volumes
/dnageom/placementVolume turn geometries/turned_solenoid_750_withHistone.txt
/dnageom/placementVolume turntwist geometries/turned_twisted_solenoid_750_withHistone.txt true
/dnageom/placementVolume straight geometries/straight_solenoid_750_withHistone.txt

# Geometry: distance from base pairs at which radicals are killed
/dnageom/radicalKillDistance 9 nm

# Geometry: deposited energy accumulation range limit to start recording SBs from direct effects
/dnageom/interactionDirectRange 2.0 angstrom

# Damage: model settings
/dnadamage/directDamageLower 5 eV
/dnadamage/directDamageUpper 37.5 eV

/dnadamage/indirectOHBaseChance 1.0
/dnadamage/indirectOHStrandChance 0.405
/dnadamage/inductionOHChance 0.0

/dnadamage/indirectHBaseChance 1.0
/dnadamage/indirectHStrandChance 0.0
/dnadamage/inductionHChance 0.0

/dnadamage/indirectEaqBaseChance 1.0
/dnadamage/indirectEaqStrandChance 0.0
/dnadamage/inductionEaqChance 0.0

# Analysis: add ellipsoid chromosomal region of interest, with the name "cell"
/chromosome/add cell ellipse 7100 2500 7100 0 0 0 nm 0 0 0

# Run: initialization
/run/initialize

# Run: print progress
/run/printProgress 10

# Source geometry
/gps/pos/type Plane
/gps/pos/shape Circle
/gps/pos/centre 0 3000 0 nm
/gps/pos/rot1 0 0 1
/gps/pos/rot2 1 0 0
/gps/pos/radius 7100 nm
/gps/direction 0 -1 0

# Source particle
/gps/particle e-

# Analysis: set ROOT output file name
#/analysisDNA/fileName 50MeV

# Source energy
/gps/energy 0.662 MeV

# Beam on
/run/beamOn 2
