// This code implementation is the intellectual property of
// the RD44 GEANT4 collaboration.
//
// By copying, distributing or modifying the Program (or any work
// based on the Program) you indicate your acceptance of this statement,
// and all its terms.
//
// $Id: _ctskdoc.h,v 1.1 1999-01-07 16:05:11 gunter Exp $
// GEANT4 tag $Name: not supported by cvs2svn $
//
/* 
	This is version 4.5 of XVT-Architect.
	This file was automatically generated by XVT-Architect,
	Do not modify its contents.
*/

#ifndef _ctskdoc_factory_h
#define _ctskdoc_factory_h

#include "facdec.h"


// Factory IDs:

#ifndef CTaskDoc1003
#define CTaskDoc1003 1003
#endif 

// Object Data Members:

	
class CTaskDoc1003Data : public CDataMembers
{
		PWRClassInfo
		virtual void Initialize(PAFactory* theFactory);

	public:

		CTaskWin* itsCTaskWin1004;
};


#endif

