// This code implementation is the intellectual property of
// the RD44 GEANT4 collaboration.
//
// By copying, distributing or modifying the Program (or any work
// based on the Program) you indicate your acceptance of this statement,
// and all its terms.
//
// $Id: _g4xvtdc.h,v 2.1 1998/07/12 02:39:09 urbi Exp $
// GEANT4 tag $Name: geant4-00 $
//
/* 
	This is version 4.5 of XVT-Architect.
	This file was automatically generated by XVT-Architect,
	Do not modify its contents.
*/

#ifndef _g4xvtdc_factory_h
#define _g4xvtdc_factory_h

#include "facdec.h"


// Factory IDs:

#ifndef G4Doc
#define G4Doc 1009
#endif 

// Object Data Members:

	
class G4DocData : public CDataMembers
{
		PWRClassInfo
		virtual void Initialize(PAFactory* theFactory);

	public:

		G4XvtWin* itsG4Win;
};


#endif

