// This code implementation is the intellectual property of
// the GEANT4 collaboration.
//
// By copying, distributing or modifying the Program (or any work
// based on the Program) you indicate your acceptance of this statement,
// and all its terms.
//
// $Id: _g4xvtwn.h,v 1.2 1999-12-15 14:48:47 gunter Exp $
// GEANT4 tag $Name: not supported by cvs2svn $
//
/* 
	This is version 4.5 of XVT-Architect.
	This file was automatically generated by XVT-Architect,
	Do not modify its contents.
*/

#ifndef _g4xvtwn_factory_h
#define _g4xvtwn_factory_h

#include "facdec.h"


// Factory IDs:

#ifndef G4Win
#define G4Win 1010
#endif 
#ifndef progStatus
#define progStatus 1017
#endif 
#ifndef LogBar
#define LogBar 1062
#endif 
#ifndef CMenuButton1063
#define CMenuButton1063 1063
#endif 
#ifndef CMenuButton1064
#define CMenuButton1064 1064
#endif 
#ifndef CMenuButton1065
#define CMenuButton1065 1065
#endif 
#ifndef CMenuButton1076
#define CMenuButton1076 1076
#endif 
#ifndef CMenuButton1077
#define CMenuButton1077 1077
#endif 
#ifndef CMenuButton1078
#define CMenuButton1078 1078
#endif 
#ifndef CMenuButton1079
#define CMenuButton1079 1079
#endif 
#ifndef CMenuButton1080
#define CMenuButton1080 1080
#endif 
#ifndef getComButton
#define getComButton 1083
#endif 
#ifndef commandBox
#define commandBox 1087
#endif 
#ifndef execButton
#define execButton 1088
#endif 
#ifndef textExecButton
#define textExecButton 1096
#endif 
#ifndef helpButton
#define helpButton 1097
#endif 
#ifndef mainTextArea
#define mainTextArea 1068
#endif 
#ifndef CommandLog
#define CommandLog 1073
#endif 
#ifndef DropArea
#define DropArea 1093
#endif 

// Object Data Members:

	
class G4WinData : public CDataMembers
{
		PWRClassInfo
		virtual void Initialize(PAFactory* theFactory);

	public:

		CStatusBar* itsprogStatus;
		CToolBar* itsLogBar;
		CMenuButton* itsCMenuButton1063;
		CMenuButton* itsCMenuButton1064;
		CMenuButton* itsCMenuButton1065;
		CMenuButton* itsCMenuButton1076;
		CMenuButton* itsCMenuButton1077;
		CMenuButton* itsCMenuButton1078;
		CMenuButton* itsCMenuButton1079;
		CMenuButton* itsCMenuButton1080;
		CMenuButton* itsgetComButton;
		NLineText* itscommandBox;
		CMenuButton* itsexecButton;
		CMenuButton* itstextExecButton;
		CMenuButton* itshelpButton;
		NScrollText* itsmainTextArea;
		NScrollText* itsCommandLog;
		CScroller* itsDropArea;
};

	
class LogBarData : public CDataMembers
{
		PWRClassInfo
		virtual void Initialize(PAFactory* theFactory);

	public:

		CMenuButton* itsCMenuButton1063;
		CMenuButton* itsCMenuButton1064;
		CMenuButton* itsCMenuButton1065;
		CMenuButton* itsCMenuButton1076;
		CMenuButton* itsCMenuButton1077;
		CMenuButton* itsCMenuButton1078;
		CMenuButton* itsCMenuButton1079;
		CMenuButton* itsCMenuButton1080;
		CMenuButton* itsgetComButton;
		NLineText* itscommandBox;
		CMenuButton* itsexecButton;
		CMenuButton* itstextExecButton;
		CMenuButton* itshelpButton;
};


#endif

