//
// ********************************************************************
// * DISCLAIMER                                                       *
// *                                                                  *
// * The following disclaimer summarizes all the specific disclaimers *
// * of contributors to this software. The specific disclaimers,which *
// * govern, are listed with their locations in:                      *
// *   http://cern.ch/geant4/license                                  *
// *                                                                  *
// * Neither the authors of this software system, nor their employing *
// * institutes,nor the agencies providing financial support for this *
// * work  make  any representation or  warranty, express or implied, *
// * regarding  this  software system or assume any liability for its *
// * use.                                                             *
// *                                                                  *
// * This  code  implementation is the  intellectual property  of the *
// * GEANT4 collaboration.                                            *
// * By copying,  distributing  or modifying the Program (or any work *
// * based  on  the Program)  you indicate  your  acceptance of  this *
// * statement, and all its terms.                                    *
// ********************************************************************
//
//
// $Id: classes.h,v 1.4 2001-07-11 09:56:52 gunter Exp $
// GEANT4 tag $Name: not supported by cvs2svn $
//
/* 
	This is version 4.5 of XVT-Architect.
	This file was automatically generated by XVT-Architect,
	Do not modify its contents.
*/

// Include all class definitions:
#include "XVTPwr.h"
#include CEnvironment_i
#include CButton_i
#include CText_i
#include CPicture_i
#include CMenuButton_i
#include CScroller_i
#include CToolBar_i
#include CWindow_i
#include NTextEdit_i
#include NScrollText_i
#include CStatusBar_i
#include NLineText_i
#include "g4rw/regexp.h"

#include G4XvtGUI_i
#include CTaskDoc_i
#include CTaskWin_i
#include G4XvtDoc_i
#include G4XvtWin_i
