// This code implementation is the intellectual property of
// the GEANT4 collaboration.
//
// By copying, distributing or modifying the Program (or any work
// based on the Program) you indicate your acceptance of this statement,
// and all its terms.
//
// $Id: classes.cxx,v 1.2 1999-12-15 14:48:47 gunter Exp $
// GEANT4 tag $Name: not supported by cvs2svn $
//
/* 
	This is version 4.5 of XVT-Architect.
	This file was automatically generated by XVT-Architect,
	Do not modify its contents.
*/

#include "XVTPwr.h"
#include "AppDef.h"
#include PAFactory_i

#define _PA_REF(x) x=x

#include G4XvtGUI_f
	
PWRRegisterClass1( G4XvtGUI1002Data, G4XvtGUI1002, "G4XvtGUI1002Data", CDataMembers)
	
void G4XvtGUI1002Data::Initialize(PAFactory* theFactory)
{
	_PA_REF(theFactory);
		itsCTaskDoc1003 = (CTaskDoc*) theFactory->GetInstance(1003);
		itsG4Doc = (G4XvtDoc*) theFactory->GetInstance(1009);
}

#include CTaskDoc_f
	
PWRRegisterClass1( CTaskDoc1003Data, CTaskDoc1003, "CTaskDoc1003Data", CDataMembers)
	
void CTaskDoc1003Data::Initialize(PAFactory* theFactory)
{
	_PA_REF(theFactory);
		itsCTaskWin1004 = (CTaskWin*) theFactory->GetInstance(1004);
}

#include CTaskWin_f
	
PWRRegisterClass1( CTaskWin1004Data, CTaskWin1004, "CTaskWin1004Data", CDataMembers)
	
void CTaskWin1004Data::Initialize(PAFactory* theFactory)
{
	_PA_REF(theFactory);
}

#include G4XvtDoc_f
	
PWRRegisterClass1( G4DocData, G4Doc, "G4DocData", CDataMembers)
	
void G4DocData::Initialize(PAFactory* theFactory)
{
	_PA_REF(theFactory);
		itsG4Win = (G4XvtWin*) theFactory->GetInstance(1010);
}

#include G4XvtWin_f
	
PWRRegisterClass1( G4WinData, G4Win, "G4WinData", CDataMembers)
	
void G4WinData::Initialize(PAFactory* theFactory)
{
	_PA_REF(theFactory);
		itsprogStatus = (CStatusBar*) theFactory->GetInstance(1017);
		itsLogBar = (CToolBar*) theFactory->GetInstance(1062);
		itsCMenuButton1063 = (CMenuButton*) theFactory->GetInstance(1063);
		itsCMenuButton1064 = (CMenuButton*) theFactory->GetInstance(1064);
		itsCMenuButton1065 = (CMenuButton*) theFactory->GetInstance(1065);
		itsCMenuButton1076 = (CMenuButton*) theFactory->GetInstance(1076);
		itsCMenuButton1077 = (CMenuButton*) theFactory->GetInstance(1077);
		itsCMenuButton1078 = (CMenuButton*) theFactory->GetInstance(1078);
		itsCMenuButton1079 = (CMenuButton*) theFactory->GetInstance(1079);
		itsCMenuButton1080 = (CMenuButton*) theFactory->GetInstance(1080);
		itsgetComButton = (CMenuButton*) theFactory->GetInstance(1083);
		itscommandBox = (NLineText*) theFactory->GetInstance(1087);
		itsexecButton = (CMenuButton*) theFactory->GetInstance(1088);
		itstextExecButton = (CMenuButton*) theFactory->GetInstance(1096);
		itshelpButton = (CMenuButton*) theFactory->GetInstance(1097);
		itsmainTextArea = (NScrollText*) theFactory->GetInstance(1068);
		itsCommandLog = (NScrollText*) theFactory->GetInstance(1073);
		itsDropArea = (CScroller*) theFactory->GetInstance(1093);
}

	
PWRRegisterClass1( LogBarData, LogBar, "LogBarData", CDataMembers)
	
void LogBarData::Initialize(PAFactory* theFactory)
{
	_PA_REF(theFactory);
		itsCMenuButton1063 = (CMenuButton*) theFactory->GetInstance(1063);
		itsCMenuButton1064 = (CMenuButton*) theFactory->GetInstance(1064);
		itsCMenuButton1065 = (CMenuButton*) theFactory->GetInstance(1065);
		itsCMenuButton1076 = (CMenuButton*) theFactory->GetInstance(1076);
		itsCMenuButton1077 = (CMenuButton*) theFactory->GetInstance(1077);
		itsCMenuButton1078 = (CMenuButton*) theFactory->GetInstance(1078);
		itsCMenuButton1079 = (CMenuButton*) theFactory->GetInstance(1079);
		itsCMenuButton1080 = (CMenuButton*) theFactory->GetInstance(1080);
		itsgetComButton = (CMenuButton*) theFactory->GetInstance(1083);
		itscommandBox = (NLineText*) theFactory->GetInstance(1087);
		itsexecButton = (CMenuButton*) theFactory->GetInstance(1088);
		itstextExecButton = (CMenuButton*) theFactory->GetInstance(1096);
		itshelpButton = (CMenuButton*) theFactory->GetInstance(1097);
}

