// This code implementation is the intellectual property of
// the GEANT4 collaboration.
//
// By copying, distributing or modifying the Program (or any work
// based on the Program) you indicate your acceptance of this statement,
// and all its terms.
//
// $Id: faccb.h,v 1.2 1999-12-15 14:48:47 gunter Exp $
// GEANT4 tag $Name: not supported by cvs2svn $
//
/* 
	This is version 4.5 of XVT-Architect.
	This file was automatically generated by XVT-Architect,
	Do not modify its contents.
*/

// Static Factory Initializer

#if (XVT_CC == XVT_CC_SYMCPLUS || defined XVT_PREDEF_PLACEMENT_NEW)
#include "new.h"
#else
inline void* operator new(size_t, void* m) { return m; }
#endif

class CGUIFactoryInit
{
	public:
		CGUIFactoryInit() {
			if (!CGUIFactory::itIsInitialized)
				new (&GUIFactory) CGUIFactory;
		}
};

static CGUIFactoryInit _FACTORYInit;

