// This code implementation is the intellectual property of
// the RD44 GEANT4 collaboration.
//
// By copying, distributing or modifying the Program (or any work
// based on the Program) you indicate your acceptance of this statement,
// and all its terms.
//
// $Id: faccmd.h,v 1.1 1999-01-07 16:05:14 gunter Exp $
// GEANT4 tag $Name: not supported by cvs2svn $
//
/* 
	This is version 4.5 of XVT-Architect.
	This file was automatically generated by XVT-Architect,
	Do not modify its contents.
*/

#ifndef GUI_FactoryCommands_h
#define GUI_FactoryCommands_h

// Command ID Bases:
/*
Default base
*/
#ifndef PA_NULLBase
#define PA_NULLBase 0
#endif 
#ifndef G4Control_Commands
#define G4Control_Commands 1000
#endif 

// Command IDs:
#ifndef NULLcCMenuButton1095md
#define NULLcCMenuButton1095md (PA_NULLBase + 20)
#endif 
#ifndef COM_INcmd
#define COM_INcmd (G4Control_Commands + 34)
#endif 
#ifndef COM_OUTcmd
#define COM_OUTcmd (G4Control_Commands + 35)
#endif 
#ifndef STOP_INcmd
#define STOP_INcmd (G4Control_Commands + 5)
#endif 
#ifndef START_OUTcmd
#define START_OUTcmd (G4Control_Commands + 3)
#endif 
#ifndef RESUMEcmd
#define RESUMEcmd (G4Control_Commands + 10)
#endif 
#ifndef RESUME_INcmd
#define RESUME_INcmd (G4Control_Commands + 11)
#endif 
#ifndef M_Pause_Geant
#define M_Pause_Geant (PA_NULLBase + 13)
#endif 
#ifndef QUIT_INcmd
#define QUIT_INcmd (G4Control_Commands + 14)
#endif 
#ifndef M_Retrieve_Commands
#define M_Retrieve_Commands (PA_NULLBase + 7)
#endif 
#ifndef M_Palettes
#define M_Palettes (PA_NULLBase + 16)
#endif 
#ifndef M_Commands
#define M_Commands (PA_NULLBase + 17)
#endif 
#ifndef COMcmd
#define COMcmd (G4Control_Commands + 31)
#endif 
#ifndef PAUSE_OUTcmd
#define PAUSE_OUTcmd (G4Control_Commands + 9)
#endif 
#ifndef PAUSEcmd
#define PAUSEcmd (G4Control_Commands + 7)
#endif 
#ifndef HELP_OUTcmd
#define HELP_OUTcmd (G4Control_Commands + 23)
#endif 
#ifndef PRINT_OUTcmd
#define PRINT_OUTcmd (G4Control_Commands + 21)
#endif 
#ifndef SAVE_AS_INcmd
#define SAVE_AS_INcmd (G4Control_Commands + 18)
#endif 
#ifndef SAVE_AS_OUTcmd
#define SAVE_AS_OUTcmd (G4Control_Commands + 19)
#endif 
#ifndef OutputWinMB
#define OutputWinMB (PA_NULLBase + 3)
#endif 
#ifndef SAVE_LOG_INcmd
#define SAVE_LOG_INcmd (G4Control_Commands + 16)
#endif 
#ifndef M_Start_Geant
#define M_Start_Geant (PA_NULLBase + 11)
#endif 
#ifndef GET_COMMANDS_OUTcmd
#define GET_COMMANDS_OUTcmd (G4Control_Commands + 30)
#endif 
#ifndef RESUME_OUTcmd
#define RESUME_OUTcmd (G4Control_Commands + 12)
#endif 
#ifndef M_Setup
#define M_Setup (PA_NULLBase + 6)
#endif 
#ifndef EXECUTEcmd
#define EXECUTEcmd (G4Control_Commands + 26)
#endif 
#ifndef HELP_MENU_1015
#define HELP_MENU_1015 (PA_NULLBase + 18)
#endif 
#ifndef HELP_MENU_1044
#define HELP_MENU_1044 (PA_NULLBase + 5)
#endif 
#ifndef STOP_OUTcmd
#define STOP_OUTcmd (G4Control_Commands + 6)
#endif 
#ifndef START_INcmd
#define START_INcmd (G4Control_Commands + 2)
#endif 
#ifndef GET_COMMANDScmd
#define GET_COMMANDScmd (G4Control_Commands + 28)
#endif 
#ifndef FILE_MENU_1015
#define FILE_MENU_1015 (PA_NULLBase + 2)
#endif 
#ifndef FILE_MENU_1044
#define FILE_MENU_1044 (PA_NULLBase + 4)
#endif 
#ifndef G4WinMB
#define G4WinMB (PA_NULLBase + 1)
#endif 
#ifndef QUIT_OUTcmd
#define QUIT_OUTcmd (G4Control_Commands + 15)
#endif 
#ifndef M_Stop_Geant
#define M_Stop_Geant (PA_NULLBase + 12)
#endif 
#ifndef M_Quit_Geant
#define M_Quit_Geant (PA_NULLBase + 15)
#endif 
#ifndef PAUSE_INcmd
#define PAUSE_INcmd (G4Control_Commands + 8)
#endif 
#ifndef HELPcmd
#define HELPcmd (G4Control_Commands + 27)
#endif 
#ifndef STARTcmd
#define STARTcmd (G4Control_Commands + 1)
#endif 
#ifndef STOPcmd
#define STOPcmd (G4Control_Commands + 4)
#endif 
#ifndef QUITcmd
#define QUITcmd (G4Control_Commands + 13)
#endif 
#ifndef HELP_INcmd
#define HELP_INcmd (G4Control_Commands + 22)
#endif 
#ifndef PRINT_INcmd
#define PRINT_INcmd (G4Control_Commands + 20)
#endif 
#ifndef SAVE_LOG_OUTcmd
#define SAVE_LOG_OUTcmd (G4Control_Commands + 17)
#endif 
#ifndef EXECUTE_INcmd
#define EXECUTE_INcmd (G4Control_Commands + 24)
#endif 
#ifndef EXECUTE_OUTcmd
#define EXECUTE_OUTcmd (G4Control_Commands + 25)
#endif 
#ifndef M_Control
#define M_Control (PA_NULLBase + 10)
#endif 
#ifndef GET_COMMANDS_INcmd
#define GET_COMMANDS_INcmd (G4Control_Commands + 29)
#endif 
#ifndef M_Enter_Parameters_for_selected_command
#define M_Enter_Parameters_for_selected_command (PA_NULLBase + 8)
#endif 
#ifndef M_On_command
#define M_On_command (PA_NULLBase + 19)
#endif 
#ifndef M_Resume_Geant
#define M_Resume_Geant (PA_NULLBase + 14)
#endif 
#ifndef M_Execute_Selected_Command
#define M_Execute_Selected_Command (PA_NULLBase + 9)
#endif 

#ifndef PAFACTORY_BASE_NAME
#define PAFACTORY_BASE_NAMEGUI
#endif
#ifndef PAFACTORY_QBASE_NAME
#define PAFACTORY_QBASE_NAME "GUI"
#endif

// Layer ID Bases
#ifndef DEFAULT_BASE
#define DEFAULT_BASE 0
#endif

// Accelerator Tags:

#endif 
