//
// ********************************************************************
// * DISCLAIMER                                                       *
// *                                                                  *
// * The following disclaimer summarizes all the specific disclaimers *
// * of contributors to this software. The specific disclaimers,which *
// * govern, are listed with their locations in:                      *
// *   http://cern.ch/geant4/license                                  *
// *                                                                  *
// * Neither the authors of this software system, nor their employing *
// * institutes,nor the agencies providing financial support for this *
// * work  make  any representation or  warranty, express or implied, *
// * regarding  this  software system or assume any liability for its *
// * use.                                                             *
// *                                                                  *
// * This  code  implementation is the  intellectual property  of the *
// * GEANT4 collaboration.                                            *
// * By copying,  distributing  or modifying the Program (or any work *
// * based  on  the Program)  you indicate  your  acceptance of  this *
// * statement, and all its terms.                                    *
// ********************************************************************
//
//
// $Id: facdec.h,v 1.3 2001-07-11 09:56:53 gunter Exp $
// GEANT4 tag $Name: not supported by cvs2svn $
//
/* 
	This is version 4.5 of XVT-Architect.
	This file was automatically generated by XVT-Architect,
	Do not modify its contents.
*/

#ifndef GUI_FacDec_h
#define GUI_FacDec_h

// Forward Declarations

#define CUserView PWR_CRectangle
#define CUserSubview PWR_CRectangle
#define CUserView_i CRectangle_i
#define CUserSubview_i CRectangle_i

class CMenuButton;
class CScroller;
class CMenuBar;
class CToolBar;
class G4XvtGUI;
class CTaskDoc;
class CTaskWin;
class NScrollText;
class G4XvtDoc;
class G4XvtWin;
class CStatusBar;
class NLineText;

#endif
