// This code implementation is the intellectual property of
// the RD44 GEANT4 collaboration.
//
// By copying, distributing or modifying the Program (or any work
// based on the Program) you indicate your acceptance of this statement,
// and all its terms.
//
// $Id: facdec.h,v 1.1 1999-01-07 16:05:14 gunter Exp $
// GEANT4 tag $Name: not supported by cvs2svn $
//
/* 
	This is version 4.5 of XVT-Architect.
	This file was automatically generated by XVT-Architect,
	Do not modify its contents.
*/

#ifndef GUI_FacDec_h
#define GUI_FacDec_h

// Forward Declarations

#define CUserView PWR_CRectangle
#define CUserSubview PWR_CRectangle
#define CUserView_i CRectangle_i
#define CUserSubview_i CRectangle_i

class CMenuButton;
class CScroller;
class CMenuBar;
class CToolBar;
class G4XvtGUI;
class CTaskDoc;
class CTaskWin;
class NScrollText;
class G4XvtDoc;
class G4XvtWin;
class CStatusBar;
class NLineText;

#endif
