// This code implementation is the intellectual property of
// the GEANT4 collaboration.
//
// By copying, distributing or modifying the Program (or any work
// based on the Program) you indicate your acceptance of this statement,
// and all its terms.
//
// $Id: facdef.h,v 1.2 1999-12-15 14:48:47 gunter Exp $
// GEANT4 tag $Name: not supported by cvs2svn $
//

/* 
	This is version 4.5 of XVT-Architect.
	This file was automatically generated by XVT-Architect,
	Do not modify its contents.
*/

#ifndef GUI_FacDef_h
#define GUI_FacDef_h

// Factory class includes:
#define G4XvtGUI_f "_g4xvtgu.h"
#define CTaskDoc_f "_ctskdoc.h"
#define CTaskWin_f "_ctskwin.h"
#define G4XvtDoc_f "_g4xvtdc.h"
#define G4XvtWin_f "_g4xvtwn.h"
#define FactoryCommands_i "faccmd.h"
#define FactoryStrings_i  "facstr.h"
#define FactoryDefines_i  "defines.h"
#define CGUIFactory_i "factory.h"
#ifndef PA_FACTORY_INSTANCE
#define PA_FACTORY_INSTANCE GUIFactory
#endif

#ifndef DSP_RELEASE
#define DSP_RELEASE 450
#endif


#endif 
