// This code implementation is the intellectual property of
// the RD44 GEANT4 collaboration.
//
// By copying, distributing or modifying the Program (or any work
// based on the Program) you indicate your acceptance of this statement,
// and all its terms.
//
// $Id: facstr.h,v 2.1 1998/07/12 02:39:15 urbi Exp $
// GEANT4 tag $Name: geant4-00 $
//
/* 
	This is version 4.5 of XVT-Architect.
	This file was automatically generated by XVT-Architect,
	Do not modify its contents.
*/

#ifndef GUI_FactoryStrings_h
#define GUI_FactoryStrings_h

// String IDs:

#ifndef GUIStringIDBase
#define GUIStringIDBase 0
#endif


// Defines for DEFAULT layer
#define STRING5 ""
#define STRING3 ""
#define STRING6 ""
#define STRING7 ""
#define STRING8 ""
#define STRING9 ""
#define STRING2 ""
#define STRING4 ""
#define STRING1 (1016+GUIStringIDBase)


#endif
