//
// ********************************************************************
// * DISCLAIMER                                                       *
// *                                                                  *
// * The following disclaimer summarizes all the specific disclaimers *
// * of contributors to this software. The specific disclaimers,which *
// * govern, are listed with their locations in:                      *
// *   http://cern.ch/geant4/license                                  *
// *                                                                  *
// * Neither the authors of this software system, nor their employing *
// * institutes,nor the agencies providing financial support for this *
// * work  make  any representation or  warranty, express or implied, *
// * regarding  this  software system or assume any liability for its *
// * use.                                                             *
// *                                                                  *
// * This  code  implementation is the  intellectual property  of the *
// * GEANT4 collaboration.                                            *
// * By copying,  distributing  or modifying the Program (or any work *
// * based  on  the Program)  you indicate  your  acceptance of  this *
// * statement, and all its terms.                                    *
// ********************************************************************
//
//
// $Id: facstr.h,v 1.3 2001-07-11 09:56:53 gunter Exp $
// GEANT4 tag $Name: not supported by cvs2svn $
//
/* 
	This is version 4.5 of XVT-Architect.
	This file was automatically generated by XVT-Architect,
	Do not modify its contents.
*/

#ifndef GUI_FactoryStrings_h
#define GUI_FactoryStrings_h

// String IDs:

#ifndef GUIStringIDBase
#define GUIStringIDBase 0
#endif


// Defines for DEFAULT layer
#define STRING5 ""
#define STRING3 ""
#define STRING6 ""
#define STRING7 ""
#define STRING8 ""
#define STRING9 ""
#define STRING2 ""
#define STRING4 ""
#define STRING1 (1016+GUIStringIDBase)


#endif
