// This code implementation is the intellectual property of
// the RD44 GEANT4 collaboration.
//
// By copying, distributing or modifying the Program (or any work
// based on the Program) you indicate your acceptance of this statement,
// and all its terms.
//
// $Id: factory.h,v 1.1 1999-01-07 16:05:15 gunter Exp $
// GEANT4 tag $Name: not supported by cvs2svn $
//
/* 
	This is version 4.5 of XVT-Architect.
	This file was automatically generated by XVT-Architect,
	Do not modify its contents.
*/

#ifndef GUIFactory_h
#define GUIFactory_h

#include "XVTPwr.h"
#include "AppDef.h"
#include PAFactory_i

// Project factory class definition:

class CGUIFactory : public PAFactory
{
	public:

		enum LayerID { 
			DEFAULT=0
		};

		CGUIFactory(void);

		CGUIFactory& operator[](LayerID theLayer);
		void SetDefaultLayer(LayerID theLayer);
		LayerID GetDefaultLayer(void) const;
		long GetLayerBase(LayerID theLayer);

	protected:

		friend class CGUIFactoryInit;

		static int itIsInitialized;

};

extern CGUIFactory GUIFactory;
#endif 
