#/vis/sceneHandler/create ATree DefaultHandler
#/vis/ASCIITree/verbose 14
/vis/sceneHandler/create OGLSX DefaultHandler
/vis/viewer/create DefaultHandler DefaultView 600
#/vis/sceneHandler/create RayTracer DefaultHandler
#/vis/viewer/create DefaultHandler DefaultView 1600
/vis/scene/create DefaultScene
/vis/scene/add/volume worldPV
/vis/sceneHandler/attach DefaultScene
#/vis/viewer/set/culling global false
/vis/scene/endOfEventAction accumulate
/vis/viewer/set/viewpointThetaPhi 150 60 deg
