/vis/disable
/control/execute macros/EnvironmentGeometry.mac
/control/execute macros/DetectorsGeometry.mac
/control/execute macros/PackagingGeometry.mac
/control/execute macros/RelativePositioningPackaging.mac

/radmon/detector/CreatePlacement              packaging MIL-STD-105D
/radmon/detector/CreatePlacement              detector01 REM-TOT-500
/radmon/detector/CreatePlacement              detector02 REM-TOT-500
/radmon/detector/CreatePlacement              detector03 LAAS
/radmon/detector/CreatePlacement              detector04 LAAS

/control/execute macros/ApplyRelativePositioning.mac
/radmon/detector/DisableEnvironment
/vis/enable
/radmon/detector/EnableEnvironment
