/radmon/physics/AddPhysicsList PhysicsParticles
/radmon/physics/AddPhysicsList ElectronEEDL
/radmon/physics/AddPhysicsList PositronStandard
/radmon/physics/AddPhysicsList PhotonEPDL
/radmon/physics/AddPhysicsList Nuclear
/radmon/physics/AddPhysicsList MuonStandard
/radmon/physics/AddPhysicsList NeutronBinary
/radmon/physics/AddPhysicsList HadronsBinary
/radmon/physics/AddPhysicsList ICRUIonization
/radmon/physics/AddPhysicsList ProductionCuts
/radmon/physics/SetPhysicsListAttribute ProductionCuts Cuts '0.001 mm'
