/radmon/materials/CreateElement  Hydrogen H  1.  1.01   g/mole
/radmon/materials/CreateElement  Carbon   C  6.  12.01  g/mole
/radmon/materials/CreateElement  Nitrogen N  7.  14.01  g/mole
/radmon/materials/CreateElement  Oxygen   O  8.  16.00  g/mole
/radmon/materials/CreateElement  Aluminum Al 13. 26.98  g/mole
/radmon/materials/CreateElement  Silicon  Si 14. 28.09  g/mole
/radmon/materials/CreateElement  Argon    Ar 18. 39.95  g/mole
/radmon/materials/CreateElement  Iron     Fe 26. 55.85  g/mole
/radmon/materials/CreateElement  Copper   Cu 29  63.55  g/mole
/radmon/materials/CreateElement  Tungsten W  74. 183.84 g/mole
/radmon/materials/CreateElement  Lead     Pb 82. 207.20 g/mole

/radmon/materials/CreateMaterial Aluminum 2.700 g/cm3 1
/radmon/materials/AddComponentByFraction Aluminum Aluminum 1
/radmon/materials/SetMaterialColor Aluminum .7 .7 .7
/radmon/materials/SetMaterialTrasparency Aluminum 1.
/radmon/materials/SetMaterialVisibility Aluminum visible
/radmon/materials/SetMaterialStyle Aluminum solid

/radmon/materials/CreateMaterial Copper 8.960 g/cm3 1
/radmon/materials/AddComponentByFraction Copper Copper 1
/radmon/materials/SetMaterialColor Copper .8 .6 .2
/radmon/materials/SetMaterialTrasparency Copper 1.
/radmon/materials/SetMaterialVisibility Copper visible
/radmon/materials/SetMaterialStyle Copper solid

/radmon/materials/CreateMaterial Water 1.000 g/cm3 2
/radmon/materials/AddComponentByAtoms Water Hydrogen 2
/radmon/materials/AddComponentByAtoms Water Oxygen 1

/radmon/materials/CreateMaterial Quartz 2.200 g/cm3 2
/radmon/materials/AddComponentByAtoms Quartz Silicon 1
/radmon/materials/AddComponentByAtoms Quartz Oxygen 2
/radmon/materials/SetMaterialColor Quartz 0. .6 .1
/radmon/materials/SetMaterialTrasparency Quartz .5
/radmon/materials/SetMaterialVisibility Quartz visible
/radmon/materials/SetMaterialStyle Quartz solid

/radmon/materials/CreateMaterial Air 1.290 mg/cm3 2
/radmon/materials/AddComponentByFraction Air Nitrogen 0.7
/radmon/materials/AddComponentByFraction Air Oxygen 0.3
/radmon/materials/SetMaterialColor Air .3 .9 1.
/radmon/materials/SetMaterialTrasparency Air 1.
/radmon/materials/SetMaterialVisibility Air visible
/radmon/materials/SetMaterialStyle Air wireframe

/radmon/materials/CreateMaterial Ceramics 2.200 g/cm3 2
/radmon/materials/AddComponentByAtoms Ceramics Silicon 1
/radmon/materials/AddComponentByAtoms Ceramics Oxygen 2
/radmon/materials/SetMaterialColor Ceramics 1. .9 .7
/radmon/materials/SetMaterialTrasparency Ceramics .3
#/radmon/materials/SetMaterialTrasparency Ceramics 1.
/radmon/materials/SetMaterialVisibility Ceramics visible
/radmon/materials/SetMaterialStyle Ceramics solid

#/radmon/materials/Dump
