/control/execute macros/DetectorsParameters.mac

/radmon/detector/CreateMultilayer        REM-TOT-500
/radmon/detector/SetMultilayerWidth      REM-TOT-500      {Det-Width}
/radmon/detector/SetMultilayerHeight     REM-TOT-500      {Det-Height}

/radmon/detector/AppendLayerToMultilayer REM-TOT-500  ly1
/radmon/detector/SetLayerType            REM-TOT-500  ly1 FlatVolume
/radmon/detector/SetLayerThickness       REM-TOT-500  ly1 {Det-Layer-Thickness}
/radmon/detector/SetLayerAttribute       REM-TOT-500  ly1 Material {Det-Material}

/radmon/detector/AppendLayerToMultilayer REM-TOT-500  ly2
/radmon/detector/SetLayerType            REM-TOT-500  ly2 FlatVolume
/radmon/detector/SetLayerThickness       REM-TOT-500  ly2 {Det-Pads-Thickness}
/radmon/detector/SetLayerAttribute       REM-TOT-500  ly2 Material {Det-Material}

/radmon/detector/CreateMultilayer        LAAS       
/radmon/detector/SetMultilayerWidth      LAAS             {Det2-Width}
/radmon/detector/SetMultilayerHeight     LAAS             {Det2-Height}

/radmon/detector/AppendLayerToMultilayer LAAS         ly1
/radmon/detector/SetLayerType            LAAS         ly1 FlatVolume
/radmon/detector/SetLayerThickness       LAAS         ly1 {Det2-Layer-Thickness}
/radmon/detector/SetLayerAttribute       LAAS         ly1 Material {Det2-Material}

/radmon/detector/AppendLayerToMultilayer LAAS         ly2
/radmon/detector/SetLayerType            LAAS         ly2 FlatVolume
/radmon/detector/SetLayerThickness       LAAS         ly2 {Det2-Pads-Thickness}
/radmon/detector/SetLayerAttribute       LAAS         ly2 Material {Det2-Material}
