#ifndef G4ASSEMBLYVOLUME_H
#define G4ASSEMBLYVOLUME_H 1

#include "G4Transform3D.hh"
#include "G4AssemblyTriplet.hh"
#include "g4std/vector"

class G4VPhysicalVolume;

/**
 * Class:       G4AssemblyVolume
 * Description: This is a helper class to make the build process of geometry
 *              easier. It allows to combine several volumes together in an
 *              arbitrary way in 3D space and then work with the result as with
 *              single logical volume for placement.
 *              The resulting objects are independent copies of each of the
 *              assembled logical volumes. The placements are not, however,
 *              bound one to each other when placement is done.
 *              They are seen as independent physical volumes in space.
 *              This is the main difference when comapred to the boolean solids
 *              or parametrized physical volumes.
 * 
 * Author:      Radovan Chytracek, John Apostolakis, Gabriele Cosmo
 * Version:     1.0
 * Date:        November 2000
 */
class G4AssemblyVolume {
public:

  G4AssemblyVolume();    
  G4AssemblyVolume( G4LogicalVolume* volume
                   ,G4ThreeVector& translation
                   ,G4RotationMatrix* rotation);
  ~G4AssemblyVolume();

  /**
   * Place the given volume inside the assembly.
   * 
   * The taken approach:
   *
   * - Place it w.r.t. the assembly coordinate system.
   *   This step is aplied to each of the participating volumes.
   *
   * The other possible approaches:
   *
   * - Place w.r.t. the firstly added volume.
   *   When placed the first, the virtual coordinate system becomes
   *   the coordinate system of the first one.
   *   Every next volume being added into the assembly will be placed
   *   w.r.t to the first one.
   *
   * - Place w.r.t the last placed volume.
   *   When placed the first, the virtual coordinate system becomes
   *   the coordinate system of the first one.
   *   Every next volume being added into the assembly will be placed
   *   w.r.t to the previous one.
   */
  void AddPlacedVolume( G4LogicalVolume* pPlacedVolume
                       ,G4ThreeVector& translation
                       ,G4RotationMatrix* rotation
                      );

  /**
    * The same as previous but takes complete 3D transformation in space
    * as its argument
    */
  void AddPlacedVolume( G4LogicalVolume* pPlacedVolume
                       ,G4Transform3D&   transformation
                      );

  /**
   * Creates instance of an assembly volume inside the given mother volume
   */
  void MakeImprint( G4LogicalVolume* pMotherLV
                   ,G4ThreeVector& translationInMother
                   ,G4RotationMatrix* pRotationInMother
                  );

  /**
    * The same as previous but takes complete 3D transformation in space
    * as its argument
    */
  void MakeImprint( G4LogicalVolume* pMotherLV
                   ,G4Transform3D&   transformation
                  );

private:    

  /**
   * Participating volumes represented as a vector of
   * <logical volume, translation, rotation>
   */
  G4std::vector<G4AssemblyTriplet> fTriplets;

  /**
   * We need to keep list of physical volumes created by MakeImprint() method
   * in order to be able cleanup the objects when not needed anymore.
   * This requires the user will keep assembly objects in memory
   * during the whole job or during the time when G4Navigator, log. vol store
   * and phys. vol. store may keep pointers to physical volumes generated by
   * the assembly volume.
   * When an assembly object is about to die it will destroy all its generated
   * physical volumes and rotation matrices as well.!
   * This may affect validity of detector contruction!
   */
  G4std::vector<G4VPhysicalVolume*> fPVStore;
};

#endif //G4ASSEMBLYVOLUME_H

