# ----------------
# Verbose settings
# ----------------
/control/verbose 2
/run/verbose 2
#/tracking/verbose 2

/vis/open HepRepFile

#/BremSplitting/active true
#/BremSplitting/nSplit 20

#/Roulette/active true
#/Roulette/factor 20

/Brem/Verbose

/control/execute {geometry}
/control/execute {scoring}
/control/execute {physics}
/control/execute {cuts}
/control/execute {biasing}

/run/initialize
/vis/drawVolume
/vis/viewer/flush


#/Brem/Geometry/Build
#/Brem/Scoring/Build
#/vis/scene/add/trajectories
#/vis/scene/endOfEventAction accumulate 
/vis/disable
/run/beamOn 1000
