# $Id: vis.mac,v 1.4 2006-11-06 11:58:46 allison Exp $

# Set verbosity
/control/verbose 2
#/vis/verbose confirmations

# Set sleep pause
/control/alias pause 2

# See tree
/vis/ASCIITree/verbose 2
/vis/drawTree worlds
/control/shell sleep {pause}

# Open viewer
/vis/open OGLSX 600x600-0+0
/vis/viewer/set/viewpointThetaPhi 30 30

# Draw material world
/vis/drawVolume
/control/shell sleep {pause}

# Draw parallel world
/vis/drawVolume ParallelScoringWorld
/control/shell sleep {pause}

# Draw specific sub volume from material world
/vis/drawVolume PhantomLayerPhysical 15
/control/shell sleep {pause}

# Draw specific sub volume from parallel world
/vis/drawVolume GhostLayerPhysical 25
/control/shell sleep {pause}

# Draw both together
/vis/drawVolume PhantomLayerPhysical 16
/vis/scene/add/volume GhostLayerPhysical 25
/control/shell sleep {pause}

# Draw all worlds
/vis/drawVolume worlds
/control/shell sleep {pause}

# Reduce verbosity from here on
/vis/verbose warnings

# Make replica container invisible
/vis/geometry/set/visibility phantomLogical ! false
/vis/geometry/set/visibility GhostLogical ! false

# Set specific colur for identification
/vis/geometry/set/colour GhostLayerLogical ! red
/control/shell sleep {pause}

# Restore
/vis/geometry/restore
/control/shell sleep {pause}

# Adjust a few viewer parameters
# Take advantage of transparency redering in OpenGL
/vis/ogl/set/transparency true
/vis/viewer/set/hiddenMarker true

# Force real world to be solid and transparent
/vis/geometry/set/forceSolid phantomLogical -1 true
/vis/geometry/set/colour phantomLogical -1 .1 .1 .1 .1
/control/shell sleep {pause}

# Set up a run
/vis/scene/add/trajectories
/vis/modeling/trajectories/create/drawByCharge
/vis/modeling/trajectories/drawByCharge-0/default/setDrawStepPts true
/vis/modeling/trajectories/drawByCharge-0/default/setStepPtsSize 2
/vis/scene/add/hits
/run/beamOn
/control/shell sleep {pause}

# Now ready to run/beamOn or /control/execute test.mac
# Restore and make clean scene
# /vis/geometry/restore
# /vis/drawVolume worlds
