# $Id: vis.mac,v 1.2 2006-11-03 17:27:27 allison Exp $

# Control versbosity
/control/verbose 2
/vis/verbose confirmations 

# See tree
/vis/ASCIITree/verbose 2
/vis/drawTree worlds

# Draw
/vis/open OGLSX 600x600-0+0
/vis/viewer/set/viewpointThetaPhi 30 30
/vis/drawVolume worlds

# Make material world invisible
/vis/geometry/set/visibility worldLogical -1 false

# Make parallel world invisible
/vis/geometry/restore
/vis/geometry/set/visibility ParallelScoringWorld -1 false

# Now ready to run
#/vis/scene/add/trajectories
#/vis/scene/add/hits
#/run/beamOn
# or execute
#/control/execute test.mac
