//---------------------------------------
//        Macro file for test30
//         examine PostStepDoIt
//        for hadronic physics
//      Created: 13.03.2002 V.Ivanchenko
//---------------------------------------
#verbose
0
#events
100000
//--------Proton_processes
#particle
proton
//--------
#material
Al
#energy(MeV)
256.
#sigmae(MeV)
1.5
#emax(MeV)
280.
#nbinse
70
#nbinsd
28
#elim(MeV)
2.
#nangle
5
#angles
7.5 30. 60. 120. 150.
#dangle
5.
//--------
//#kBound
//0.1
//#HETCEmission
//#GNASHTransition
//#GEMEvaporation
#generator
binary
//LEparametrisation
//binary
//binary_no_pc
//binary
//#paw
//kin.paw
#run
//--------
//#generator
//bertini
//#paw
//ber.paw
//#run
//--------Exit
#exit
