#----------------------------------------------------------------------------
# DEFAULT MACRO FOR THE HADRONICS APPLICATION
# by aatos.heikkinen@cern.ch
# --------------------------------------------------------------------------------  


/control/verbose 1
/tracking/verbose 0
/run/verbose 0
/event/verbose 0

# SETTING FOR THE PARTICULAR HADRONIC MODEL

#/physics/addPhysics proton-precompound
/physics/addPhysics proton-bertini
/physics/addPhysics bertini


/run/initialize

/vis/scene/create
/vis/open OGLIX
/vis/viewer/flush
/tracking/storeTrajectory 1
/vis/scene/endOfEventAction accumulate

/vis/viewer/set/viewpointThetaPhi 10 150 deg
#/vis/viewer/set/viewpointThetaPhi 50 150 deg
#/vis/scene/add/axes
#/vis/scene/add/hits
#/vis/scene/add/scale 1 m x
#/vis/scene/add/scale 1 m y
#/vis/scene/add/scale 1 m z

/vis/viewer/pan 190 75 cm
/vis/viewer/zoom 9



/vis/viewer/update
/vis/scene/transientsAction none
/beam/position/Xposition -50.0 cm
/beam/position/Yposition 0.0 cm
/beam/position/Zposition 0.0 cm

/beam/energy/meanEnergy 500 MeV
/run/beamOn 10











