#----------------------------------------------------------------------------
# PHYSICS LIST:
# 
#  - ELECTROMAGNETIC PHYSICS FOR PROTONS, ELECTRONS, POSITRONS, PHOTONS AND IONS 
# 
#
#-------------------------------------------------------------------------------
/control/verbose 1
/tracking/verbose 0
/run/verbose 0
/event/verbose 0

# SETTING FOR THE PHYSICS MODELS

/physics/addPhysics photon-penelope
/physics/addPhysics electron-penelope
/physics/addPhysics positron-penelope

###################################################
#### Alternative Low Energy models for protons
#### Same Low Energy model for ions
##################################################

### ICRU49 parameterisation
/physics/addPhysics ion-LowE

### ZIEGLER 1977 parameterisation
#/physics/addPhysics ion-LowE-ziegler1977

### ZIEGLER 1985 parameterisation
#/physics/addPhysics ion-LowE-ziegler1985

### ZIEGLER 2000 parameterisation
#/physics/addPhysics ion-LowE-ziegler2000

/run/initialize
/run/beamOn 100

