# === FILE TO BE REMOVED IN G4 11.0 ===
#
# for neutronHP and particleHP
#
unset G4NEUTRONHP_SKIP_MISSING_ISOTOPES 
unset G4NEUTRONHP_DO_NOT_ADJUST_FINAL_STATE
unset G4NEUTRONHP_USE_ONLY_PHOTONEVAPORATION
unset G4NEUTRONHP_NELECT_DOPPLER
unset G4NEUTRONHP_PRODUCE_FISSION_FRAGMENTS

unset G4PHP_DO_NOT_ADJUST_FINAL_STATE
unset G4PHP_NELECT_DOPPLER

#
# for Bertini cascade
#
unset G4CASCADE_USE_PRECOMPOUND

env |grep G4NEUTRONHP
env |grep G4PHP
env |grep G4CASCADE
