# $Id$
#
# Macro file for "Hadr14.cc"
# (can be run in batch, without graphic)
#
/control/verbose 2
/run/verbose 2
#
/testhadr/det/setMat Molybdenum98
/testhadr/det/setSize 100 m 
#
/run/initialize
#
/gun/particle gamma
/gun/energy 10 MeV
#
/analysis/setFileName gamma
/analysis/h1/set 2  100  -1. 30 keV	#recoil ion
/analysis/h1/set 11 100 -10.  1 MeV	#Q
#
/testhadr/event/printModulo 1000
#
/run/beamOn 1000
