#
# Macro file for "Hadr03.cc"
# (can be run in batch, without graphic)
#
# proton 10 MeV; all processes
#
/control/verbose 2
/run/verbose 2
#
/testhadr/det/setMat Molybdenum98 
#
/run/initialize
#
/gun/particle proton
/gun/energy 10 MeV
#
/process/list
/process/inactivate hadElastic
#
/analysis/setFileName inelastic
/analysis/h1/set 2  100  0. 8000 keV	#gamma
/analysis/h1/set 7  100  0.  400 keV	#nuclei
/analysis/h1/set 10 100 -10  +0  MeV	#Q
#
/run/printProgress 1000
#
/run/beamOn 10000
