#
# Macro file for "Hadr03.cc"
#
# NB. for neutronHP, do not forget to activate 
#     G4NEUTRONHP_PRODUCE_FISSION_FRAGMENTS
#
/control/verbose 2
/run/verbose 2
#
/testhadr/det/setIsotopeMat U235 92 235 19.05 g/cm3
/testhadr/det/setSize 10 m
#
/run/initialize
#
/gun/particle neutron
/gun/energy 1 eV
#
/process/list
/process/inactivate hadElastic
###/process/inactivate neutronInelastic
/process/inactivate nCapture
#
/analysis/setFileName nFission
/analysis/h1/set 2  100  0   10 MeV	#gamma
/analysis/h1/set 3  100  0   10 MeV	#neutron
/analysis/h1/set 7  100  0   150 MeV	#nuclei
/analysis/h1/set 10 100  150 250 MeV	#Q
/analysis/h1/set 12 200  1   200 none   #A
#
/run/printProgress 1000
/testhadr/run/printStat false
#
/run/beamOn 10000
