# $Id: GNUmakefile,v 1.2 2008-12-03 07:40:49 kmura Exp $
# $Name: not supported by cvs2svn $
# ===========================================================
#   Makefile for building Geant4Py modules
# ===========================================================
include ../../config/config.gmk

install_dir := $(Q_LIBDIR)/g4py

include $(G4PY_INSTALL)/config/g4py.gmk
include $(G4PY_INSTALL)/config/sys/$(Q_SYSTEM).gmk
include $(G4PY_INSTALL)/config/script-install.gmk

