#
# Macro file for "Activation.cc"
#
/control/verbose 2
/run/verbose 1
#
/testhadr/det/setIsotopeMat Bi209 83 209 9.78 g/cm3
/testhadr/det/setThickness 10 cm
/testhadr/det/setSizeYZ 5 cm
#
/process/em/verbose 0
/process/had/verbose 0
#
/run/initialize
#
# Set a very high time threshold to allow all decays to happen
/process/had/rdm/thresholdForVeryLongDecayTime 1.0e+60 year
#
/process/em/printParameters
#
/gun/particle neutron
/gun/energy 25 meV
/testhadr/gun/beamSize 25 mm
/testhadr/gun/beamTime 3 year
#
/analysis/setFileName Bi209
/analysis/h1/set 4  100  0 6 MeV   #gamma
/analysis/h1/set 14 100  0 4 year  #gamma
/analysis/h1/set 24 100  0 4 year  #(Bi209)
/analysis/h1/set 25 100  0 4 year  #(Bi210)
/analysis/h1/set 26 100  0 4 year  #(Po210)
/analysis/h1/set 27 100  0 4 year  #(alpha)
/analysis/h1/set 28 100  0 4 year  #(Pb206)
#
/run/printProgress 100000
/run/beamOn 1000000
