#
# Macro file for "Activation.cc"
# in interactive mode
#
/control/verbose 1
/run/verbose 1
#
/testhadr/det/setMat G4_Co
/testhadr/det/setThickness 1 cm
/testhadr/det/setSizeYZ 1 cm
#
/run/initialize
#
# Set a very high time threshold to allow all decays to happen
/process/had/rdm/thresholdForVeryLongDecayTime 1.0e+60 year
#
/gun/particle neutron
/gun/energy 25 meV
#
/control/execute vis.mac
#
/tracking/verbose 2
/run/beamOn 1
