# $Id: GNUmakefile,v 1.6 2002-12-09 11:25:10 gcosmo Exp $
# --------------------------------------------------------------
# GNUmakefile for examples module.  Gabriele Cosmo, 06/04/98.
# --------------------------------------------------------------

name := test17
G4TARGET := $(name)
G4EXLIB := true

ifndef G4INSTALL
  G4INSTALL = ../../
endif

.PHONY: all
 
all: lib bin

include $(G4INSTALL)/config/binmake.gmk


