# $Id: run1.mac 69899 2013-05-17 10:05:33Z gcosmo $
#
# Macro file for "exampleN02.cc"
# 
# can be run in batch, without graphic
# or interactively: Idle> /control/execute run1.mac
#
/run/verbose 2
/event/verbose 0
# 
# proton 3 GeV to the direction (0.,0.,1.)  (default kinematic)
# 1 event with detailled printing
#
/tracking/verbose 1
/run/beamOn 1
# 
# muon 300 MeV to the direction (0.,0.,1.)
# 3 events (no printing)
#
/gun/particle mu-
/gun/energy 300 MeV
/tracking/verbose 0
/run/beamOn 3
