# $Id: run1.mac 66241 2012-12-13 18:34:42Z gunter $
#
# Macro file for "exampleN02.cc"
# 
# can be run in batch, without graphic
# or interactively: Idle> /control/execute run1.mac
#
/run/verbose 2
/event/verbose 0
#/tracking/verbose 6
# 
# muon 300 MeV to the direction (0.,0.,1.)
# 3 events (no printing)
#
/gun/particle mu-
/gun/energy 300 MeV
/run/beamOn 100000
#/gun/particle e- 
#/gun/energy 1 GeV
#/run/beamOn 4 
