//---------------------------------------
//        Macro file for test30
//         examine PostStepDoIt
//        for hadronic physics
//      Created: 13.03.2002 V.Ivanchenko
//---------------------------------------
#verbose
1
#rad
#saverand
#events
100
//--------Proton_processes
#particle
proton
//--------
#material
G4_Ta
#momentum(MeV/c)
100000
#pmax(MeV/c)
5500.
#nbins
110
#nmompi
12
#nanglepi
10
#anglespi
0.35 0.55 0.75 0.95 1.15 1.35 1.55 1.75 1.95 2.15
#mompi(MeV/c)
100 150 200 250 300 350 400 450 500 600 700 800
//#random
//ftfbbug.txt
#generator
qgsb
#run
#generator
ftfp
#run
#generator
ftfb
#run
#exit
