# - G4hadronic_deex_evaporation module build definition

# Define the Geant4 Module.
geant4_add_module(G4hadronic_deex_evaporation
  PUBLIC_HEADERS
    G4AlphaEvaporationChannel.hh
    G4AlphaEvaporationProbability.hh
    G4DeuteronEvaporationChannel.hh
    G4DeuteronEvaporationProbability.hh
    G4Evaporation.hh
    G4EvaporationChannel.hh
    G4EvaporationDefaultGEMFactory.hh
    G4EvaporationFactory.hh
    G4EvaporationProbability.hh
    G4He3EvaporationChannel.hh
    G4He3EvaporationProbability.hh
    G4NeutronEvaporationChannel.hh
    G4NeutronEvaporationProbability.hh
    G4ProtonEvaporationChannel.hh
    G4ProtonEvaporationProbability.hh
    G4TritonEvaporationChannel.hh
    G4TritonEvaporationProbability.hh
    G4UnstableFragmentBreakUp.hh
    G4VEvaporation.hh
  SOURCES
    G4AlphaEvaporationChannel.cc
    G4AlphaEvaporationProbability.cc
    G4DeuteronEvaporationChannel.cc
    G4DeuteronEvaporationProbability.cc
    G4Evaporation.cc
    G4EvaporationChannel.cc
    G4EvaporationDefaultGEMFactory.cc
    G4EvaporationFactory.cc
    G4EvaporationProbability.cc
    G4He3EvaporationChannel.cc
    G4He3EvaporationProbability.cc
    G4NeutronEvaporationChannel.cc
    G4NeutronEvaporationProbability.cc
    G4ProtonEvaporationChannel.cc
    G4ProtonEvaporationProbability.cc
    G4TritonEvaporationChannel.cc
    G4TritonEvaporationProbability.cc
    G4UnstableFragmentBreakUp.cc
    G4VEvaporation.cc)

geant4_module_link_libraries(G4hadronic_deex_evaporation
  PUBLIC
    G4globman
    G4hadronic_deex_management
    G4hadronic_deex_util
    G4hadronic_util
  PRIVATE
    G4hadronic_deex_fermi_breakup
    G4hadronic_deex_fission
    G4hadronic_deex_gem_evaporation
    G4hadronic_deex_photon_evaporation
    G4hepgeometry
    G4heprandom
    G4materials
    G4partman)
