# $Id: GNUmakefile,v 1.1 2006/08/08 05:20:57 kmura Exp $
# $Name: geant4-09-02 $
# ===========================================================
#   Makefile for building Geant4Py modules
# ===========================================================
include ../../config/config.gmk

# python module name
MODULE := G4intercoms#

include $(G4PY_INSTALL)/config/g4py.gmk
include $(G4PY_INSTALL)/config/module.gmk
include $(G4PY_INSTALL)/config/install.gmk

