# John Allison 2005
# Not really relevant - but our system testing requires a batch mode macro
#
/run/verbose 2
/event/verbose 0
# 
# proton 3 GeV to the direction (0.,0.,1.)  (default kinematic)
# 1 event with detailled printing
#
/tracking/verbose 1
/run/beamOn 1
# 
# muon 300 MeV to the direction (0.,0.,1.)
# 3 events (no printing)
#
/gun/particle mu-
/gun/energy 300 MeV
/tracking/verbose 0
/run/beamOn 3
