# Example of interactive redefinition
# of the geometry
#
# this macro can be executed at any time
# during an interactive session:
#
# Idle> /control/execute newgeom.mac
# 
#
/N03/det/setNbOfLayers 1
#
/N03/det/setAbsMat Water
/N03/det/setAbsThick 40 cm
#
/N03/det/setGapMat Air
/N03/det/setGapThick  0 cm
#
/N03/det/setSizeYZ   40 cm
#
/N03/det/setField 3 tesla
#
/N03/det/update
#
/vis/viewer/zoom 1.3
