# $Id: run2.mac,v 1.3 1999-11-15 11:10:26 maire Exp $
#
# Macro file of "exampleN03.cc"
#
# (in iteractive it must be executed after initialization)
# (otherwise type: /control/execute prerunN03.mac)
# (graphic needed: OpenGL or Mesa) 
#
# 
# electron 30 MeV to the direction (1.,0.,0.)
# 1 event
#
/run/beamOn 1
#
# shoot randomly 20 events
#
/event/printModulo 5
/gun/random on
/run/beamOn 20
#
# activate/inactivate physic processes
#
/process/list
/process/inactivate eBrem
#
/run/beamOn 20
#

