//
// ********************************************************************
// * DISCLAIMER                                                       *
// *                                                                  *
// * The following disclaimer summarizes all the specific disclaimers *
// * of contributors to this software. The specific disclaimers,which *
// * govern, are listed with their locations in:                      *
// *   http://cern.ch/geant4/license                                  *
// *                                                                  *
// * Neither the authors of this software system, nor their employing *
// * institutes,nor the agencies providing financial support for this *
// * work  make  any representation or  warranty, express or implied, *
// * regarding  this  software system or assume any liability for its *
// * use.                                                             *
// *                                                                  *
// * This  code  implementation is the  intellectual property  of the *
// * GEANT4 collaboration.                                            *
// * By copying,  distributing  or modifying the Program (or any work *
// * based  on  the Program)  you indicate  your  acceptance of  this *
// * statement, and all its terms.                                    *
// ********************************************************************
//

// Geometry Header File 
//   MomoN02MyDetector.hh generated by Geant4 Geometry Editor at Thu Mar 14 10:39:13 JST 2002  


#ifndef MomoN02MyDetector_h
#define  MomoN02MyDetector_h  1

class G4VPhysicalVolume;
#include "G4VUserDetectorConstruction.hh"
class  MomoN02MyDetector:  public G4VUserDetectorConstruction
   {      public:
      MomoN02MyDetector();
     ~MomoN02MyDetector();

      public:
      G4VPhysicalVolume* Construct();
  };
#endif

