//
// ********************************************************************
// * DISCLAIMER                                                       *
// *                                                                  *
// * The following disclaimer summarizes all the specific disclaimers *
// * of contributors to this software. The specific disclaimers,which *
// * govern, are listed with their locations in:                      *
// *   http://cern.ch/geant4/license                                  *
// *                                                                  *
// * Neither the authors of this software system, nor their employing *
// * institutes,nor the agencies providing financial support for this *
// * work  make  any representation or  warranty, express or implied, *
// * regarding  this  software system or assume any liability for its *
// * use.                                                             *
// *                                                                  *
// * This  code  implementation is the  intellectual property  of the *
// * GEANT4 collaboration.                                            *
// * By copying,  distributing  or modifying the Program (or any work *
// * based  on  the Program)  you indicate  your  acceptance of  this *
// * statement, and all its terms.                                    *
// ********************************************************************
//

// Physics List Header File 
//   MomoN02PhysicsList.hh generated by Geant4 Physics Editor at Thu Mar 14 10:39:12 JST 2002  


 #ifndef  MomoN02PhysicsList_h
#define  MomoN02PhysicsList_h  1

#include "G4VUserPhysicsList.hh"
class  MomoN02PhysicsList:  public G4VUserPhysicsList
   {      public:
      MomoN02PhysicsList();
      virtual ~MomoN02PhysicsList();

  protected:
    virtual void ConstructParticle();
    virtual void ConstructProcess();
    virtual void SetCuts();
  protected:
    virtual void ConstructBosons();
    virtual void ConstructLeptons();
    virtual void ConstructMesons();
    virtual void ConstructBaryons();
  protected:
    virtual void ConstructGeneral();
    virtual void ConstructEM();
    virtual void ConstructAllShortLiveds();
  };
#endif

