//
// ********************************************************************
// * License and Disclaimer                                           *
// *                                                                  *
// * The  Geant4 software  is  copyright of the Copyright Holders  of *
// * the Geant4 Collaboration.  It is provided  under  the terms  and *
// * conditions of the Geant4 Software License,  included in the file *
// * LICENSE and available at  http://cern.ch/geant4/license .  These *
// * include a list of copyright holders.                             *
// *                                                                  *
// * Neither the authors of this software system, nor their employing *
// * institutes,nor the agencies providing financial support for this *
// * work  make  any representation or  warranty, express or implied, *
// * regarding  this  software system or assume any liability for its *
// * use.  Please see the license in the file  LICENSE  and URL above *
// * for the full disclaimer and the limitation of liability.         *
// *                                                                  *
// * This  code  implementation is the result of  the  scientific and *
// * technical work of the GEANT4 collaboration.                      *
// * By using,  copying,  modifying or  distributing the software (or *
// * any work based  on the software)  you  agree  to acknowledge its *
// * use  in  resulting  scientific  publications,  and indicate your *
// * acceptance of all terms of the Geant4 Software license.          *
// ********************************************************************
//

// Physics List Header File 
//   MomoN02PhysicsList.hh generated by Geant4 Physics Editor at Thu Mar 14 10:39:12 JST 2002  


 #ifndef  MomoN02PhysicsList_h
#define  MomoN02PhysicsList_h  1

#include "G4VUserPhysicsList.hh"
class  MomoN02PhysicsList:  public G4VUserPhysicsList
   {      public:
      MomoN02PhysicsList();
      virtual ~MomoN02PhysicsList();

  protected:
    virtual void ConstructParticle();
    virtual void ConstructProcess();
    virtual void SetCuts();
  protected:
    virtual void ConstructBosons();
    virtual void ConstructLeptons();
    virtual void ConstructMesons();
    virtual void ConstructBaryons();
  protected:
    virtual void ConstructGeneral();
    virtual void ConstructEM();
    virtual void ConstructAllShortLiveds();
  };
#endif

