/control/verbose 1
/tracking/verbose 0
/run/verbose 0
/event/verbose 0
/physics/addPhysics photon-standard
/physics/addPhysics electron-standard
/physics/addPhysics positron-standard
/physics/cutE 0.5 micrometer
/run/initialize
#/target/setThickness 30. cm
###########
# Visualisation
#/vis/scene/create
#/vis/open VRML2FILE
#/vis/open DAWNFILE
#/vis/open OGLIX
#/vis/drawVolume
#/vis/viewer/zoom 2
#/tracking/storeTrajectory 1
#/vis/scene/endOfEventAction accumulate
#/vis/viewer/set/viewpointThetaPhi 0. 0. deg
#########################
/gun/particle e-
/gun/energy 70. keV
#/tracking/verbose 1
/run/beamOn 200







