#================================================
#     Macro file for Hadr00
#     14.04.2009 Ivanchneko
#================================================
/control/verbose 1
/run/verbose 1
/tracking/verbose 0
/testhadr/TargetMat        G4_C
/testhadr/TargetRadius     1  cm
/testhadr/TargetLength     10 cm
/run/printProgress         10
#
/run/initialize
/process/em/workerVerbose 0
#
/gun/particle  neutron
/gun/energy 100. MeV
###/testhadr/fileName  nC
/testhadr/particle   neutron
/testhadr/verbose 1
/process/eLoss/verbose 0
/run/beamOn 0
#
