# $Id: GNUmakefile,v 1.2 2009-05-28 15:50:15 gcosmo Exp $
# --------------------------------------------------------------
# GNUmakefile for examples module.  Gabriele Cosmo, 06/04/98.
# --------------------------------------------------------------

name := test39
G4TARGET := $(name)
G4EXLIB := true

ifndef G4INSTALL
  G4INSTALL = ../../
endif

.PHONY: all tools
 
all: lib bin

include $(G4INSTALL)/config/binmake.gmk

