# G.A.P.Cirrone and C.Casarino
#
# Default macro file. It is called if no argument is provided at run
# 
# i.e. simply typing $G4WORKDIR/bin/Linux-++/IORT <no argument here!> 
#
# This macro can be used for a proton or electron beam in water. Both electromagnetic and
# hadronic models may be swiched on


#/control/getEnv G4SYSTEM


#########################
# Set of the verboses 
#
/control/verbose 1
/tracking/verbose 0
/run/verbose 1
/event/verbose 0

##########################
# Set of the physic models
#
 #/Physics/addPhysics emstandard_opt3                     # Electromagnetic model
 #/Physics/addPhysics Em_extra_physics			
#/Physics/addPhysics Elastic                             # Hadronic elastic model
#/Physics/addPhysics decay
#/Physics/addPhysics radioactive_decay
#/Physics/addPhysics Stopping_physics
#/Physics/addPhysics Neutron_tracking_cut
#/Physics/addPhysics binary                              # Hadronic inelastic model

#/Physics/addPhysics local_ion_ion_inelastic            # Optional Hadronic inelastic model for ions (local physic list)
#/Physics/addPackage QGSP_BIC_EMY

##########################
#       Geometry         #
##########################
#/geometrySetup/selectGeometry coll50


##########################
# Initialisation procedure
#
/run/initialize

##########################
# Visualisation 
#
/vis/scene/create
/vis/open OGL
/vis/viewer/flush
/vis/viewer/set/viewpointThetaPhi 30 140 deg
/vis/viewer/zoom 1
/vis/viewer/pan -10  0 cm
/vis/scene/add/trajectories
/vis/scene/endOfEventAction accumulate
#/vis/viewer/update  # new 

##########################
# Definition of the GUI
# It will work only if the QT GUI interface is active
#
/control/execute macro/GUIPersonalisation.mac
##########################
# Set here the cut and the step max for the tracking. 
# Suggested values of cut and step:
#
# Set cuts ONLY inside the detector
 #/Physics/setDetectorCuts 0.01 mm

# Definition of the production cuts
/run/setCut 0.01 mm
/run/setCutForAGivenParticle e- 1 mm
/run/setCutForAGivenParticle e+ 1 mm
/run/setCutForAGivenParticle gamma 1 mm
/run/setCutForAGivenParticle proton 1 mm
/run/setCutForRegion DetectorLog 0.01 mm


# Set cuts OUTSIDE the detector 
#/Physics/setCuts 1. mm
 #/Physics/setCuts 0.01 mm

 #/Step/waterPhantomStepMax 0.01 mm 

#########################
# Set the primary particle type,
# energy and position along the X direction
#
#/gun/particle proton
/beam/energy/meanEnergy 9.9 MeV   # 6.2 MeV old
/beam/energy/sigmaEnergy  500 keV # 400 keV old
/beam/position/Xposition -862.817 mm  # coll40, coll50, coll60, coll70, coll80 -> -862.817 mm ; coll100 ->  
                                                                                                # -1062.817   mm ; 

#########################
# Display the event number
# during the run
# 
/event/printEventNumber 1000

#########################
# Start of the run
#
# If secondary particles dose & fluence are needed
#/analysis/secondary true 
# Default material is water liquid
#/changePhantom/material G4_PLEXIGLASS

#/ProtectionDisc1/OuterRadiusDisc1 40   # default -> 40*mm ; 30(coll40);35(coll50);45(coll70);50(coll40);60(coll100) 
#/ProtectionDisc1/InnerRadiusDisc1      # default -> 0*mm
#/ProtectionDisc1/HeightDisc1             # default -> 2*mm
#/ProtectionDisc1/XPositionDisc1 -11.0  # default -> -11*mm   R90 (10.1 MeV) -> -10.68 mm da centro detector (24mm)
#/ProtectionDisc1/material G4_Al        # default -> G4_WATER ;

#/ProtectionDisc2/OuterRadiusDisc2 40   # default -> 40*mm ; 30(coll40);35(coll50);45(coll70);50(coll40);60(coll100)
#/ProtectionDisc2/InnerRadiusDisc2      # default -> 0*mm
#/ProtectionDisc2/HeightDisc2            # default -> 1*mm
#/ProtectionDisc2/XPositionDisc2 -8.0  # default -> -8*mm
#/ProtectionDisc2/material G4_Pb        # default -> G4_WATER ;

#/InsertProtectionDisc/insert

#/changePhantom/update

#/DeleteProtectionDisc/delete


/run/beamOn  10

