              
      COMMON/CALOR/Imat,BoxSize,Field  
*                                                               
*  Imat    = GEANT material number.                     (data card CALOR)
*  BoxSize = total size of the box (cm)                 (data card CALOR)
*  Field   = magnetic field (tesla)                     (data card CALOR)
*                                                                               
