# - G4procman module build definition

# Define the Geant4 Module.
geant4_add_module(G4procman
  PUBLIC_HEADERS
    G4EntanglementAuxInfo.hh
    G4eplusAnnihilationEntanglementClipBoard.hh
    G4NoProcess.hh
    G4ParticleTypes.hh
    G4ProcTblElement.hh
    G4ProcTblElement.icc
    G4ProcessAttribute.hh
    G4ProcessManager.hh
    G4ProcessManager.icc
    G4ProcessManagerMessenger.hh
    G4ProcessTable.hh
    G4ProcessTable.icc
    G4ProcessTableMessenger.hh
    G4ProcessType.hh
    G4ProcessVector.hh
    G4ProcessVector.icc
    G4VContinuousDiscreteProcess.hh
    G4VContinuousProcess.hh
    G4VDiscreteProcess.hh
    G4VEntanglementClipBoard.hh
    G4VProcess.hh
    G4VRestContinuousDiscreteProcess.hh
    G4VRestContinuousProcess.hh
    G4VRestDiscreteProcess.hh
    G4VRestProcess.hh
    G4WrapperProcess.hh
  SOURCES
    G4ProcTblElement.cc
    G4ProcessAttribute.cc
    G4ProcessManager.cc
    G4ProcessManagerMessenger.cc
    G4ProcessTable.cc
    G4ProcessTableMessenger.cc
    G4ProcessVector.cc
    G4VContinuousDiscreteProcess.cc
    G4VContinuousProcess.cc
    G4VDiscreteProcess.cc
    G4VProcess.cc
    G4VRestContinuousDiscreteProcess.cc
    G4VRestContinuousProcess.cc
    G4VRestDiscreteProcess.cc
    G4VRestProcess.cc
    G4WrapperProcess.cc)

geant4_module_link_libraries(G4procman
  PUBLIC
    G4baryons
    G4bosons
    G4globman
    G4heprandom
    G4intercoms
    G4ions
    G4leptons
    G4mesons
    G4partman
    G4track
  PRIVATE
    G4materials)
