#
#  This file permits to customize, with commands,
# the menu bar of the G4UIXm, G4UIQt, G4UIWin32 sessions.
# It has no effect with G4UIterminal.
#
# File :
/gui/addMenu file File
/gui/addButton file Continue continue
/gui/addButton file Exit "exit"
#
# Run menu :
/gui/addMenu run Run
/gui/addButton run "beamOn 1" "/run/beamOn 1"
/gui/addButton run run1 "/control/execute run1.mac"
/gui/addButton run run2 "/control/execute run2.mac"
#
# Gun menu :
/gui/addMenu gun Gun
/gui/addButton gun "50 MeV"  "/gun/energy 50 MeV"
/gui/addButton gun "1 GeV"   "/gun/energy 1 GeV"
/gui/addButton gun "10 GeV"  "/gun/energy 10 GeV"
/gui/addButton gun "e-"      "/gun/particle e-"
/gui/addButton gun "pi0"     "/gun/particle pi0"
/gui/addButton gun "pi+"     "/gun/particle pi+"
/gui/addButton gun "neutron" "/gun/particle neutron"
/gui/addButton gun "proton"  "/gun/particle proton"
#
# Vis menu :
/gui/addMenu vis Vis
/gui/addButton vis Vis0(OGLIX) "/control/execute visTutor/exN03Vis0.mac"
/gui/addButton vis Vis1(OGLSX) "/control/execute visTutor/exN03Vis1.mac"
/gui/addButton vis Vis2(OGLSX) "/control/execute visTutor/exN03Vis2.mac"
/gui/addButton vis Vis3(OGLSX) "/control/execute visTutor/exN03Vis3.mac"
/gui/addButton vis Vis4(OGLIX) "/control/execute visTutor/exN03Vis4.mac"
/gui/addButton vis Vis5(OIX)   "/control/execute visTutor/exN03Vis5.mac"
/gui/addButton vis Vis6(VRML2FILE) "/control/execute visTutor/exN03Vis6.mac"
/gui/addButton vis Vis7(DAWNFILE) "/control/execute visTutor/exN03Vis7.mac"
/gui/addButton vis Vis8(DAWNFILE) "/control/execute visTutor/exN03Vis8.mac"
/gui/addButton vis Vis9(OGLIWIN) "/control/execute visTutor/exN03Vis9.mac"
/gui/addButton vis Vis10(OIWin32) "/control/execute visTutor/exN03Vis10.mac"
/gui/addButton vis Vis11(OGLSXm) "/control/execute visTutor/exN03Vis11.mac"
/gui/addButton vis Vis12(OGLSX) "/control/execute visTutor/exN03Vis12.mac"
/gui/addButton vis Vis13(OGLSX) "/control/execute visTutor/exN03Vis13.mac"
/gui/addButton vis Vis14(OGLSQt) "/control/execute visTutor/exN03Vis14.mac"
/gui/addButton vis Vis15(OGLSQt) "/control/execute visTutor/exN03Vis15.mac"
#
# Viewer menu :
/gui/addMenu viewer Viewer
/gui/addButton viewer "Set style solid" "/vis/viewer/set/style solid"
/gui/addButton viewer "Set style wireframe" "/vis/viewer/set/style wire"
#/gui/addButton viewer viewer_update "/vis/viewer/update"
/gui/addButton viewer "Update scene" "/vis/scene/notifyHandlers"
#
# To limit the output flow in the "dump" widget :
/N03/event/printModulo 100
