//---------------------------------------
//        Macro file for test30
//         examine PostStepDoIt 
//        for hadronic physics
//      Created: 13.03.2002 V.Ivanchenko
//--------------------------------------- 
#verbose
0
#events
100000
//--------Proton_processes
#particle
proton
//--------
#material
Pb
#energy(MeV)
120
#emax(MeV)
120
#nbinse
120
#nbinsd
120
#elim(MeV)
30.
#nangle
13
#angles
0. 11. 24. 35. 45. 56. 69. 82. 95. 106. 121. 134. 145.
#dangle
5.
//--------
#generator
kinetic
#paw
kin.paw
#run
//--------Exit
#exit
