#
# Macro file for "ParN02.cc"
# 
# can be run in batch, without graphic
# or interactively: Idle> /control/execute run2.mac
#
/run/verbose 2
/event/verbose 0
# 
# proton 3 GeV to the direction (0.,0.,1.)  (default kinematic)
# 1 event with detailled printing
#
/tracking/verbose 1
/run/beamOn 1
# 
# set a magnetic field
# 1 events; print the hits
#
/N02/det/setField 2 tesla
/tracking/verbose 0
/hits/verbose 1
/run/beamOn 1
