              
      COMMON/CALOR/Imat,SizeX,SizeYZ,nLayers
      COMMON/FIELD/Field  
*                                                               
*  Imat    = GEANT material number                      (data card CALOR)
*  SizeX   = total  X-size of the box (cm)              (data card CALOR)
*  SizeYZ  = total YZ-size of the box (cm)              (data card CALOR)
*  nLayers = numbers of layers                          (data card CALOR) 
*  Field   = magnetic field (tesla)                     (data card FIELD)
*
      COMMON/STEPMAX/stepmax
*
*  stepmax = max allowed step length                    (data card STEPMX)
