# Macro file for example B5
# 
# Can be run in batch, without graphic
# or interactively: Idle> /control/execute run1.mac
#
# Defaults:
# armAngle 30. deg
# field value: 1.0*tesla
/run/beamOn 3
#
/mydet/armAngle 0. deg
/mydet/fieldValue 0. tesla
/run/beamOn 3
#
/mydet/armAngle 60. deg
/mydet/fieldValue 2. tesla
/run/beamOn 3
#
/mydet/armAngle 30. deg
/mydet/fieldValue 1. tesla
/mydet/momentum 2. GeV
/mydet/sigmaMomentum 0. 
/mydet/sigmaAngle 0.
/mydet/sigmaAngle 2. deg
/run/beamOn 3

