# - G4phys_ctor_hinelastic module build definition

# Define the Geant4 Module.
geant4_add_module(G4phys_ctor_hinelastic
  PUBLIC_HEADERS
    G4HadronInelasticQBBC.hh
    G4HadronInelasticQBBC_ABLA.hh
    G4HadronPhysicsFTF_BIC.hh
    G4HadronPhysicsFTFP_BERT.hh
    G4HadronPhysicsFTFP_BERT_HP.hh
    G4HadronPhysicsFTFP_BERT_TRV.hh
    G4HadronPhysicsFTFP_BERT_ATL.hh
    G4HadronPhysicsFTFQGSP_BERT.hh
    G4HadronPhysicsNuBeam.hh
    G4HadronPhysicsQGS_BIC.hh
    G4HadronPhysicsQGSP_BERT.hh
    G4HadronPhysicsQGSP_BERT_HP.hh
    G4HadronPhysicsQGSP_BIC.hh
    G4HadronPhysicsQGSP_BIC_HP.hh
    G4HadronPhysicsQGSP_FTFP_BERT.hh
    G4HadronPhysicsINCLXX.hh
    G4HadronPhysicsShielding.hh
    G4HadronPhysicsShieldingLEND.hh
    G4VHadronPhysics.hh
    G4HadronPhysicsQGSP_BIC_AllHP.hh
  SOURCES
    G4HadronInelasticQBBC.cc
    G4HadronInelasticQBBC_ABLA.cc
    G4HadronPhysicsFTF_BIC.cc
    G4HadronPhysicsFTFP_BERT.cc
    G4HadronPhysicsFTFP_BERT_HP.cc
    G4HadronPhysicsFTFP_BERT_TRV.cc
    G4HadronPhysicsFTFP_BERT_ATL.cc
    G4HadronPhysicsFTFQGSP_BERT.cc
    G4HadronPhysicsNuBeam.cc
    G4HadronPhysicsQGS_BIC.cc
    G4HadronPhysicsQGSP_BERT.cc
    G4HadronPhysicsQGSP_BERT_HP.cc
    G4HadronPhysicsQGSP_BIC.cc
    G4HadronPhysicsQGSP_BIC_HP.cc
    G4HadronPhysicsQGSP_FTFP_BERT.cc
    G4HadronPhysicsINCLXX.cc
    G4HadronPhysicsShielding.cc
    G4HadronPhysicsShieldingLEND.cc
    G4VHadronPhysics.cc
    G4HadronPhysicsQGSP_BIC_AllHP.cc)

geant4_module_link_libraries(G4phys_ctor_hinelastic
  PUBLIC
    G4globman
    G4hadronic_mgt
    G4hadronic_xsect
    G4run
  PRIVATE
    G4baryons
    G4had_fission
    G4had_par_hp
    G4had_preequ_exciton
    G4had_string_diff
    G4had_string_frag
    G4had_theo_max
    G4hadronic_abla
    G4hadronic_bert_cascade
    G4hadronic_binary
    G4hadronic_deex_photon_evaporation
    G4hadronic_proc
    G4hadronic_util
    G4ions
    G4mesons
    G4partman
    G4phys_builders
    G4phys_ctor_factory
    G4physlist_util
    G4procman
    G4shortlived)
