#Activate e.m. physics
/physics/addPhysics photon-eedl
/physics/addPhysics electron-eedl
/physics/addPhysics positron-standard
/physics/addPhysics proton-eedl
/physics/addPhysics alpha-eedl
/physics/addPhysics charged-eedl
/process/list
# Sets some default verbose
#
/control/verbose 1
/run/verbose 1
/event/verbose 0
#/tracking/verbose 1
/run/initialize
/gun/particle alpha
/gun/energy 100. MeV
/run/beamOn 100
