//---------------------------------------
//        Macro file for test30
//         examine PostStepDoIt 
//        for hadronic physics
//      Created: 13.03.2002 V.Ivanchenko
//--------------------------------------- 
#verbose
0
#events
10000
//--------Proton_processes
#particle
proton
//--------
#material
Pb
#energy(MeV)
35.
#emax(MeV)
35.
#elim(MeV)
1.
#nangle
0
//--------
#generator
LEparametrisation
#paw
par.paw
#run
#generator
preCompound
#paw
prec.paw
#run
#generator
CHIPS
#paw
chips.paw
#run
#generator
kinetic
#paw
kin.paw
#run
//--------Exit
#exit
