# $Id: dedx2.mac,v 1.1 2009-07-30 15:03:30 grichine Exp $
#
# macro file for TestEm5.cc
#
# to control dE/dx calculation
#
/control/verbose 2
/run/verbose 2
#
/testem/det/setAbsMat Graphite   
/testem/det/setAbsThick 10 um  
/testem/det/setAbsYZ    10 um
#
/testem/phys/addPhysics standard
###/testem/phys/addPhysics livermore
###/testem/phys/addPhysics penelope
#
/testem/phys/setCuts 1 km
#    
/run/initialize
#
/testem/gun/setDefault
/gun/particle e- 
/gun/energy 1 MeV
#
/testem/histo/setFileName dedx2
/testem/histo/setFileType hbook
/testem/histo/setHisto 1 100 0. 10. keV		#energy in absorber
#
/run/beamOn 10000
