# $Id: hanson.mac,v 1.2 2009-11-09 15:28:00 grichine Exp $
#
# macro file for TestEm5.cc    
#
# angle distribution of  15.7 MeV electrons
# transmitted through thin gold foils.
# A.O.Hanson et al. Phys.Rev.84 (1951) page 634.
#     		    
/control/verbose 2
/run/verbose 2
#
/testem/det/setAbsMat   Gold      
/testem/det/setAbsThick 9.658 um
####/testem/det/setAbsThick 19.296 um  
/testem/det/setAbsYZ    1 cm
#
/testem/phys/setGCut 13.0 um   
/testem/phys/setECut 1.12 um
/testem/phys/setPCut 1.12 um
#
#/testem/phys/addPhysics  standard_local
#
#/testem/phys/addPhysics  emstandard
#
#/testem/phys/addPhysics  emstandard_opt1
#
/testem/phys/addPhysics  emstandard_opt2
#/testem/phys/addPhysics  emstandard_ly
#
#/testem/phys/addPhysics  emstandard_opt3
#/testem/phys/addPhysics  standardSS
#/testem/phys/addPhysics  standardGS
#/testem/phys/addPhysics  empenelope
#/testem/phys/addPhysics  emlivermore
#
/run/initialize
#
/testem/gun/setDefault
/gun/particle e- 
/gun/energy 15.7 MeV
#
/testem/histo/setFileName hanson
/testem/histo/setFileType hbook
####/testem/histo/setHisto 12  100 0 10 deg		#space angle
/testem/histo/setHisto 12  100 0 30 deg		#space angle    
#
/testem/event/printModulo 10000 
/run/beamOn 100000
