# $Id: ihepmu.mac,v 1.1 2009-11-09 15:26:39 grichine Exp $
#
# macro file for TestEm5.cc
#
# mu+, transmitted through 14.3 mm of copper
#
/control/verbose 2
/run/verbose 2
#
/testem/det/setAbsMat Copper
/testem/det/setAbsThick 14.3 mm       ## rad. length
/testem/det/setAbsYZ    100 mm
/testem/det/setWorldX   1 m
/testem/det/setWorldYZ  1 m
#
#/testem/phys/addPhysics  standard_local
#
/testem/phys/addPhysics  emstandard
#
#/testem/phys/addPhysics  emstandard_opt1
#
#/testem/phys/addPhysics  emstandard_opt2
#/testem/phys/addPhysics  emstandard_ly
#
#/testem/phys/addPhysics  emstandard_opt3
#/testem/phys/addPhysics  standardSS
#/testem/phys/addPhysics  standardGS
#/testem/phys/addPhysics  empenelope
#/testem/phys/addPhysics  emlivermore
#
#
/testem/phys/setCuts 1 mm
#
/run/initialize
#
/testem/gun/setDefault
/gun/particle mu+
/gun/energy 7.195 GeV
#/gun/energy 11.595 GeV
#
/testem/histo/setFileName mumsc/9.2-ref00-opt0
/testem/histo/setFileType hbook
/testem/histo/setHisto 14  100 -5.0  +5.0 mm		# x-position at exit  
/testem/histo/setHisto 15  100  0.  +10.0 mm		# radius at exit  
#
/testem/stack/killSecondaries
#
/testem/event/printModulo 40000
/run/beamOn 311250
