# $Id: p600mev.mac,v 1.1 2009-11-09 15:26:39 grichine Exp $
#
# macro file for TestEm5.cc
#
# mu+, transmitted through 14.3 mm of copper
#
/control/verbose 2
/run/verbose 2
#
/testem/det/setAbsMat Copper   # Aluminium   # Graphite
/testem/det/setAbsThick 9.5 mm  # 72.5 mm   # 114.3 mm       
/testem/det/setAbsYZ    800 mm
/testem/det/setWorldX   1 m
/testem/det/setWorldYZ  1 m
#
#/testem/phys/addPhysics  standard_local
#
#/testem/phys/addPhysics  emstandard
#
#/testem/phys/addPhysics  emstandard_opt1
#
#/testem/phys/addPhysics  emstandard_opt2
/testem/phys/addPhysics  emstandard_ly
#
#/testem/phys/addPhysics  emstandard_opt3
#/testem/phys/addPhysics  standardSS
#/testem/phys/addPhysics  standardGS
#/testem/phys/addPhysics  empenelope
#/testem/phys/addPhysics  emlivermore
#
#
/testem/phys/setCuts 1 mm
#
/run/initialize
#
/testem/gun/setDefault
/gun/particle proton
/gun/energy 600 MeV
#/gun/energy 11.595 GeV
#
/testem/histo/setFileName mumsc/9.2-ref00-opt0
/testem/histo/setFileType hbook
/testem/histo/setHisto 14  100 -5.0  +5.0 mm		# x-position at exit  
/testem/histo/setHisto 15  100  0.  +10.0 mm		# radius at exit  
#
/testem/stack/killSecondaries
#
/testem/event/printModulo 40000
/run/beamOn 311250
