# $Id: shortmy.mac,v 1.1 2009-07-30 15:03:30 grichine Exp $
#
# macro file for TestEm5.cc
#
/control/verbose 2
/run/verbose 2
#
/testem/det/setAbsMat Silicon
#/testem/det/setAbsThick 20 um
/testem/det/setAbsThick 200 um
#/testem/det/setAbsThick 200 cm
/testem/det/setAbsYZ    50 um
#/testem/det/setAbsYZ    500 um
#
#/testem/phys/addPhysics  standard
/testem/phys/addPhysics  emstandard
#/testem/phys/addPhysics  emstandard_opt1
#/testem/phys/addPhysics  emstandard_opt2
#/testem/phys/addPhysics  emstandard_opt3
#
/testem/phys/setCuts 7 um
#
/run/initialize
#
/testem/gun/setDefault
#/gun/particle pi+ 
#/gun/particle proton 
/gun/particle mu+ 
#/gun/particle e- 
/gun/energy 5 GeV
#/gun/energy 5 MeV
#
/testem/histo/setFileName testem5
/testem/histo/setFileType root
/testem/histo/setHisto 13 100 -0.25 0.25 mrad 
#
/testem/event/printModulo 1
/run/beamOn 10
