#
# Macro file planeBoolI.mac
# for geometry/tracking performance test of G4IntersectionSolid from plane gun
# 100 Gev geantino
#
/control/verbose 2
# /run/verbose 2
/gun/particle geantino
/gun/energy 100 GeV
/run/initialize
#
# SimpleBox geometry made by Al
# Geantino from random points in planes, 10 events each .
#
# from +/- X-axis
#
/mydet/SwitchDetector SimpleBox
/mydet/SelectMaterial Al
/mydet/SwitchBool Intersection
/tsGun/planeGun 100.0 0.0 0.0
/tracking/verbose 1
/run/beamOn 10
#
#/mydet/SwitchDetector SimpleBox
#/mydet/SelectMaterial Al
#/mydet/SwitchCSG Tubs
/tsGun/planeGun -100.0 0.0 0.0
/tracking/verbose 1
/run/beamOn 10
#
# from +/- Y-axis
#
#/mydet/SwitchDetector SimpleBox
#/mydet/SelectMaterial Al
#/mydet/SwitchCSG Tubs
/tsGun/planeGun 0.0 100.0 0.0
/tracking/verbose 1
/run/beamOn 10
#
/mydet/SwitchDetector SimpleBox
/mydet/SelectMaterial Al
#/mydet/SwitchCSG Box
/tsGun/planeGun 0.0 -100.0 0.0
/tracking/verbose 1
/run/beamOn 10
#
# from +/- Z-axis
#
#/mydet/SwitchDetector SimpleBox
#/mydet/SelectMaterial Al
#/mydet/SwitchCSG Tubs
/tsGun/planeGun 0.0 0.0 100.0
/tracking/verbose 1
/run/beamOn 10
#
#/mydet/SwitchDetector SimpleBox
#/mydet/SelectMaterial Al
#/mydet/SwitchCSG Tubs
/tsGun/planeGun 0.0 0.0 -100.0
/tracking/verbose 1
/run/beamOn 10
#
#
exit
