#
# Macro file planeBoolU.mac
# for geometry/tracking performance test of G4UnionSolid from plane gun
# 100 Gev geantino
#
/control/verbose 2
# /run/verbose 2
/gun/particle geantino
/gun/energy 100 GeV
/run/initialize
#
# SimpleBox geometry made by Al
# Geantino in random directions from point, 10 events.
#
# from +/- X-axis
#
/mydet/SwitchDetector SimpleBox
/mydet/SelectMaterial Al
/mydet/SwitchBool Union
/tsGun/viewerGun 100.0 0.0 0.0
/tracking/verbose 1
/run/beamOn 10
#
#/mydet/SwitchDetector SimpleBox
#/mydet/SelectMaterial Al
#/mydet/SwitchCSG Tubs
/tsGun/viewerGun -100.0 0.0 0.0
/tracking/verbose 1
/run/beamOn 10
#
# from +/- Y-axis
#
#/mydet/SwitchDetector SimpleBox
#/mydet/SelectMaterial Al
#/mydet/SwitchCSG Tubs
/tsGun/viewerGun 0.0 100.0 0.0
/tracking/verbose 1
/run/beamOn 10
#
/mydet/SwitchDetector SimpleBox
/mydet/SelectMaterial Al
#/mydet/SwitchCSG Box
/tsGun/viewerGun 0.0 -100.0 0.0
/tracking/verbose 1
/run/beamOn 10
#
# from +/- Z-axis
#
#/mydet/SwitchDetector SimpleBox
#/mydet/SelectMaterial Al
#/mydet/SwitchCSG Tubs
/tsGun/viewerGun 0.0 0.0 100.0
/tracking/verbose 1
/run/beamOn 10
#
#/mydet/SwitchDetector SimpleBox
#/mydet/SelectMaterial Al
#/mydet/SwitchCSG Tubs
/tsGun/viewerGun 0.0 0.0 -100.0
/tracking/verbose 1
/run/beamOn 10
#
#
exit
