#
/control/execute vis.mac
#
########################################
#
/score/create/cylinderMesh cylinderMesh_1
#
/score/mesh/cylinderSize 1. 1. m
/score/mesh/translate/xyz 0. 0. 0. cm
#
/score/mesh/nBin 30 30 30
#
/score/quantity/doseDeposit dDepPS
#
/score/close
#
########################################
#
/score/list
#
/vis/disable
/run/beamOn 10000
/vis/enable
#
########################################
#
/vis/drawVolume
/score/drawProjection cylinderMesh_1 dDepPS
#
