#
/control/execute vis.mac
#
########################################
#
/score/create/boxMesh boxMesh_1
#
/score/mesh/boxSize 1. 1. 1. m
/score/mesh/translate/xyz 0. 0. 0. cm
#
/score/mesh/nBin 30 30 30
#
/score/quantity/doseDeposit eDepPS
#
/score/close
#
########################################
#
/score/list
#
#/run/beamOn 10000
/run/beamOn 100
#
########################################
#
/vis/drawVolume
/score/drawProjection boxMesh_1 eDepPS
#
