#
# Macro file for "Hadr06.cc"
#
# NB. for neutronHP, do not forget to activate the fission fragment model
#     via one, and only one, of the following two UI commands:
# - To use the default fission model:
#/process/had/particle_hp/produce_fission_fragment true
#
# - To use the alternative Wendt fission model:
#/process/had/particle_hp/use_Wendt_fission_model true
#
/control/verbose 2
/run/verbose 1
#
/testhadr/det/setIsotopeMat U235 92 235 19.05 g/cm3
/testhadr/det/setRadius 5 cm
#
/run/initialize
#
# Set a very high time threshold to allow all decays to happen
/process/had/rdm/thresholdForVeryLongDecayTime 1.0e+60 year
#
/control/execute vis.mac
#
/gun/particle neutron
/gun/energy 2 MeV
#
/run/beamOn 1
