#
# Macro file for "Hadr06.cc"
#
# To "force" primary fission only, kill secondary neutrons:
# in TrackingAction.cc,uncomment lines below "to force only 1 fission ..."
# ( ~ end of PreUserTrackingAction() )
# Also, to limit the printout, do not fill ParticleCount()
# ( ~ begin of PreUserTrackingAction() )
#  
/run/verbose 2
#
/testhadr/det/setIsotopeMat U235 92 235 19.05 g/cm3
/testhadr/det/setRadius 10 cm
#
/run/initialize
#
/process/inactivate nCapture
/process/had/particle_hp/produce_fission_fragment true
#
/gun/particle neutron
/gun/energy 0.025 eV
#
/analysis/setFileName singleFission
/analysis/h1/set  1 100  100. 300. MeV	#Edep
/analysis/h1/set  3 100    0.  20. MeV	#Eflow
#
/run/printProgress 10000
/run/beamOn 100000
