//---------------------------------------
//        Macro file for test30
//         examine PostStepDoIt 
//        for hadronic physics
//      Created: 13.03.2002 V.Ivanchenko
//--------------------------------------- 
#verbose
0
#events
1000
//--------Proton_processes
#particle
neutron
//--------
#material
Fe
#energy(MeV)
65.
#emax(MeV)
80
#elim(MeV)
15.
#nangle
5
#angles
9.5 16.5 21. 24.5 28.   
#dangle
4.
//--------
generator
kinetic
#paw
kin.paw
#run
//--------Exit
#exit
