n //---------------------------------------
//        Macro file for test30
//         examine PostStepDoIt
//        for hadronic physics
//      Created: 13.03.2002 V.Ivanchenko
//---------------------------------------
#verbose
0
#events
100000
//--------Proton_processes
#particle
alpha
//--------
#material
C
#energy(MeV)
540.
// 4 * 135 MeV
#sigmae(MeV)
0.5
#emax(MeV)
200.
#nbinse
100
#nbinsd
100
#elim(MeV)
1.
#nangle
6
#angles
0. 15. 30. 50. 80. 110.
#dangle
5.
//--------
#generator
binary_ion
#paw
bin.paw
#run
//--------Exit
#exit
