/tracking/verbose 1
/run/verbose 1
/run/initialize
/tracking/storeTrajectories 1
/vis~/create_view/new_graphics_system DAWN
/vis/scene/add/trajectories
/run/beamOn 1
/vis/refresh/view
/vis/view/update
/vis/draw/current
/vis/show/view
/geom/switch assembly
/vis~/create_view/new_graphics_system DAWN
/vis/scene/add/trajectories
/run/beamOn 1
/vis/refresh/view
/vis/view/update
/vis/draw/current
/vis/show/view
