//---------------------------------------
//        Macro file for test30
//         examine PostStepDoIt 
//        for hadronic physics
//      Created: 13.03.2002 V.Ivanchenko
//--------------------------------------- 
#verbose
0
#events
100000
//--------Proton_processes
#exclusive
#particle
proton
//--------
#material
Al
#energy(MeV)
90.
#emax(MeV)
100.
#nbinse
50
#elim(MeV)
2.
#nangle
8
#angles
20. 30. 45. 60. 90. 105. 120. 135.
#dangle
10.
//--------
#generator
kinetic
#paw
kin.paw
#run
//--------Exit
#exit
