# $Id: cms.mac,v 1.1 2006-12-07 15:25:40 allison Exp $

/control/verbose 2
/control/alias pause 10

# Draw geometry hierarchy to depth 2
# Make a scene with detetctor to depth 2
/vis/scene/create
# Search for volume (takes a little while) and add
/vis/scene/add/volume OCMS 0 2
# Draw geometry hierarchy
/vis/open ATree
/vis/ASCIITree/verbose 2
# /vis/ASCIITree/verbose 3
# Takes a long time with verbose 3 because of volume calculation of
# some volumes, I think.  (Some are done by Monte Carlo sampling.)
/vis/viewer/refresh
/control/shell sleep {pause}

# Set some vis attributes
# Top volume
/vis/geometry/set/visibility OCMS ! false
# Level 1 volume
/vis/geometry/set/visibility CMSE ! false
# Level 2 - main components
# Set colour of sub-trees to unlimited depth
/vis/geometry/set/colour Tracker -1 green
/vis/geometry/set/colour CALO -1 red
/vis/geometry/set/colour MUON -1 blue
/vis/geometry/set/colour BEAM -1 cyan
/vis/geometry/set/colour VCAL -1 magenta

# /vis/verbose confirmations

# Make a scene with detector to depth 4
/vis/scene/create
/vis/scene/add/volume OCMS 0 4

/vis/open OGLSX 600x600-0+0
/control/shell sleep {pause}

/vis/viewer/set/viewpointThetaPhi 60 30
/control/shell sleep {pause}

# Cull low density volumes (air, etc.)
/vis/viewer/set/culling density true 10 mg/cm3
/control/shell sleep {pause}

# Hidden line removal
/vis/viewer/set/hiddenEdge true
/control/shell sleep {pause}

# Surfaces
/vis/viewer/set/style surface
/control/shell sleep {pause}

/vis/viewer/addCutawayPlane 0 0 0 m -1 0 0
/control/shell sleep {pause}

/vis/viewer/zoom 2
/control/shell sleep {pause}

/vis/open OGLSXm
# Copy view parameters from above OGLSX viewer
/vis/viewer/set/all viewer-1
/vis/viewer/update

/vis/open OIX
# Copy view parameters from above OGLSXm viewer
/vis/viewer/set/all viewer-2
/vis/viewer/update

exit

# The following seems to get stuck in the tracker
# Make a scene with detector to depth 5
/vis/scene/create
/vis/scene/add/volume OCMS 0 5
/vis/open OGLIX

/vis/viewer/set/all viewer-2

