// -*- C++ -*-
// AID-GENERATED
// =========================================================================
// This class was generated by AID - Abstract Interface Definition          
// DO NOT MODIFY, but use the org.freehep.aid.Aid utility to regenerate it. 
// =========================================================================
#ifndef HEPREP_HASHEPREP_H
#define HEPREP_HASHEPREP_H 1

// Copyright 2000-2005, FreeHEP.

namespace HEPREP {

class HepRep;

/**
 * The HasHepRep interface.
 *
 * @author Mark Donszelmann
 */
class HasHepRep {

public: 
    /// Destructor.
    virtual ~HasHepRep() { /* nop */; }

    /**
     * Returns the associated HepRep to this object.
     *
     */
    virtual HepRep & getHepRep() = 0;
}; // class
} // namespace HEPREP
#endif /* ifndef HEPREP_HASHEPREP_H */
