// -*- C++ -*-
// AID-GENERATED
// =========================================================================
// This class was generated by AID - Abstract Interface Definition          
// DO NOT MODIFY, but use the org.freehep.aid.Aid utility to regenerate it. 
// =========================================================================
#ifndef HEPREP_HEPREPCONSTANTS_H
#define HEPREP_HEPREPCONSTANTS_H 1

// Copyright 2000-2005, FreeHEP.

namespace HEPREP {

/**
 * Constants for HepRep interfaces.
 *
 * @author Mark Donszelmann
 */
class HepRepConstants {

public: 
    /// Destructor.
    virtual ~HepRepConstants() { /* nop */; }

    /**
     * Defines constants for type
     */
    enum { TYPE_UNKNOWN = -1, TYPE_STRING = 1, TYPE_COLOR = 2, TYPE_LONG = 10, TYPE_INT = 11, TYPE_DOUBLE = 20, TYPE_BOOLEAN = 30 };

    /**
     * Defines constants for showLabel
     */
    enum { SHOW_NONE = 0x0000, SHOW_NAME = 0x0001, SHOW_DESC = 0x0002, SHOW_VALUE = 0x0004, SHOW_EXTRA = 0x0008 };
}; // class
} // namespace HEPREP
#endif /* ifndef HEPREP_HEPREPCONSTANTS_H */
