#
# Macro file for "Hadr04.cc"
# (can be run in batch, without graphic)
#
# neutron 2 MeV; all processes
#
/control/verbose 2
/run/verbose 2
#
/testhadr/det/setMat graphite
/testhadr/det/setSize 20 m
#
/testhadr/phys/thermalScattering true
#
/run/initialize
#
/process/list
#
/particle/createAllIsomer
/gun/particle neutron
/gun/energy 2 MeV
#
/analysis/setFileName Graphite_on
/analysis/h1/set 1  100  0. 200. none	#nb colli >1eV
/analysis/h1/set 2  100  0. 5. m	#track len >1eV
/analysis/h1/set 3  100  0. 50. mus	#time of flight >1eV
/analysis/h1/set 4  100  0. 10000. none	#nb colli <1eV
/analysis/h1/set 5  100  0. 100. m	#track len <1eV
/analysis/h1/set 6  100  0. 100. ms	#time of flight <1eV
/analysis/h1/set 7  100  0. 500. meV	#energy dist <1eV
#
/run/printProgress 200
#
/run/beamOn 2000
