#
# Macro file 'run11.mac' for the initialization phase of "TestEm8.cc"
#
# It creates the default geometry (simple absorber cylinder )        
#
/control/verbose 2
#
#control/saveHistory
#
/run/verbose 2
#
/run/initialize
#
#/calor/setAbsMat Xenon
#  
#/calor/setAbsThick  20.0 mm 
# 
#/calor/setAbsRad 100.0 mm
#
#/calor/update
#
#  hist file name
#
#/plots/sethistName g4.p11
#
/plots/sethistName g4.p11
#
#  PLOT: kinetic energy distribution in absorber
#
#/plots/setnbinEn 95
#/plots/setEnlow 0.0 MeV
#/plots/setEnhigh 0.1  MeV 
# 
/plots/setnbinTt 10
/plots/setTtlow 99.9996 MeV
/plots/setTthigh 100.0002  MeV  
#
/plots/setnbinTglob 20
/plots/setTgloblow 0.00 ns
/plots/setTglobhigh 20.0 ns  
#
#/calor/cutG 3.0 mm    
#
#/calor/cutE 3.0 mm
#
/run/initialize
/run/particle/dumpCutValues
#
/gun/particle proton
#
#/gun/particle chargedgeantino
# 
#/gun/energy 2000.00 GeV
#
/gun/energy 1.0 MeV
#
#/tracking/verbose 1
#
/event/printModulo 1
/run/beamOn 5
#
#








