#
# This file permits to customize, with commands,
# the menu bar of the G4UIXm, G4UIQt, G4UIWin32 sessions.
# It has no effect with G4UIterminal.
#
# Process vis.mac (and draw geometry)
#
/control/execute vis.mac
#
# File menu :
/gui/addMenu file File
/gui/addButton file Quit exit
#
# Run menu :
/gui/addMenu run Run
/gui/addButton run "beamOn 1" "/run/beamOn 1"
#
# Gun menu :
/gui/addMenu gun Gun
/gui/addButton gun "511 keV"  "/gun/energy 511 keV"
/gui/addButton gun "5 MeV"  "/gun/energy 5 MeV"
/gui/addButton gun "50 MeV"   "/gun/energy 50 MeV"
/gui/addButton gun "e-"      "/gun/particle e-"
/gui/addButton gun "pi0"     "/gun/particle pi0"
/gui/addButton gun "pi+"     "/gun/particle pi+"
/gui/addButton gun "neutron" "/gun/particle neutron"
/gui/addButton gun "proton"  "/gun/particle proton"
#

