/control/execute common_settings_lowgran.mac
# Overwrite the sensitivity of the absorber to account for the passive material
/Par04/detector/setAbsorber 0 G4_W 1.4 mm false

# Initialize
/run/initialize

/control/execute common_settings_postInit.mac
/control/execute common_settings_vis.mac

## dynamically set readout mesh from particle direction
/param/ActivateModel defineMesh
## we do not use ML fast sim
/param/InActivateModel inferenceModel
/param/InActivateModel dummyModel
/run/beamOn 1
