#
# Macro file of "SolidsChecker.cc"
# for Optical photons geometry test
#
/run/initialize
#/geometry/test/recursive_test
/particle/list
#/tracking/verbose 1
#
#/mydet/SelectDetector Cone
#
/mydet/SelectDetector Sphere
#
/event/printModulo 100000
/run/beamOn 1000000
/event/printModulo 10000
#/tracking/verbose 3
/run/beamOn 100000
#
#/run/beamOn 353561 Torus
#/run/beamOn 6236 Cone
#
#/event/printModulo 10000
#/run/beamOn 100000
#/event/printModulo 100000
#/run/beamOn 1000000
