#!/usr/bin/env bash

THIS=$(dirname $0)

#---Enable FPE ---------------------------------------------------
#export CXXFLAGS=-DG4FPE_DEBUG

CONFIG=slc6-clang34

#use Xercesc 3.1.1p1 from ...experimental....
XERCESC_VERSION=3.1.1p1

#run without root
export ROOTSYS="-"
export CLHEP_ROOT_DIR="-"

Clang_dir=/afs/cern.ch/sw/lcg/external/llvm/3.4/x86_64-slc6-gcc48-opt

# as clang was built with 4.8, we need the libs for this
. /afs/cern.ch/sw/lcg/external/gcc/4.8/x86_64-slc6-gcc48-opt/setup.sh
# now set up clang
.  ${Clang_dir}/setup.sh

export CXX=${Clang_dir}/bin/clang++
export  CC=${Clang_dir}/bin/clang

. ${THIS}/g4ec-slc-common x86_64-slc6 4.8
