#!/usr/bin/env bash

THIS=$(dirname $0)

#---Enable FPE ---------------------------------------------------
export CXXFLAGS=-DG4FPE_DEBUG

#use Xercesc 3.1.1p1 from explicit place 
XercesC_dir=/afs/cern.ch/sw/lcg/external/XercesC/3.1.1p1/x86_64-slc6-gcc48-opt

CONFIG=slc6-gcc49

. ${THIS}/g4ec-slc-common x86_64-slc6 4.9
