#!/usr/bin/env bash

#-----------------------------------------------------------------
THIS=$(dirname $0)

CONFIG=slc5-gcc43

#---Enable FPE -----------------------------------------------------
export CXXFLAGS=-DG4FPE_DEBUG

. ${THIS}/g4ec-slc-common x86_64-slc5 4.3
