
      COMMON/EDEPO/EDEP,SEDEP,SEDEP2
     +            ,DEEM,STMA,STMI,RMAX
     +            ,anbstep,sstep,s2step,anch,anne
     +            ,anele,anpos,sanele,sanpos
     +            ,sanch,sanch2,sanne,sanne2 
     +            ,tra,ref,stra,sref
     +            ,nth0
     +            ,NHI1,HIS1(2),NHI2 ,HIS2(2),NHI3,HIS3(2),NHI4,HIS4(2)
     +            ,NHI5,HIS5(2),NHI6 ,HIS6(2),NHI7,HIS7(2),NHI8,HIS8(2)
     +            ,NHI9,HIS9(2),NHI10,HIS10(2)
      COMMON/PLOTS/NAME
      CHARACTER*25 NAME
      COMMON/GEOMAT/MATWLD,XWORLD,YZWORL,FieldW,
     +              MATABS,XABSOR,YZABSO,FieldA,
     +              XPOSAB,X1ABSO,X2ABSO, 
     +              XVERT ,YVERT ,ZVERT

