# $Id: run2a.mac,v 1.2 2005-12-07 18:30:49 japost Exp $
#
# Macro file for "exampleNTST.cc"
# 
# (can be run in batch, without graphic)
#
/control/verbose 2
/control/saveHistory
/NTST/setDebug 0
#
/run/verbose 0
/event/verbose 0
/tracking/verbose 0
#
# construct the default geometry
# 
/run/useBgsTran 0
/run/minEcut 1 MeV
/run/looperCut 200 MeV
/run/cut 1 mm
/gen/choose evt
#
/run/initialize
/run/beamOn 1000
