#################################################################################
#                                                                              	#
# ESA-CERN GEANT4 RADIOACTIVE DECAY MODULE                                     	#
# VALIDATION TEST for the Pb210 decay                                           #	
# 									      										#
# THIS TEST  DEMONSTRATE THAT after the Beta decay of Pb210, 					#
#	the atomic relaxation of 210Bi[46.539keV]	takes place for the 		 	# 
#   simulation case  where  half-life treshold is set to 1.e-6s					#
#																				#
#	In this case   210Bi[46.539keV]   tracks should not be seen 				#
#	in the tracking verbose	but Auger electrons ares still produced				#
#  Desorgher  Laurent, 17 October 2011                                    		#
#                                                                              	#
#################################################################################
#
# NOTE THAT THE FIRST RECORD IN THIS MACROFILE IS THE OUTPUT LOG-FILE NAME.
# NOW SET VERBOSE LEVELS FOR RUN, EVENT, TRACKING AND THE RDM PROCESS.
/run/filename Pb210Test.log
/run/verbose 0
/event/verbose 0
/tracking/verbose 0

/grdm/analogueMC 1
/grdm/verbose 0

/grdm/hlThreshold 1.0000e-06 s
/grdm/verbose 0
/grdm/nucleusLimits 210 210 82 82


#Source
##########################
/tracking/verbose 1
/grdm/ion 210 82 0
/run/beamOn 10









