#################################################################################
#                                                                              	#
# ESA-CERN GEANT4 RADIOACTIVE DECAY MODULE                                     	#
# VALIDATION TEST NUMBER 5                                                  	#	
# 									      	#
# THIS TEST SHOWS THE DECAYS OF CR-46, WICH HAS A PURE BETA+ DECAY CHANNLE 	#
#                                                                              	#
#       IT DEMONSTRATES THE ABILITY IN RDM TO GENERATE BETA+ PARTICLES WITH 	#
#       CORRECT ENERGY AND DECAY TIME						#
#                                                                              	#
# F LEI, DERA FARNBOROUGH, 8 MARCH 2000                                        	#
#                                                                              	#
#################################################################################
#
# NOTE THAT THE FIRST RECORD IN THIS MACROFILE IS THE OUTPUT LOG-FILE NAME.
# NOW SET VERBOSE LEVELS FOR RUN, EVENT, TRACKING AND THE RDM PROCESS.
#
# This macro takes a long time to finish!
#
/run/filename tav05a.log

/run/verbose 0
/event/verbose 0
/tracking/verbose 0

/grdm/analogueMC 1
/grdm/fBeta 1
/grdm/verbose 0

/grdm/nucleusLimits 46 46 24 24
/grdm/ion 46 24 0
/run/beamOn 100


