#################################################################################
#                                                                              	#
# ESA-CERN GEANT4 RADIOACTIVE DECAY MODULE                                     	#
# VALIDATION TEST NUMBER 7                                                  	#	
# 									      	#
# THIS TEST SHOWS THE DECAYS OF NE-24 TO NA-24 IN VARIANCE 			#
# REDUCTION MODE USING THE DEFAULT SETTINGS OF RDM				#
#                                                                              	#
# F LEI, DERA FARNBOROUGH, 8 MARCH 2000                                        	#
#                                                                              	#
#################################################################################
#
# NOTE THAT THE FIRST RECORD IN THIS MACROFILE IS THE OUTPUT LOG-FILE NAME.
# NOW SET VERBOSE LEVELS FOR RUN, EVENT, TRACKING AND THE RDM PROCESS.
#
/run/filename tav07.log
/run/verbose 0
/event/verbose 0
/tracking/verbose 0
/grdm/analogueMC 0
/grdm/verbose 0

/grdm/nucleusLimits 24 24 10 10
/grdm/ion 24 10 0
/run/beamOn 100






