#################################################################################
#                                                                              	#
# ESA-CERN GEANT4 RADIOACTIVE DECAY MODULE                                     	#
# VALIDATION TEST NUMBER 11                                                  	#	
# 									      	#
# THIS TEST SHOWS THE DECAYS OF THE F-24 TO MG-24 CHAIN IN VARIANCE 		#
# REDUCTION MODE USING THE DEFAULT SOURCE-PROFILE-FUNCTION AND DEFAULT          #
# DECAY-BIAS-FUNCTION.		      						#
#                                                                              	#
# F LEI, DERA FARNBOROUGH, 8 MARCH 2000                                        	#
#                                                                              	#
#################################################################################
#
# NOTE THAT THE FIRST RECORD IN THIS MACROFILE IS THE OUTPUT LOG-FILE NAME.
# NOW SET VERBOSE LEVELS FOR RUN, EVENT, TRACKING AND THE RDM PROCESS.
#
/run/filename tav11.log
/run/verbose 0
/event/verbose 0
/tracking/verbose 0

/grdm/analogueMC 0
/grdm/BRbias 0
/grdm/verbose 0

/grdm/ion 24 9  0
/run/beamOn 10



