#################################################################################
#                                                                              	#
# ESA-CERN GEANT4 RADIOACTIVE DECAY MODULE                                     	#
# VALIDATION TEST NUMBER 21                                                  	#	
# 									      	#
* THIS TEST TO DEMONSTRATE THAT ISOTOPES GENERATED IN HADRONIC                  #
# PROCESSES CAN BE TREATED BY THE RDM.					        # 
#                                                                              	#
# F LEI, DERA FARNBOROUGH, 8 MARCH 2000                                        	#
#                                                                              	#
#################################################################################
#
# NOTE THAT THE FIRST RECORD IN THIS MACROFILE IS THE OUTPUT LOG-FILE NAME.
# NOW SET VERBOSE LEVELS FOR RUN, EVENT, TRACKING AND THE RDM PROCESS.
/run/filename tav22.log
/run/verbose 0
/event/verbose 0
/tracking/verbose 0

/grdm/analogueMC 1
/grdm/verbose 0

/gun/particle proton 
/gun/energy 1 GeV
/run/beamOn 100



