#################################################################################
#                                                                              	#
# ESA-CERN GEANT4 RADIOACTIVE DECAY MODULE                                     	#
# VALIDATION TEST for the Pb210 decay                                           #	
# 									      										#
# THIS TEST  DEMONSTRATE THE use of user data for radioactive decay				#
# 																				# 
#                                                                              	#
#  Desorgher  Laurent, 1o October 2011                                    		#
#                                                                              	#
#################################################################################
#
# NOTE THAT THE FIRST RECORD IN THIS MACROFILE IS THE OUTPUT LOG-FILE NAME.
# NOW SET VERBOSE LEVELS FOR RUN, EVENT, TRACKING AND THE RDM PROCESS.
/run/filename UserRadDataPb210Test
/run/verbose 0
/event/verbose 0
/tracking/verbose 0

/grdm/analogueMC 1
/grdm/verbose 0



/grdm/verbose 0
/grdm/nucleusLimits 210 210 82 82

#Radioactive decay data for Pb210 given in file UserRadData_z82.a210
#In this file we have boosted the alpha decay of   Pb210 to 50% branching ratio
#This has the effect that more neraly 50% of alpha decay  should be observed in the tracking verbose

/grdm/setRadioactiveDecayFile 82 210 UserRadData_z82.a210


#Source
##########################
/tracking/verbose 1
/grdm/ion 210 82 0
/run/beamOn 10









