# $Id: targtest.mac,v 1.1 2003-07-31 01:11:01 dwright Exp $
#
# Macro file for "qqinc.cc"
# 
# /control/verbose 2
/control/saveHistory
/target/setTgtMat Lead
/target/setTgtThick 2.0 mm
# /target/setTgtRadius 5.0 cm
/target/update 
#
/run/verbose 2
/event/verbose 0
/event/printModulo 10000
/tracking/verbose 0
# 
# 950 MeV/c pi- in the direction (0.,0.,1.)
#
/gun/particle pi-
/gun/energy 820.6 MeV
/run/beamOn 10000000
