
#sample with weight window, onBoundary and degenerate window (zero window size)
#sample with importance biasing options
/Tst33/Scoring   
/Tst33/ImportanceSampling
/Tst33/WeightRoulette 0
/Tst33/ConfigureSampling
/Tst33/Run 30
/Tst33/PostRun

#sample with all options, weight change fixed by weight roulette
/Tst33/ClearSampling
/Tst33/Scoring   
/Tst33/ImportanceSampling
/Tst33/WeightRoulette 1
/Tst33/ConfigureSampling
/Tst33/Run 30
/Tst33/PostRun

#change sampling 
/Tst33/ClearSampling
/Tst33/Scoring   
/Tst33/ImportanceSampling
/Tst33/ConfigureSampling
/Tst33/Run 30
/Tst33/PostRun


#change sampling 
/Tst33/ClearSampling
/Tst33/Scoring   
/Tst33/WeightRoulette 0
/Tst33/ConfigureSampling
/Tst33/Run 30
/Tst33/PostRun

#change sampling, weight change fixed by weight roulette 
/Tst33/ClearSampling
/Tst33/Scoring   
/Tst33/WeightRoulette 1
/Tst33/ConfigureSampling
/Tst33/Run 30
/Tst33/PostRun


#change sampling 
/Tst33/ClearSampling
/Tst33/Scoring   
/Tst33/ConfigureSampling
/Tst33/Run 30
/Tst33/PostRun

#change 
/Tst33/ClearSampling
/Tst33/ImportanceSampling
/Tst33/ConfigureSampling
/Tst33/Run 30
/Tst33/PostRun

