# $Id: csda.mac,v 1.2 2007-02-16 11:59:47 maire Exp $
#
# macro file for TestEm18.cc
#
/control/verbose 2
/run/verbose 2
#
/testem/det/setMat Water
###/testem/det/setMat Water_vapor
/testem/det/setSize 1 cm
#
/testem/phys/setCuts 100 km
#
/run/initialize
#
/process/eLoss/fluct false
/process/eLoss/StepFunction 1 1 mm
#
/gun/particle e- 
/gun/energy 20 MeV
#
/run/beamOn 1
#
/testem/stepMax 10 um
#
/run/beamOn 1
