# $Id: pixe.mac 66241 2012-12-13 18:34:42Z gunter $
#
# macro file for TestEm18.cc
#
/control/verbose 2
/run/verbose 2
#
/testem/det/setMat Tungsten
/testem/det/setSize 100 um
#
/testem/phys/setCuts 1 um
#
/run/initialize
#
/process/em/pixe true
#
/gun/particle proton 
/gun/energy 10 MeV
#
/analysis/setFileName pixe
# 
/analysis/h1/set 3 100 0 10 MeV	    #total eLoss
/analysis/h1/set 5 100 0 100 keV    #gamma energy spectrum
#
/testem/event/printModulo 100000
#
/run/beamOn 1000000
