# $Id: gui.mac,v 1.1 2009-11-27 16:06:28 mkossov Exp $
#
# macro file for test57.cc
#
/control/verbose 2
/run/verbose 2
#
/testem/det/setAbsMat   Lead    # Cadmium # Copper  # Copper # Aluminium # Graphite
/testem/det/setAbsThick 8.33 mm # 12.7 mm # 25.4 mm # 9.5 mm # 72.5 mm   # 114.3 mm       
/testem/det/setAbsYZ    800 mm
/testem/det/setWorldX   1 m
/testem/det/setWorldYZ  1 m
#
#/testem/phys/addPhysics  standard_local
#
#/testem/phys/addPhysics  emstandard
#
#/testem/phys/addPhysics  emstandard_opt1
#
#/testem/phys/addPhysics  emstandard_opt2
#/testem/phys/addPhysics  emstandard_ly
#
#/testem/phys/addPhysics  emstandard_opt3
#/testem/phys/addPhysics  standardSS
#/testem/phys/addPhysics  standardGS
#/testem/phys/addPhysics  empenelope
#/testem/phys/addPhysics  emlivermore
#
#
#/testem/phys/setCuts 1 mm
#
/run/initialize
#
/testem/gun/setDefault
/gun/particle proton
/gun/energy 600 MeV
#/gun/energy 11.595 GeV
#
#
/testem/stack/killSecondaries
#
/testem/event/printModulo 10000
/run/beamOn 100000
