#================================================
# Macro file to test IAEAphsp writer
#================================================
/control/verbose 1
/run/verbose 1
/tracking/verbose 0
/event/verbose 0
#
/action/IAEAphspWriter/namePrefix  psf_z
/action/IAEAphspWriter/zphsp       50.1 cm
/action/IAEAphspWriter/zphsp       60.5 cm
#
/my_geom/worldXY   25.0 cm
/my_geom/worldZ   100.0 cm
#
/my_phys/setList    QGSP_BIC_HP_EMZ
#
/run/initialize
#
/run/setCut          0.1 mm
#
/gun/particle  gamma
/my_beam/kinE    10.0 MeV
/my_beam/DE       5.0 MeV
/my_beam/X0   7.0 cm
/my_beam/DX   2.0 cm
/my_beam/Y0  -5.0 cm
/my_beam/DY   1.0 cm
/my_beam/Z0   0.0 cm
/my_beam/verbose  2
#
##/run/printProgress  10
/run/beamOn         50
#
