# test05
#
/run/initialize
#
/gps/particle geantino

# ellipse plane source
/gps/pos/type Plane
/gps/pos/shape Ellipse
/gps/pos/centre 3. 1. 0. cm
/gps/pos/halfx 1. cm
/gps/pos/halfy 2. cm

#isotropic angular distribution
/gps/ang/type iso

# brems energy distr.
/gps/ene/type Brem
/gps/ene/min 2. MeV
/gps/ene/max 10. MeV
/gps/ene/temp 2e12

# commands below are independent of gps
#
/analysis/setFileName test05
/analysis/h1/set 1 100 1 15 MeV
/analysis/h2/set 1 100 -5 5 cm none linear 100 -5 5 cm none linear 
/analysis/h2/set 4 120 0 360 deg none linear 100 -1 1 none none linear
#
#/control/execute vis.mac
#
/run/printProgress 10000
#
/run/beamOn 100000


