# test26
#
/run/initialize
#
/gps/particle geantino

# source
/gps/pos/type Plane
/gps/pos/shape Square
/gps/pos/centre 1. 2. 1. cm
/gps/pos/halfx 2. cm
/gps/pos/halfy 2. cm

# angular distribution
/gps/ang/type cos
/gps/ang/mintheta 1. rad
/gps/ang/maxtheta 2. rad
/gps/ang/minphi 1.5 rad
/gps/ang/maxphi 3. rad

# energy distribution
/gps/ene/type Lin
/gps/ene/min 2. MeV
/gps/ene/max 10. MeV
/gps/ene/gradient 1.
/gps/ene/intercept 1.
#
/gps/hist/type biase
/gps/hist/point 0.   0.
/gps/hist/point 0.25 1.
/gps/hist/point 0.5  2.
/gps/hist/point 0.75 1.
/gps/hist/point 1.   0.1
#/gps/number 3

# commands below are independent of gps
#
/analysis/setFileName test26
/analysis/h1/set 1 100 0 15 MeV
/analysis/h2/set 1 100 -5 5 cm none linear 100 -5 5 cm none linear #x-y
/analysis/h2/set 4 120 0 360 deg none linear 100 -1 1 none none linear
/analysis/h2/set 5 120 0 360 deg none linear  90 0 180 deg none linear
#
#/control/execute vis.mac
#
/run/printProgress 10000
#
/run/beamOn 100000
