//---------------------------------------
//        Macro file for test30
//         examine PostStepDoIt 
//        for hadronic physics
//      Created: 13.03.2002 V.Ivanchenko
//--------------------------------------- 
#verbose
0
#events
50000
//--------Proton_processes
#particle
proton
//--------
#material
Zr
#energy(MeV)
50
#emax(MeV)
50
#elim(MeV)
1.
#nangle
1
#angles
0.  
#dangle
5.
//--------
#generator
binary
#paw
bic.paw
#run
#generator
bertini
#paw
ber.paw
#run
//--------Exit
#exit
