/process/activate   LowEnRayleigh   gamma
/process/activate   LowEnPhotoElec  gamma
/process/activate   LowEnCompton    gamma
/process/activate   LowEnConversion gamma

/process/inactivate phot            gamma
/process/inactivate compt           gamma
/process/inactivate conv            gamma

/process/activate   LowEnergyIoni   
/process/activate   LowEnBrem       

/process/inactivate eIoni           
/process/inactivate eBrem           

/process/list
