/process/inactivate LowEnRayleigh   gamma
/process/inactivate LowEnPhotoElec  gamma
/process/inactivate LowEnCompton    gamma
/process/inactivate LowEnConversion gamma

/process/activate   phot            gamma
/process/activate   compt           gamma
/process/activate   conv            gamma

/process/inactivate LowEnergyIoni   e-
/process/inactivate LowEnBrem       e-

/process/activate   eIoni           e-
/process/activate   eBrem           e-

/process/list
