# Definition of the physics processes and models
# Define the physics models
/physics/addPhysics LowE_Livermore                      # Electromagnetic model
/physics/addPhysics HPElastic                           # Hadronic elastic model with HP
/physics/addPhysics binary                              # Hadronic inelastic model
/physics/addPhysics binary_ion                          # Hadronic inelastic model for ions
/physics/addPhysics radioactive_decay                   # Radioactive decay

