/control/verbose 2
/vis/verbose warnings

# Open OGLIX viewer
/vis/open OGLIX
# Draw volume
/vis/drawVolume
/vis/viewer/set/autoRefresh false

# Execute testVisSceneAdd.mac
/control/execute testVisSceneAdd.mac

# Execute testVisSet.mac
/control/execute testVisSet.mac

# Fire a e+
/gun/particle e+
/vis/modeling/trajectories/create/drawByCharge
/vis/modeling/trajectories/drawByCharge-0/default/setDrawStepPts true
/vis/modeling/trajectories/drawByCharge-0/default/setStepPtsSize 5
/run/beamOn 1

# printEPS
/vis/ogl/set/printFilename OGLIX-output/visSceneTest
/vis/ogl/printEPS
