/control/verbose 2
/vis/verbose warnings

/vis/open OGL 600x600-0+0

# Disable auto refresh and quieten vis messages whilst scene and
# trajectories are established:
/vis/viewer/set/autoRefresh false
/vis/verbose errors

/vis/drawVolume

/vis/scene/add/trajectories
/vis/modeling/trajectories/create/drawByCharge
/vis/modeling/trajectories/drawByCharge-0/default/setDrawStepPts true
/vis/modeling/trajectories/drawByCharge-0/default/setStepPtsSize 5

# Deselect unwanted volumes...
#/test202/select calorimeter_boxes               false
#/test202/select box_in_box                      false
#/test202/select tracker_tube                    false
#/test202/select displaced_box                   false
#/test202/select Boolean_solids                  false
#/test202/select Tubes_etc                       false
#/test202/select Sphere                          false
#/test202/select Polyhedra                       false
#/test202/select Polycone                        false
#/test202/select Orb                             false
#/test202/select Trapezoid                       false
#/test202/select Elliptical_Tube                 false
#/test202/select Elliptical_Cone                 false
#/test202/select G4Cons                          false
#/test202/select Simple_shared                   false
#/test202/select Boolean_for_logical_volume_test false
#/test202/select Radially_replicated_tube_sector false
#/test202/select tetrahedron                     false
#/test202/select Twisted_Tubs                    false
#/test202/select Twisted_Box                     false
#/test202/select Twisted_Trd                     false
#/test202/select Another_Twisted_Trd             false
#/test202/select G4Paraboloid                    false
#/test202/select G4GenericTrap                   false
#/test202/select Simple_tessellated              false
#/test202/select Simple_union                    false

# Re-establish auto refreshing and verbosity:
/vis/viewer/set/autoRefresh true
/vis/verbose confirmations
