/control/verbose 2
/vis/verbose warnings

/vis/open OGLIX 600x600-0+0

/vis/drawVolume

/vis/scene/add/trajectories
/vis/modeling/trajectories/create/drawByCharge
/vis/modeling/trajectories/drawByCharge-0/default/setDrawStepPts true
/vis/modeling/trajectories/drawByCharge-0/default/setStepPtsSize 5

# Deselect problem volumes...
#/test202/select Elliptical_Cone false
#/test202/select Twisted_Trd false
