# $Id: targtest.mac,v 1.1 2003-10-08 12:32:10 hpw Exp $
#
# Macro file for "exampleN03AH.cc"
# 
# can be run in batch, without graphic
# or interactively: Idle> /control/execute run1.mac
#
# /control/verbose 2
/control/saveHistory
/target/setTgtMat Copper
/target/setTgtThick 5.0 mm
# /target/setTgtRadius 5.0 cm
/target/update 
#
/run/verbose 0
/event/verbose 0
/event/printModulo 1000
/tracking/verbose 0
# 
# 730 MeV proton in the direction (0.,0.,1.)
# 3 events
#
/gun/particle proton
/gun/energy 2 GeV
/run/beamOn 100000
