#
# Macro file for the initialization phase of "TestEm6.cc"
#
# It creates the default geometry (simple absorber cylinder )        
#
/control/verbose 2
/event/setverbose 0
#
/run/initialize
#
/calor/setAbsMat Aluminium
/calor/setAbsThick 0.1 micrometer
/calor/setAbsRad 20 mm
/calor/update
#
/lowenergy/lowlimE 250 eV
/lowenergy/lowlimG 250 eV
/lowenergy/secphotcut 20. keV
#/lowenergy/seceleccut 1 keV
/calor/cutG 1.   micrometer    
/calor/cutE 0.01   micrometer
#
/run/initialize
/run/particle/dumpCutValues
#
/gun/particle e-
#/gun/zvertex -0.16 mum
/gun/energy 500 eV
/tracking/verbose 2
/run/beamOn 1
#
#  PLOT: nb of steps ..........
..........................................

/plots/sethistName geant4.hbook
#

#  PLOT: energy deposit distribution in absorber............................
/plots/setnbinTl 100
/plots/setTllow 0.0 mm
/plots/setTlhigh 500 micrometer 

#  PLOT: energy of transmitted particles (with quantum numbers of the primary)
/plots/setnbinEn 200
/plots/setEnlow 0.0 keV
/plots/setEnhigh 500 eV  

#  PLOT: angle distr. of transmitted particles 
/plots/setnbinTt 200
/plots/setTtlow 0.0 keV
/plots/setTthigh 500 eV 

#  PLOT: energy spectrum of charged secondaries
/plots/setnbinTsec 100
/plots/setTseclow 0.00 keV
/plots/setTsechigh 20  keV 

#  PLOT: energy spectrum of photons escaping the absorber (forward)
/plots/setnbinGamma 100
/plots/setElowGamma 0.0 keV
/plots/setEhighGamma 20 keV
#
/tracking/verbose 0
/run/beamOn 10000









