# $Id: GNUmakefile,v 1.1 2009/11/19 22:41:18 ldesorgh Exp $
# --------------------------------------------------------------
# GNUmakefile for examples module.  Gabriele Cosmo, 06/04/98.
# --------------------------------------------------------------

name := exampleRMC01
G4TARGET := $(name)
G4EXLIB := true

ifndef G4INSTALL
  G4INSTALL = ../../../..
endif

.PHONY: all
all: lib bin


CPPFLAGS +=

include $(G4INSTALL)/config/binmake.gmk
