# $Id: run04.mac,v 1.5 2002-10-14 16:00:08 vnivanch Exp $
#
# Macro file for "TestEm2.cc" 
# (can be run in batch, without graphic)
#
# Fe L = 20 radl  R = 5 radl; electron 30 GeV
#
# EGS4 simulation: Particle Data Group - Phys.Rev.D 50-3 - August94
#
/control/verbose 2
#
/em2/setCut 0.8 mm
/run/initialize
#
/em2/setMat Fe
/em2/setLbin 40 0.5
/em2/setRbin 20 0.25
/em2/update
#
/run/verbose 2
/em2/printModulo 10
#
/gun/particle e-
/gun/energy 30 GeV
/run/beamOn 100


