# $Id: GNUmakefile,v 1.1 2007-06-21 15:25:47 jjacquem Exp $
# $Name: not supported by cvs2svn $
# ===========================================================
#   Makefile for building Geant4Py modules
# ===========================================================
G4PYPATH = ${G4INSTALL}/environments/g4py
include ${G4PYPATH}/config/config.gmk


# python module name
MODULE := ../pyTestEm0

include $(G4PY_INSTALL)/config/g4py.gmk
include $(G4PY_INSTALL)/config/module.gmk
