# $Id: geantino.mac,v 1.3 2009-06-22 13:34:26 maire Exp $
#
# Macro file for "amsEcal.cc"
#
# Geantinos allows to measure nb of radLengths of calorimeter
#
/control/verbose 2
/run/verbose 2
#
/run/initialize
#
/ams/gun/setDefault
/gun/particle geantino
/ams/gun/beam 6 mm	# +- 0.5*beam
#
/ams/histo/setFileName nradl/nradl.182
/ams/histo/setFileType hbook
#
/ams/histo/setHisto 5 100  12. 22. none
#
/ams/event/printModulo 4000
#
/run/beamOn 40000
