# $Id$
#
# Macro file for "amsEcal.cc" 
# (can be run in batch, without graphic)
#
/control/verbose 2
/run/verbose 2
#
/ams/phys/addPhysics  emstandard_local
/ams/phys/setCuts 1 mm
#
/run/initialize
#
/ams/gun/setDefault
/gun/particle proton
/gun/energy 100 GeV
/ams/gun/beam 20 mm
#
/analysis/setFileName mips
#
/analysis/h1/set 1 100  0. 50. MeV		#evis in ecal
/analysis/h1/set 3 20  0. 20. none
/analysis/h1/set 4 20  0. 20. none
#
/run/printProgress 4000
#
/run/beamOn 40000
