#
# Macro file for "Hadr05.cc" 
#
/control/verbose 1
#
/process/em/verbose 0
/process/had/verbose 0

/testhadr/det/setNbOfLayers 1
/testhadr/det/setNbOfAbsor  1
/testhadr/det/setAbsor 1 Aluminium 10 cm
/testhadr/det/setSizeYZ 10 cm
#
/run/setCut 2 cm
#
/control/execute vis.mac
##/run/initialize
#
/globalField/setValue 0 0 10 tesla
#
/testhadr/gun/setDefault
/gun/particle proton
/gun/energy 300 MeV
#
/run/beamOn 1
