# Verbose
#
/control/verbose 2
/tracking/verbose 2
/run/verbose 2

# Create empty scene 
/vis/scene/create

#
/vis/open OGLIX

# Draw scene
/vis/viewer/zoom 1
#/vis/viewer/set/viewpointThetaPhi -50 -60 deg
/vis/viewer/set/viewpointThetaPhi 90 0 deg
#/vis/viewer/set/viewpointThetaPhi 105 165 deg

/vis/viewer/flush
#
# for drawing the tracks
# if too many tracks cause core dump => storeTrajectory 0
#/tracking/storeTrajectory 1
#/vis/scene/endOfEventAction accumulate

/vis/scene/add/trajectories


/gun/position 0.0 0.0 15.0 mm
#/run/beamOn 1
#/run/beamOn 1
#/run/beamOn 1
#if you want add Rotation to detector[deg]
#/mydet/RotateX 10.
#/mydet/RotateY 10.
#if you want abort Run instead of Warning Message
/mydet/AbortRun 1
#if you want to change the detector

#/mydet/SelectDetector Sphere
#/run/beamOn 3000
#/mydet/SelectDetector Shell
#/run/beamOn 3000
#/mydet/SelectDetector Ellipsoid
#/run/beamOn 3000
#/mydet/SelectDetector Tubs
#/run/beamOn 30000
#/mydet/SelectDetector Cons
#/run/beamOn 3000
/mydet/SelectDetector Polycone
/run/beamOn 3000
#/mydet/SelectDetector Polyhedra
#/run/beamOn 3000
#/mydet/SelectDetector Para
#/run/beamOn 3000
#/mydet/SelectDetector Torus
#/run/beamOn 3000
#/mydet/SelectDetector Box
#/run/beamOn 3000
#/mydet/SelectDetector Orb
#/run/beamOn 3000
#/mydet/SelectDetector Trd
#/run/beamOn 3000
#/mydet/SelectDetector Trap
#/run/beamOn 3000
#/mydet/SelectDetector EllipticalTube
#/run/beamOn 3000
#/mydet/SelectDetector EllipticalCone
#/run/beamOn 3000
#/mydet/SelectDetector Hype
#/run/beamOn 3000
#Infinite Loop
##/mydet/SelectDetector Tet
##/run/beamOn 3000
#/mydet/SelectDetector GenericTrap
#/run/beamOn 3000
#/mydet/SelectDetector Paraboloid
#/run/beamOn 3000
#/mydet/SelectDetector TessellatedSolid
#/run/beamOn 3000
#/mydet/SelectDetector ExtrudedSolid
#/run/beamOn 3000
#/mydet/SelectDetector TwistedBox
#/run/beamOn 300
#/mydet/SelectDetector TwistedTrd
#/run/beamOn 300
#/mydet/SelectDetector TwistedTrap
#/run/beamOn 300
#/mydet/SelectDetector TwistedTubs
#/run/beamOn 300
#/mydet/SelectDetector b1Ub2
#/run/beamOn 3000
#/mydet/SelectDetector b1Ib2
#/run/beamOn 3000
#/mydet/SelectDetector b1Sb2
#/run/beamOn 3000


