# Verbose
#
/control/verbose 2
#/tracking/verbose 2
/run/verbose 2

# Create empty scene 
/vis/scene/create

#
/vis/open OGLIX

# Draw scene
/vis/viewer/zoom 1
#/vis/viewer/set/viewpointThetaPhi -50 -60 deg
/vis/viewer/set/viewpointThetaPhi 90 0 deg
#/vis/viewer/set/viewpointThetaPhi 105 165 deg

/vis/viewer/flush
#
# for drawing the tracks
# if too many tracks cause core dump => storeTrajectory 0
#/tracking/storeTrajectory 1
#/vis/scene/endOfEventAction accumulate
#
#/testem/event/drawTracks all
/vis/scene/add/trajectories

#/AXPET/gun/optPhotonPolar -360.0 deg
/gun/position 0.0 0.0 15.0 mm
#/run/beamOn 1
#/run/beamOn 1
#/run/beamOn 1

#if you want to change the detector

/mydet/SelectDetector Sphere
/run/beamOn 30
/mydet/SelectDetector Shell
/run/beamOn 30
/mydet/SelectDetector Ellipsoid
/run/beamOn 30
/mydet/SelectDetector Tubs
/run/beamOn 30
/mydet/SelectDetector Cons
/run/beamOn 30
/mydet/SelectDetector Polycone
/run/beamOn 30
/mydet/SelectDetector Polyhedra
/run/beamOn 30
/mydet/SelectDetector Para
/run/beamOn 30
/mydet/SelectDetector Torus
/run/beamOn 30
/mydet/SelectDetector Box
/run/beamOn 30
/mydet/SelectDetector Orb
/run/beamOn 30

