//---------------------------------------
//        Macro file for test30
//         examine PostStepDoIt 
//        for hadronic physics
//      Created: 13.03.2002 V.Ivanchenko
//--------------------------------------- 
#verbose
0
#events
10000
//--------Proton_processes
#particle
neutron
//--------
#material
Pb
#energy(MeV)
65
#emax(MeV)
80
#elim(MeV)
15.
#nangle
2
#angles
20. 28.   
#nbinsd
40
#dangle
4.
//--------
#generator
LEparametrisation
#paw
par.paw
#run
#generator
preCompound
#paw
prec.paw
#run
#generator
CHIPS
#paw
chips.paw
#run
#generator
kinetic
#paw
kin.paw
#run
//--------Exit
#exit
