//---------------------------------------
//        Macro file for test30
//         examine PostStepDoIt 
//        for hadronic physics
//      Created: 13.03.2002 V.Ivanchenko
//--------------------------------------- 
#verbose
0
#events
1000
//--------Proton_processes
#particle
proton
//--------
#material
Pb
#energy(MeV)
65
#emax(MeV)
80
#elim(MeV)
15.
#nangle
2
#angles
20. 28.   
#dangle
4.
//--------
generator
kinetic
#paw
kin.paw
#run
//--------Exit
#exit
