# - G4hadronic_deex_alt_fermi_breakup module build definition

# Define the Geant4 Module.
geant4_add_module(G4hadronic_deex_alt_fermi_breakup
  PUBLIC_HEADERS
    G4FermiVDecay.hh
    G4FermiParticle.hh
    G4FermiKopylovDecay.hh
    G4FermiRandomizer.hh
    G4FermiIntegerPartition.hh
    G4FermiSingleton.hh
    G4FermiStableFragment.hh
    G4FermiBreakUp.hh
    G4FermiFragmentsStorage.hh
    G4FermiDefaultNuclearMass.hh
    G4FermiUnstableFragment.hh
    G4FermiSplitter.hh
    G4FermiFastNucleiProperties.hh
    G4FermiNucleiProperties.hh
    G4FermiDefaultPoolSource.hh
    G4FermiDataTypes.hh
    G4FermiLogger.hh
    G4FermiPossibleFragment.hh
    G4FermiVNucleiProperties.hh
    G4FermiFragmentPool.hh
    G4FermiCopyMass.hh
    G4FermiPhaseDecay.hh
    G4FermiCache.hh
  SOURCES
    G4FermiFastNucleiProperties.cc
    G4FermiFragmentsStorage.cc
    G4FermiParticle.cc
    G4FermiStableFragment.cc
    G4FermiBreakUp.cc
    G4FermiDefaultPoolSource.cc
    G4FermiIntegerPartition.cc
    G4FermiLogger.cc
    G4FermiSplitter.cc
    G4FermiRandomizer.cc
    G4FermiDataTypes.cc
    G4FermiDefaultNuclearMass.cc
    G4FermiCopyMass.cc
    G4FermiKopylovDecay.cc
    G4FermiUnstableFragment.cc
    G4FermiPossibleFragment.cc)

geant4_module_link_libraries(G4hadronic_deex_alt_fermi_breakup
  PUBLIC
    G4hadronic_deex_fermi_breakup
    G4globman
    G4hadronic_util
    G4hepgeometry
    G4heprandom
  PRIVATE
    G4hadronic_deex_management
    G4partman)
