#
# Macro file for the initialization phase of "TestEm5.cc"
#
# It creates the default geometry (simple absorber box )        
#
/control/verbose 2
#control/saveHistory
/run/verbose 2
#
/run/initialize
#
/calor/setAbsMat Gold      
/calor/setAbsThick 9.658 mum  
/calor/setAbsYZ 10. cm
/calor/update
#
#  hist file name
/plots/sethistName geant4.plot01a
#  PLOT: angle distr. of transmitted particles
/plots/setnbinTh 60
/plots/setThlow 0.0 deg
/plots/setThhigh 30.0 deg
#
/calor/cutG 13.0 micrometer
/calor/cutE 1.12 micrometer
/run/initialize
#
#
/gun/particle e- 
/gun/energy 15.7 MeV
#
/run/beamOn 1000000
#
#


