//---------------------------------------
//        Macro file for test30
//         examine PostStepDoIt 
//        for hadronic physics
//      Created: 13.03.2002 V.Ivanchenko
//--------------------------------------- 
#verbose
0
#events
100000
//--------Proton_processes
#particle
proton
//--------
#material
Al
#energy(MeV)
22.2
#nangle
13
#angles
30. 60. 90. 120. 150.  
#dangle
10.
//--------
#generator
LEparametrisation
#paw
par.paw
run
#generator
preCompound
#paw
prec.paw
run
#generator
CHIPS
#paw
chips.paw
run
#generator
kinetic
#paw
kin.paw
run
//--------Exit
#exit
