/PhysicsList/cut 0.2 mm
/control/verbose 1
/control/saveHistory
/run/verbose 2


/run/initialize
/tracking/storeTrajectory 1

/Phantom/dimension 15. cm
/Phantom/Nvoxels 150
/Phantom/maxStep 0.2 mm

/PhantomSD/dimension 15. cm
/PhantomSD/Nvoxels 150


/Jaws/X1/DistanceFromAxis -5.0 cm
/Jaws/X2/DistanceFromAxis 5.0 cm
/Jaws/Y1/DistanceFromAxis -5.0 cm
/Jaws/Y2/DistanceFromAxis 5.0 cm
/Jaws/update

/energy 6.0 MeV
/sourceType 0.127 MeV

/run/beamOn 1000
