#
# Macro file for "TestEm17.cc"
# (can be run in batch, without graphic)
#
/control/verbose 2
/run/verbose 2
#
/testem/det/setMat Iron
/testem/det/setSize 1 m
#
/testem/phys/addPhysics local
#
/run/setCut 1 mm
#
/run/initialize
#
/process/inactivate muIoni
/process/inactivate muPairProd
/process/inactivate muToMuonPairProd
#
/gun/particle mu+
/gun/energy 10 TeV
#
/testem/histo/setFileName brem
/testem/histo/setHisto 3 100 -10. 0.
#
/run/printProgress 1000
#
/run/beamOn 10000
