#
# Macro file for "TestEm17.cc"
# (can be run in batch, without graphic)
#
/control/verbose 2
/run/verbose 2
#
/testem/det/setMat Iron
/testem/det/setSize 1 m
#
/testem/phys/addPhysics emstandard_opt0
#
/run/setCut 1 mm
#
/run/initialize
#
/process/inactivate muPairProd
/process/inactivate muBrems
#
/gun/particle mu+
/gun/energy 10 TeV
#
/testem/histo/setFileName ioni
/testem/histo/setHisto 1 100 -10. 0.
#
/run/printProgress 1000
#
/run/beamOn 10000
