# -------------------------------------------------------------------
# $Id: GNUmakefile 69157 2013-04-19 14:05:11Z gcosmo $
# -----------
# GNUmakefile 
# -----------

name := microbeam

G4TARGET := $(name)
G4EXLIB := true

ifndef G4INSTALL
  G4INSTALL = ../..
endif

.PHONY: all
all: lib bin

include $(G4INSTALL)/config/binmake.gmk
