#############################################################################*#
#                                                                             #
# initInter.mac                                                               #
# Initialisation macro for interactive mode                                   #
#                                                                             #
###############################################################################
#
/control/verbose 2
/control/saveHistory
#
# Open a viewer
/vis/open
# This opens the default viewer - see examples/basic/B1/vis.mac for a
# more comprehensive overview of options. Also the documentation.
#
# Trajectories: set to 0 if too many
# alternatively use /dmx/drawTracks [none charged noscint all]
/tracking/storeTrajectory 1
#
#
# Camera viewpoint
/vis/drawView  70 -90 0. 0. cm 1.5
#
# Add detector to scene
/vis/drawVolume
#
# Flush visualization
/vis/viewer/update
#
#
# now run macro: gamma.mac, alpha.mac, neutron.mac, sourceAm241.mac


