#############################################################################*#
#                                                                             #
# initInter.mac                                                               #
# Initialisation macro for interactive mode                                   #
#                                                                             #
###############################################################################
#
/control/verbose 2
/control/saveHistory
#
# Create empty scene
/vis/scene/create
#
# Create a scene handler for a specific graphics system
# (Edit the next line(s) to choose another graphic system)
#/vis/open OGLSX
#/vis/open OGLIX
/vis/open OGLSXm
#/vis/open OGLIXm
#/vis/open DANWFILE
#/vis/open Xo
#
# Trajectories: set to 0 if too many
# alternatively use /dmx/drawTracks [none charged noscint all]
/tracking/storeTrajectory 1
#
#
# Camera viewpoint
/vis/drawView  70 -90 0. 0. cm 1.5
#
# Add detector to scene
/vis/drawVolume
#
# Flush visualization
/vis/viewer/update
#
#
# now run macro: gamma.mac, alpha.mac, neutron.mac, sourceAm241.mac


