
#############################################################################*#
#                                                                             #
# initInter.mac                                                               #
# Initialisation macro for interactive mode                                   #
#                                                                             #
###############################################################################

/control/verbose 2
/control/saveHistory
/run/verbose 2

# create empty scene
/vis/scene/create

# Create a scene handler for a specific graphics system
# (Edit the next line(s) to choose another graphic system)
#/vis/open OGLIX
#/vis/open OGLIXm
/vis/open OGLSXm
#/vis/open DAWNFILE
#/vis/open Xo

# Trajectories: set to 0 if too many
# alternatively use /dmx/drawTracks [none charged noscint all]
/tracking/storeTrajectory 1

/vis/drawView  70 -90 0. 0. cm 1.5

/vis/drawVolume

/vis/viewer/update

# now run macro: gamma.mac, alpha.mac, neutron.mac
