#
# Example of interactive redefinition
# of the geometry
#
# this macro can be executed at any time
# during an interactive session:
#
# Idle> /control/execute newgeom.mac
# 
#
/calor/setNbOfLayers 1
#
/calor/setAbsMat Aluminium
/calor/setAbsThick 10. cm
#
/calor/setGapMat Air
/calor/setGapThick  0.1 cm
#
/calor/setSizeYZ   10. cm
#
/calor/update
#
/calor/setField 3 tesla
#
/vis/camera/zoom 1.3
/vis/drawVolume

