#################################################################################
#                                                                              	#
# ESA-CERN GEANT4 RADIOACTIVE DECAY MODULE                                     	#
# VALIDATION TEST NUMBER 6                                                  	#	
# 									      	#
# THIS TEST SHOWS THE DECAYS OF AS-74. 						#
# 										#
#    AS-74 HAS A RATHER COMPLICATED DECAY SCHEME WITH  CHANNELS:                #
#										#
#    BETA-, BETA+ AND EC							#
#										#
# F LEI, DERA FARNBOROUGH, 8 MARCH 2000                                        	#
#                                                                              	#
#################################################################################
#
# NOTE THAT THE FIRST RECORD IN THIS MACROFILE IS THE OUTPUT LOG-FILE NAME.
# NOW SET VERBOSE LEVELS FOR RUN, EVENT, TRACKING AND THE RDM PROCESS.
#
/run/filename tav.log
/run/verbose 0
/event/verbose 0
/tracking/verbose 0

/grdm/analogueMC 1
/grdm/verbose 0

/grdm/nucleusLimits 19 40 19 40 
#/grdm/ion 74 33 0
/gps/type Volume
/gps/shape Sphere
/gps/radius 0.5 m
#/gps/halfz 0.5m

/gps/confine physicalMirror_Phys
#/gps/confine physicalXe_l2base_Phys
#physicalPMT_no_1
#/gps/confine physicalPMT_no_1
#logical_PMT_Glass_body
/gps/particle neutron
#/gps/ion 19 40 0 0
#/gun/energy 0 MeV
#/gps/centre 0. 0. 20. cm
/gps/energytype Mono
/gps/monoenergy 2 MeV
/grdm/allVolumes
#/grdm/noVolumes
#/grdm/selectVolume logical_PMT_Glass_body
/run/beamOn 11



