#################################################################################
#                                                                              	#

# THIS TEST TO DEMONSTRATE THAT ISOTOPES GENERATED IN HADRONIC                  #
# PROCESSES CAN BE TREATED BY THE RDM.					        # 
#                                                                              	#
#################################################################################
#
#
/exrdm/phys/SelectPhysics Hadron
/geometry/material/add NaI Na-I 3.67
/exrdm/det/setTargetMate NaI
# material definitions has to be done before /run/initilalize
/histo/fileName neutron-10ev
/run/initialize
/run/setCutForRegion Target 10 cm
/run/setCutForRegion Detector 50 cm
/grdm/verbose 0
/grdm/noVolumes
/grdm/selectVolume Target

/tracking/verbose 0
/gps/particle neutron 
/gps/energy 10 eV
/run/beamOn 1000




