#/exrdm/phys/SelectPhysics LHEP_BIC_HP
/run/initialize
/run/setCut 1000 cm
/run/setCutForRegion Target 10 cm
/run/setCutForRegion Detector 50 cm

# vis
/vis/open VRML2FILE
/vis/scene/create 
/vis/viewer/reset
/vis/viewer/zoom 20.
/vis/viewer/set/viewpointThetaPhi 90. 180.
/vis/viewer/set/style wireframe
/vis/drawVolume
/vis/scene/endOfEventAction accumulate	
/tracking/storeTrajectory 1	
#

/gps/particle proton
/tracking/verbose 1
/run/beamOn 10



