# $Id: vis.mac,v 1.2 2003/06/16 17:06:44 dressel Exp $
# -------------------------------------------------------------------
# GEANT4 tag $Name: geant4-06-00 $
# -------------------------------------------------------------------


/vis/scene/create
/vis/open OGLIX
/vis/viewer/set/style  w
/vis/viewer/flush
/vis/viewer/set/viewpointThetaPhi -70 -20
/tracking/storeTrajectory 1
/vis/scene/endOfEventAction accumulate
