# - G4hadronic_inclxx_utils module build definition

# Define the Geant4 Module.
geant4_add_module(G4hadronic_inclxx_utils
  PUBLIC_HEADERS
    G4INCLAllocationPool.hh
    G4INCLBook.hh
    G4INCLConfig.hh
    G4INCLConfigEnums.hh
    G4INCLEventInfo.hh
    G4INCLFinalState.hh
    G4INCLGeant4Compat.hh
    G4INCLGeant4Random.hh
    G4INCLGlobalInfo.hh
    G4INCLGlobals.hh
    G4INCLHashing.hh
    G4INCLHFB.hh
    G4INCLHornerFormEvaluator.hh
    G4INCLIAvatar.hh
    G4INCLIChannel.hh
    G4INCLIFunction1D.hh
    G4INCLInterpolationTable.hh
    G4INCLIntersection.hh
    G4INCLInvFInterpolationTable.hh
    G4INCLIRandomGenerator.hh
    G4INCLLogger.hh
    G4INCLNaturalIsotopicDistributions.hh
    G4INCLNuclearMassTable.hh
    G4INCLParticle.hh
    G4INCLParticleSpecies.hh
    G4INCLParticleTable.hh
    G4INCLParticleType.hh
    G4INCLRandom.hh
    G4INCLRandomSeedVector.hh
    G4INCLRanecu.hh
    G4INCLRanecu3.hh
    G4INCLRootFinder.hh
    G4INCLThreeVector.hh
    G4INCLUnorderedVector.hh
    G4INCLVersion.hh
  SOURCES
    G4INCLConfig.cc
    G4INCLConfigVersion.cc
    G4INCLEventInfo.cc
    G4INCLFinalState.cc
    G4INCLGlobals.cc
    G4INCLHFB.cc
    G4INCLIAvatar.cc
    G4INCLIChannel.cc
    G4INCLIFunction1D.cc
    G4INCLInterpolationTable.cc
    G4INCLInvFInterpolationTable.cc
    G4INCLLogger.cc
    G4INCLNaturalIsotopicDistributions.cc
    G4INCLNuclearMassTable.cc
    G4INCLParticle.cc
    G4INCLParticleSpecies.cc
    G4INCLParticleTable.cc
    G4INCLRandom.cc
    G4INCLRandomSeedVector.cc
    G4INCLRanecu.cc
    G4INCLRanecu3.cc
    G4INCLRootFinder.cc)

geant4_module_link_libraries(G4hadronic_inclxx_utils
  PUBLIC
    G4globman
    G4heprandom
    G4partman)
