/run/beamOn 5000
/control/shell mv doseSD.out /local/pablo/risultatiGeant4/doseSD1.out
/control/shell mv matrice.out /local/pablo/risultatiGeant4/matrice1.out

/run/beamOn 5000
/control/shell mv doseSD.out /local/pablo/risultatiGeant4/doseSD2.out
/control/shell mv matrice.out /local/pablo/risultatiGeant4/matrice2.out

/run/beamOn 5000
/control/shell mv doseSD.out /local/pablo/risultatiGeant4/doseSD3.out
/control/shell mv matrice.out /local/pablo/risultatiGeant4/matrice3.out

/run/beamOn 5000
/control/shell mv doseSD.out /local/pablo/risultatiGeant4/doseSD4.out
/control/shell mv matrice.out /local/pablo/risultatiGeant4/matrice4.out


/run/beamOn 5000
/control/shell mv doseSD.out /local/pablo/risultatiGeant4/doseSD5.out
/control/shell mv matrice.out /local/pablo/risultatiGeant4/matrice5.out

/run/beamOn 5000
/control/shell mv doseSD.out /local/pablo/risultatiGeant4/doseSD6.out
/control/shell mv matrice.out /local/pablo/risultatiGeant4/matrice6.out


/run/beamOn 5000
/control/shell mv doseSD.out /local/pablo/risultatiGeant4/doseSD7.out
/control/shell mv matrice.out /local/pablo/risultatiGeant4/matrice7.out


/run/beamOn 5000
/control/shell mv doseSD.out /local/pablo/risultatiGeant4/doseSD8.out
/control/shell mv matrice.out /local/pablo/risultatiGeant4/matrice8.out


/run/beamOn 5000
/control/shell mv doseSD.out /local/pablo/risultatiGeant4/doseSD9.out
/control/shell mv matrice.out /local/pablo/risultatiGeant4/matrice9.out


/run/beamOn 5000
/control/shell mv doseSD.out /local/pablo/risultatiGeant4/doseSD10.out
/control/shell mv matrice.out /local/pablo/risultatiGeant4/matrice10.out

/run/beamOn 5000
/control/shell mv doseSD.out /local/pablo/risultatiGeant4/doseSD11.out
/control/shell mv matrice.out /local/pablo/risultatiGeant4/matrice11.out

/run/beamOn 5000
/control/shell mv doseSD.out /local/pablo/risultatiGeant4/doseSD12.out
/control/shell mv matrice.out /local/pablo/risultatiGeant4/matrice12.out

/run/beamOn 5000
/control/shell mv doseSD.out /local/pablo/risultatiGeant4/doseSD13.out
/control/shell mv matrice.out /local/pablo/risultatiGeant4/matrice13.out

/run/beamOn 5000
/control/shell mv doseSD.out /local/pablo/risultatiGeant4/doseSD14.out
/control/shell mv matrice.out /local/pablo/risultatiGeant4/matrice14.out

/run/beamOn 5000
/control/shell mv doseSD.out /local/pablo/risultatiGeant4/doseSD15.out
/control/shell mv matrice.out /local/pablo/risultatiGeant4/matrice15.out
