############################################################################
#
# PHYSICS LIST:
# ============= 
#
#  Decay:
#  ------
#    * Decay of all unstable particles
#
#
#  Electromagnetic Physics
#  -----------------------
#    * Livermore-based models for photons, electrons
#    * Ziegler77-based models for charged hadrons, ions 
#    * Standard models for positrons, muons 
#
# 
#  Hadronic Physics (elastic)
#  --------------------------
#    * LEP elastic scattering model for hadrons (protons, 
#      neutrons, pions), ions (deuterons, tritons, alphas)
#
#
#  Hadronic Physics (inelastic)
#  ----------------------------
#    * LEP model for protons, neutrons
#    * Fission and capture models for neutrons
#    * LEP model for ions (deuterons, tritons, alphas)
#    * LEP model for pions (pions+, pions-)
#
#
#  Hadronic Physics (inelastic)
#  ----------------------------
#    * Capture model for muons-
#
##############################################################################


####################
# VERBOSITY LEVELS #
####################

/control/verbose 1
/tracking/verbose 0
/run/verbose 0
/event/verbose 0


###########
# PHYSICS #
###########

###  A) EM PHYSICS AND DECAY

/physics/addPhysics Decay
/physics/addPhysics EM-Photon-EPDL
/physics/addPhysics EM-Electron-EEDL
/physics/addPhysics EM-Positron-Standard
/physics/addPhysics EM-HadronIon-LowEZiegler1977
/physics/addPhysics EM-Muon-Standard

###  B) HADRONIC PHYSICS

/physics/addPhysics HadronicEl-HadronIon-LElastic
/physics/addPhysics HadronicInel-ProtonNeutron-LEP
/physics/addPhysics HadronicInel-Ion-LEP
/physics/addPhysics HadronicInel-Pion-LEP
/physics/addPhysics HadronicAtRest-MuonMinus-Capture


##############################
# BEAM LINE SETTINGS AND RUN #
##############################

/run/initialize

###  IF YOU WANT A RANGE SHIFTER PLEASE CHANGE
###  THE FOLLOWIG PARAMETERS
###  SETTING FOR THE RANGE SHIFTER

#/beamLine/RangeShifter/thickness 4 cm
#/beamLine/RangeShifter/RSMat Water

/run/beamOn 200



