#----------------------------------------------------------------------------
# MACRO FILE FOR THE VISUALIZATION OF THE
# HADRONTHERAPY EXAMPLE USING THE OPENGL LIBRARIES
#
#
# THIS MACRO ILLUSTRATES THE POSSIBILITY
# FOR THE USER TO 
#
# 1. Insert a range shifter of PMMA (default is air i.e. no range shifter!);
# 2. Define the thickness of the range shifter; 
# 
#
# NOTE THAT THE MODULATOR MATERIAL IS POLTMETHYLMETHACRILATE 
# (PMMA) FOR DEFAULT. IF ONE WANT CARRY OUT A SIMULATION WITHOUT 
# THE MODULATOR HE/SHE MUST SET "Air" the <<ModMater>> in the
# <<GetMater>> function of the HadrontherapyModulator.cc class
#
# THEN THE USER CAN RUN HIS/HER SIMULATION 
#
# LOOKING ON THE HELP OF THE IDLE FOR HOW TO CHANGE OTHE TOPIC FEATURES
# OF THE BEAM LINE.
# ADDITIONAL INFORMATIONS ON THE MESSENGER AVAILABLE CAN BE FOUND
# INSIDE THE HADRONTHERAPY DOCUMENTATION (http://www.ge.infn.it/geant4/examples/).
# 
# ANYWAY SEND ME AN E-MAIL FOR ANY QUESTION: cirrone@lns.infn.it.   
#------------------------------------------------------------------------------

/control/verbose 1
/tracking/verbose 0
/run/verbose 0
/event/verbose 0

# SETTING FOR THE PHYSICS MODELS
/physics/addPhysics Decay
/physics/addPhysics EM-Photon-Standard
/physics/addPhysics EM-Electron-Standard
/physics/addPhysics EM-Positron-Standard
/physics/addPhysics EM-HadronIon-Standard
/physics/addPhysics EM-Muon-Standard
/physics/addPhysics HadronicEl-HadronIon-LElastic
/physics/addPhysics HadronicInel-ProtonNeutron-LEP
/physics/addPhysics HadronicInel-Ion-LEP
/physics/addPhysics HadronicInel-Pion-LEP
/physics/addPhysics HadronicAtRest-MuonMinus-Capture

/run/initialize

/vis/open DAWNFILE
/vis/drawVolume
/vis/viewer/reset 
/vis/viewer/zoom              1.5
/vis/viewer/set/viewpointThetaPhi 70 20

/tracking/storeTrajectory 1
# SET OF THE VISUALISATION CHARACTERISTICS
#/vis/scene/create
#/vis/open OGLIX
#/vis/viewer/flush

#/vis/viewer/set/viewpointThetaPhi 0 180 deg
#/vis/viewer/zoom 8
#/vis/viewer/pan -90  80 cm
#/tracking/storeTrajectory 1
#/vis/scene/endOfEventAction accumulate
#/vis/specify RODetectorLog 1
#/vis/viewer/update



# SETTING FOR THE RANGE SHIFTER 
#/beamLine/RangeShifter/thickness 0.01 mm
#/beamLine/RangeShifter/RSMat Air
#/tracking/verbose 1
/vis/viewer/flush
/run/beamOn 10000
