//---------------------------------------
//        Macro file for test30
//         examine PostStepDoIt 
//        for hadronic physics
//      Created: 13.03.2002 V.Ivanchenko
//--------------------------------------- 
#verbose
0
#events
20000
//--------Proton_processes
#particle
proton
//--------
#material
Pb
#energy(MeV)
585.
#elim(MeV)
2.
#emaxpi(MeV)
250.
#emax(MeV)
600.
#nbinse
200
#nbinsd
80
#nbinspi
25
#nangle
5
#angles
30. 60. 90. 120. 150.
#dangle
10.
#nanglepi
5
#anglespi
22.5 45. 60. 90. 135.
//--------
#generator
kinetic
#paw
kin.paw
#run
//--------Exit
#exit
