// This code implementation is the intellectual property of
// the RD44 GEANT4 collaboration.
//
// By copying, distributing or modifying the Program (or any work
// based on the Program) you indicate your acceptance of this statement,
// and all its terms.
//
// $Id: schema.h,v 2.0 1998/07/02 17:03:56 gunter Exp $
// GEANT4 tag $Name: geant4-00 $
//
#ifndef  SCHEMA_H
#define  SCHEMA_H
// This file was generated by fedex_plus.  You probably don't want to edit
// it since your modifications will be lost if fedex_plus is used to
// regenerate it.
/*  */
#ifdef __O3DB__
#include <OpenOODB.h>
#endif

#include <sdai.h>


#include <Registry.h>

#include <STEPaggregate.h>

#include <STEPentity.h>

#include <STEPundefined.h>
extern void SchemaInit (Registry &);
#include <SdaiCONFIG_CONTROL_DESIGN.h> 
extern void SdaiCONFIG_CONTROL_DESIGNInit (Registry & r);
#endif
