

//



//
// $Id: schema.h,v 1.2 1999-05-21 20:20:43 japost Exp $
// GEANT4 tag $Name: not supported by cvs2svn $
//
#ifndef  SCHEMA_H
#define  SCHEMA_H
// This file was generated by fedex_plus.  You probably don't want to edit
// it since your modifications will be lost if fedex_plus is used to
// regenerate it.
/*  */
#ifdef __O3DB__
#include <OpenOODB.h>
#endif

#include <sdai.h>


#include <Registry.h>

#include <STEPaggregate.h>

#include <STEPentity.h>

#include <STEPundefined.h>
extern void SchemaInit (Registry &);
#include <SdaiCONFIG_CONTROL_DESIGN.h> 
extern void SdaiCONFIG_CONTROL_DESIGNInit (Registry & r);
#endif
