#
# Macro file for the initialization phase of "TestEm5.cc"
#
# It creates the default geometry (simple absorber cylinder )        
#
/control/verbose 2
#control/saveHistory
/run/verbose 2
#
#  hist file name
/plots/sethistName geant4.plot21
#  PLOT: gamma energy at exit   
/plots/setnbinGamma 80
/plots/setElowGamma  0.1  MeV
/plots/setEhighGamma 1. GeV
#
/run/initialize
#
/calor/setAbsMat Aluminium 
/calor/setAbsThick 5.30  mm  
/calor/setAbsRad 100.0 mm
/calor/update
#
/calor/cutG 1.00 mm
/calor/cutE 5.0 micrometer
/run/initialize
/run/particle/dumpCutValues
#
#
/gun/particle e- 
/gun/energy 25. GeV
#
/run/beamOn 100000
#
#


