//---------------------------------------
//        Macro file for test30
//         examine PostStepDoIt 
//        for hadronic physics
//      Created: 13.03.2002 V.Ivanchenko
//--------------------------------------- 
#verbose
0
#events
20000
//--------Proton_processes
#particle
proton
//--------
#material
C
#energy(MeV)
800.
#sigmae(MeV)
1.5
#elim(MeV)
2.
#nbinse
200
#nbinsd
80
#nangle
5
#angles
7.5 30. 60. 120. 150.
#dangle
10.
//--------
#generator
kinetic
#paw
kin.paw
#run
//---------Exit
#exit
