###################################################
# Visualization of detector geometry and events  
###################################################

# create empty scene
/vis/scene/create

# Create a scene handler for a specific graphics system
/vis/open OGLIX

# draw scene
/vis/viewer/zoom 1.5
#/vis/viewer/set/viewpointThetaPhi 45 45 deg
/vis/viewer/set/viewpointThetaPhi 90 -25 deg
#/vis/viewer/flush
/vis/drawVolume

#if you want to see trajectories and hits points
/vis/scene/add/trajectories
/vis/modeling/trajectories/create/drawByCharge
/vis/modeling/trajectories/drawByCharge-0/default/setDrawStepPts true
/vis/modeling/trajectories/drawByCharge-0/default/setStepPtsSize 5

#DrawSurface Points
/rndm/numPoints 100000

# (if you prefer not refreshing each event, uncomment next line)
# /vis/scene/endOfEventAction accumulate

#hard coded position and direction for gun
#/gun/position 400 0 -0.1 mm
#/gun/direction  0 0 1

#if you want make a run with particle

#/run/beamOn 1

#if you want to change the detector

#/mydet/SelectDetector Polycone

#if you want to change number of Points
#/rndm/numPoints 100

#to draw Points On the Surface
/run/beamOn 1
/mydet/SelectDetector Sphere
/run/beamOn 1
/mydet/SelectDetector Shell
/run/beamOn 1
/mydet/SelectDetector Ellipsoid
/run/beamOn 1
/mydet/SelectDetector Tubs
/run/beamOn 1
/mydet/SelectDetector Cons
/run/beamOn 1
/mydet/SelectDetector Polycone
/run/beamOn 1
/mydet/SelectDetector Polyhedra
/run/beamOn 1
/mydet/SelectDetector Para
/run/beamOn 1
/mydet/SelectDetector Torus
/run/beamOn 1
/mydet/SelectDetector Box
/run/beamOn 1
/mydet/SelectDetector Orb
/run/beamOn 1
/mydet/SelectDetector EllipticalTube
/run/beamOn 1
/mydet/SelectDetector EllipticalCone
/run/beamOn 1
/mydet/SelectDetector Hype
/run/beamOn 1
/mydet/SelectDetector Trap
/run/beamOn 1
/mydet/SelectDetector Trd
/run/beamOn 1
#Infinite Loop
#/mydet/SelectDetector Tet
#/run/beamOn 1
/mydet/SelectDetector GenericTrap
/run/beamOn 1
/mydet/SelectDetector Paraboloid
/run/beamOn 1
/mydet/SelectDetector TessellatedSolid
/run/beamOn 1
/mydet/SelectDetector ExtrudedSolid
/run/beamOn 1
/mydet/SelectDetector TwistedBox
/run/beamOn 1
/mydet/SelectDetector TwistedTrd
/run/beamOn 1
/mydet/SelectDetector TwistedTrap
/run/beamOn 1
/mydet/SelectDetector TwistedTubs
/run/beamOn 1
/mydet/SelectDetector b1Ub2
/run/beamOn 1
/mydet/SelectDetector b1Ib2
/run/beamOn 1
/mydet/SelectDetector b1Sb2
/run/beamOn 1


