/run/initialize

/vis/open OGLSX
/vis/viewer/set/viewpointThetaPhi -79.9999 90
/vis/viewer/set/style s
/vis/viewer/set/lineSegmentsPerCircle 100
/vis/drawVolume
/vis/scene/add/axes
/vis/scene/endOfEventAction accumulate
/tracking/storeTrajectory 1

/tracking/verbose 1

# /gps/verbose 1
# /gps/particle gamma
# /gps/energy 40.0 keV
# /gps/pos/type Plane
# /gps/pos/shape Annulus
# /gps/pos/inner_radius 9. mm
# /gps/pos/radius 10. mm
# /gps/pos/centre 0. 0. 10. cm
# /gps/ang/type cos
# /gps/ang/mintheta    0. deg
# /gps/ang/maxtheta   180. deg
# /gps/ang/minphi  0. deg
# /gps/ang/maxphi  360. deg

/run/beamOn 30


