# $Id: GNUmakefile,v 1.5 2002-12-09 10:57:10 gcosmo Exp $
# --------------------------------------------------------------
# GNUmakefile for examples module.  Gabriele Cosmo, 06/04/98.
# --------------------------------------------------------------

name := test07
G4TARGET := $(name)
G4EXLIB := true

ifndef G4INSTALL
  G4INSTALL = ../..
endif

.PHONY: all
 
all: lib bin

include $(G4INSTALL)/config/binmake.gmk
