# G.A.P.Cirrone
#
# Macro file recommended for the use with ion beams 
# Both native Geant4 physic lists and 'local' physics are used
# 

#########################
# Set of the verboses 
#
/control/verbose 1
/tracking/verbose 0
/run/verbose 0
/event/verbose 0
##########################
# Set of the physic models
#
/physic/addPhysics emstandard_opt3                     # Electromagnetic model    (Geant4 native physic list)
/physic/addPhysics elastic                             # Hadronic elastic model   (Geant4 native physic list)
/physic/addPhysics binary                              # Hadronic inelastic model for proton and neutron (Geant4 native physic list)
/physic/addPhysics local_ion_ion_inelastic             # Hadronic inelastic model for ions (local physic list)

#Alternatively to *local_ion_ion_inelastic* the native "binary-ion" can be also used

##########################
# Initialisation procedure
#
/run/initialize

##########################
# Visualisation 
#
/vis/scene/create
/vis/open OGLIX
/vis/viewer/flush
/vis/viewer/set/viewpointThetaPhi 20 180 deg
/vis/viewer/zoom 1
/vis/viewer/pan -10  0 cm
/tracking/storeTrajectory 1
/vis/scene/endOfEventAction accumulate
#/vis/specify RODetectorLog 1
/vis/viewer/update

##########################
# Set here the cut and the step max for the tracking. 
# Suggested values of cut and step:
#
/physic/setCuts 0.01 mm
/Step/waterPhantomStepMax 0.01 mm 


#########################
# Set the primary particle type,
# energy and position along the X direction
#
/gun/particle ion
/gun/ion 6 12 6

/beam/energy/meanEnergy 744 MeV
/beam/energy/sigmaEnergy 3 MeV
/beam/position/Xposition -300 mm


#########################
# Start of the run
#
/run/beamOn 20000
