
# ---------------------------------------------------------
# THIS MACRO PERMIT TO RECONSTRUCT THE SPREAD OUT BRAGG PEAK
# MODULATING THE PROTON BEAM ENERGY BY MEANS OF A ROTATING
# MODULATOR WHEEL.
# HERE THE WHEEL IS ROTATED OF 1 DEGREE AT EACH RUN AND 
# ONE THOUSAND PROTON HYSTORIES ARE SIMULATED IN EACH 
# RUN
# IN ORDER TO INCREASE THE RESOLUTION MORE EVENT CAN ADDED
# OR A SMALLER ANGLE CAN BE CHOSEN.
# 
# NOTE THAT THE MODULATOR MATERIAL IS AIR FOR DEFAULT.
# IF ONE WANT CARRY OUT A SIMULATION WITH
# THE MODULATOR HE/SHE MUST MODIFY  "HadrontherapyModulator.cc"
# AND SET the <<ModMater>> TO "PMMA".
#
# USERS SHOULD GIVE A LOOK TO THE HELP OF THE IDLE TO KNOW
# THE ACTIVATED MESSSENGERS FOR THE GEOMETRY
#
# 
# ANYWAY SEND ME AN E-MAIL FOR ANY QUESTION: cirrone@lns.infn.it.   
# --------------------------------------------------------------------------------  
#########################
# Set of the verboses 
#
/control/verbose 1
/tracking/verbose 0
/run/verbose 0
/event/verbose 0

##########################
# Set of the physic models
#

/Physics/addPhysics emstandard_opt3                     # Electromagnetic model
/Physics/addPhysics Em_extra_physics			
/Physics/addPhysics Elastic                             # Hadronic elastic model
/Physics/addPhysics decay
/Physics/addPhysics radioactive_decay
/Physics/addPhysics Stopping_physics
/Physics/addPhysics Neutron_tracking_cut
/Physics/addPhysics binary                              # Hadronic inelastic model

#/Physics/addPhysics local_ion_ion_inelastic            # Optional Hadronic inelastic model for ions (local physic list)
 
##########################
# Initialisation procedure
#
/run/initialize

##########################
# Visualisation 
#
/vis/scene/create
/vis/open OGLI
/vis/viewer/flush
/vis/viewer/set/viewpointThetaPhi 50 130 deg
/vis/viewer/zoom 3.5
/vis/viewer/pan -60  40 cm
/vis/scene/add/trajectories
/vis/viewer/update
/vis/scene/add/trajectories
/vis/scene/endOfEventAction accumulate
#########################
# Set the primary particle type,
# energy and position along the X direction
#
/gun/particle proton

/beam/energy/meanEnergy 62 MeV
/beam/energy/sigmaEnergy 400 keV
/beam/position/Xposition -3000 mm

##########################
# Set here the cut and the step max for the tracking. 
# Suggested values of cut and step:
#
/Physics/setCuts 0.1 mm
/Step/waterPhantomStepMax 0.01 mm 


# IF YOU WANT A RANGE SHIFTER PLEASE CHANGE
# THE FOLLOWIG PARAMETERS
# SETTING FOR THE RANGE SHIFTER

/beamLine/RangeShifter/RSMat Air
/beamLine/RangeShifter/thickness 1 cm


# START OF THE MODULATOR ROTATION
# IT CONSISTS IN A COMPLETE ROTATION 
# OF THE WHEEL (360 DEG)

# Running in loop 
/control/alias initialValue 0
/control/alias   finalValue 359
/control/alias     stepSize 1
/control/loop macro/modulator.loop counterName {initialValue} {finalValue} {stepSize}
