############################################################################
#
#  This example macro file provides an overview of all possible physics
#  options available in the Hadrontherapy advanced example. A user can 
#  create his own physics list by combining different physics constructors. 
#
############################################################################
#
#  Summary of available physics options and associated macro commands: 
#
#  Commands are arranged by the type of interactions and the different
#  particles.
#
#  NOTE: For a given type of physics processes and a given particle ONLY ONE
#  physics constructor should be activated (the different options are
#  indicated by "Option X", where in some cases only one option exists).
#
#  To create a complete physics list, a physics constructor must be
#  activated for each subpoint (A,B,C,...) of each of the different physics
#  interactions (I-V).
#  
#  Below the overview one can find an example set of macro commands for 
#  activating physics constructors, where alternative options are also
#  specified (as comments).
#
#
#  I) Decay:
#  ---------
#    A. Unstable particles
#        Option 1: Decay model
#                  Macro command: /physics/addPhysics Decay
#
#
#  II) Electromagnetic Physics
#  ---------------------------
#    A. Photons
#        Option 1: Livermore-based models (Low-energy package)
#                  Macro command: /physics/addPhysics EM-Photon-EPDL
#        Option 2: Penelope-like models (Low-energy package)
#                  Macro command: /physics/addPhysics EM-Photon-Penelope
#        Option 3: Standard models (Standard package)
#                  Macro command: /physics/addPhysics EM-Photon-Standard
#
#    B. Electrons
#        Option 1: Livermore-based models (Low-energy package)
#                  Macro command: /physics/addPhysics EM-Electron-EEDL
#        Option 2: Penelope-like models (Low-energy package)
#                  Macro command: /physics/addPhysics EM-Electron-Penelope
#        Option 3: Standard models (Standard package)
#                  Macro command: /physics/addPhysics EM-Electron-Standard
#
#    C. Charged hadrons, ions 
#        Option 1: ICRU49-based models (Low-energy package)
#                  Macro command: /physics/addPhysics EM-HadronIon-LowE
#        Option 2: Ziegler77-based models (Low-energy package)
#                  Macro command: /physics/addPhysics EM-HadronIon-LowEZiegler1977
#        Option 3: Ziegler85-based models (Low-energy package)
#                  Macro command: /physics/addPhysics EM-HadronIon-LowEZiegler1985
#        Option 4: Standard models (Standard package)
#                  Macro command: /physics/addPhysics EM-HadronIon-Standard
#
#    D. Positrons
#        Option 1: Penelope-like models (Low-energy package)
#                  Macro command: /physics/addPhysics EM-Positron-Penelope
#        Option 2: Standard models (Standard package)
#                  Macro command: /physics/addPhysics EM-Positron-Standard
#
#    E. Muons
#        Option 1: Standard models (Standard package)
#                  Macro command: /physics/addPhysics EM-Muon-Standard
# 
#
#  III) Hadronic Physics (elastic)
#  -------------------------------
#    A. Hadrons (protons, neutrons, pions), ions (deuterons, tritons, alphas)
#        Option 1: LEP elastic scattering model 
#                  Macro command: /physics/addPhysics HadronicEl-HadronIon-LElastic
#        Option 2: Bertini model (hadrons), LEP model (ions)
#                  Macro command: /physics/addPhysics HadronicEl-HadronIon-Bert
#        Option 3: UHadronElasticProcess
#                  Macro command: /physics/addPhysics HadronicEl-HadronIon-UElastic
#        Option 4: CHIPS (protons, neutrons), LEP model (other hadrons, ions)
#                  Macro command: /physics/addPhysics HadronicEl-HadronIon-QElastic
#
#
#  IV) Hadronic Physics (inelastic)
#  --------------------------------
#    A. Protons, neutrons
#        Option 1: LEP model
#                  Macro command: /physics/addPhysics HadronicInel-ProtonNeutron-LEP       
#        Option 2: Precompound model (default evaporation)
#                  Macro command: /physics/addPhysics HadronicInel-ProtonNeutron-Prec          
#        Option 3: Precompound model (GEM evaporation)
#                  Macro command: /physics/addPhysics HadronicInel-ProtonNeutron-PrecGEM          
#        Option 4: Precompound model (default evaporation, Fermi break-up)
#                  Macro command: /physics/addPhysics HadronicInel-ProtonNeutron-PrecFermi         
#        Option 5: Precompound model (GEM evaporation, Fermi break-up)
#                  Macro command: /physics/addPhysics HadronicInel-ProtonNeutron-PrecGEMFermi         
#        Option 6: Bertini model
#                  Macro command: /physics/addPhysics HadronicInel-ProtonNeutron-Bert         
#        Option 7: Binary cascade model
#                  Macro command: /physics/addPhysics HadronicInel-ProtonNeutron-Bin        
#
#    B. Pions
#        Option 1: LEP model
#                  Macro command: /physics/addPhysics HadronicInel-Pion-LEP       
#        Option 2: Bertini model
#                  Macro command: /physics/addPhysics HadronicInel-Pion-Bert       
#        
#    C. Ions (deuterons, tritons, alphas)
#        Option 1: LEP model
#                  Macro command: /physics/addPhysics HadronicInel-Ion-LEP       
#
#
#  V) Hadronic Physics (at rest)
#  -----------------------------
#    A. Muons-
#        Option 1: Muon Minus Capture model
#                  Macro command: /physics/addPhysics HadronicAtRest-MuonMinus-Capture 
#
#
#
##############################################################################


####################
# VERBOSITY LEVELS #
####################

/control/verbose 1
/tracking/verbose 0
/run/verbose 0
/event/verbose 0


###########
# PHYSICS #
###########

/physics/addPhysics Decay

/physics/addPhysics EM-Photon-EPDL
### Alternatively:
### /physics/addPhysics EM-Photon-Penelope
### /physics/addPhysics EM-Photon-Standard

/physics/addPhysics EM-Electron-EEDL
### Alternatively:
### /physics/addPhysics EM-Electron-Penelope
### /physics/addPhysics EM-Electron-Standard

/physics/addPhysics EM-HadronIon-LowE
### Alternatively:
### /physics/addPhysics EM-HadronIon-LowEZiegler1977
### /physics/addPhysics EM-HadronIon-LowEZiegler1985
### /physics/addPhysics EM-HadronIon-Standard

/physics/addPhysics EM-Positron-Penelope
### Alternatively:
### /physics/addPhysics EM-Positron-Standard

/physics/addPhysics EM-Muon-Standard

/physics/addPhysics HadronicEl-HadronIon-LElastic
### Alternatively:
### /physics/addPhysics HadronicEl-HadronIon-Bert
### /physics/addPhysics HadronicEl-HadronIon-UElastic
### /physics/addPhysics HadronicEl-HadronIon-QElastic

/physics/addPhysics HadronicInel-ProtonNeutron-LEP   
### Alternatively:
### /physics/addPhysics HadronicInel-ProtonNeutron-Prec          
### /physics/addPhysics HadronicInel-ProtonNeutron-PrecGEM          
### /physics/addPhysics HadronicInel-ProtonNeutron-PrecFermi         
### /physics/addPhysics HadronicInel-ProtonNeutron-PrecGEMFermi         
### /physics/addPhysics HadronicInel-ProtonNeutron-Bert         
### /physics/addPhysics HadronicInel-ProtonNeutron-Bin  
      
/physics/addPhysics HadronicInel-Pion-LEP       
### Alternatively:
### /physics/addPhysics HadronicInel-Pion-Bert       

/physics/addPhysics HadronicInel-Ion-LEP       

/physics/addPhysics HadronicAtRest-MuonMinus-Capture 


##############################
# BEAM LINE SETTINGS AND RUN #
##############################

/run/initialize

###  IF YOU WANT A RANGE SHIFTER PLEASE CHANGE
###  THE FOLLOWIG PARAMETERS
###  SETTING FOR THE RANGE SHIFTER

#/beamLine/RangeShifter/thickness 4 cm
#/beamLine/RangeShifter/RSMat Water

/run/beamOn 200



