// This code implementation is the intellectual property of
// the RD44 GEANT4 collaboration.
//
// By copying, distributing or modifying the Program (or any work
// based on the Program) you indicate your acceptance of this statement,
// and all its terms.
//
// $Id: schema.cc,v 2.0 1998/07/02 17:05:11 gunter Exp $
// GEANT4 tag $Name: geant4-00 $
//
#ifndef  SCHEMA_CC
#define  SCHEMA_CC
// This file was generated by fedex_plus.  You probably don't want to edit
// it since your modifications will be lost if fedex_plus is used to
// regenerate it.
/*   */ 
class Registry;

void 
SchemaInit (Registry & reg)
{
	 extern void SdaiCONFIG_CONTROL_DESIGNInit (Registry & r);
	 SdaiCONFIG_CONTROL_DESIGNInit (reg); 

}
#endif
