

//



//
// $Id: schema.cc,v 1.2 1999-05-21 20:21:12 japost Exp $
// GEANT4 tag $Name: not supported by cvs2svn $
//
#ifndef  SCHEMA_CC
#define  SCHEMA_CC
// This file was generated by fedex_plus.  You probably don't want to edit
// it since your modifications will be lost if fedex_plus is used to
// regenerate it.
/*   */ 
class Registry;

void 
SchemaInit (Registry & reg)
{
	 extern void SdaiCONFIG_CONTROL_DESIGNInit (Registry & r);
	 SdaiCONFIG_CONTROL_DESIGNInit (reg); 

}
#endif
