      INTEGER*4 FUNCTION SETNTUC()
      INTEGER NNTUC
      PARAMETER (NNTUC = 200)
      INTEGER*4 NVAR,P
      COMMON /NTUC/ NVAR,P(NNTUC)
      NVAR = 0
      SETNTUC = NNTUC
      RETURN
      END
