# $Id: hadron.mac,v 1.1 2004-09-24 09:57:57 maire Exp $
#
# macro file for TestEm5.cc
#
/control/verbose 2
/run/verbose 2
#
/testem/det/setAbsMat Iron
#
/testem/det/setAbsThick 1 m
/testem/det/setAbsYZ    1 m
#
/testem/phys/addPhysics  standard
/testem/phys/addPhysics  binary
/testem/phys/addPhysics  binary_ion
/testem/phys/addPhysics  elastic
#
/testem/phys/setCuts 1 km
#
/run/initialize
#
/testem/gun/setDefault
/gun/particle pi+ 
/gun/energy 500 MeV
#
/tracking/verbose 1
#
/run/beamOn 1


