# $Id: ion.mac 66241 2012-12-13 18:34:42Z gunter $
#
# macro file for TestEm5.cc
#
/control/verbose 2
/run/verbose 2
#
/testem/det/setAbsMat G4_Fe
#
/testem/det/setAbsThick 0.1 mm
/testem/det/setAbsYZ    1 m
#
/testem/phys/addPhysics  emstandard
#
/testem/phys/setCuts 1 km
#
/run/initialize
#
#/testem/gun/setDefault
/gun/particle ion
/gun/ion 6 12 
/gun/energy 1200 MeV
#
/tracking/verbose 0
#
/run/beamOn 1000
