# $Id: neutron.mac,v 1.5 2009-09-18 14:03:24 maire Exp $
#
# macro file for TestEm5.cc
#
/control/verbose 2
/run/verbose 2
#
/testem/det/setAbsMat H2Liq
###/testem/det/setAbsMat Beryllium
###/testem/det/setAbsMat Graphite
###/testem/det/setAbsMat Water
#
/testem/det/setAbsThick 20 cm
/testem/det/setAbsYZ    20 cm
#
/testem/phys/addPhysics  local
#
/testem/phys/setCuts 1 km
#
/run/initialize
#
/testem/gun/setDefault
/gun/particle neutron 
/gun/energy 3 MeV
#
/testem/histo/setFileName h2liq
/testem/histo/setHisto 1 200 0.01 4000. keV	#energy deposit
#
##/testem/event/printModulo 10000
#
/run/beamOn 100000


