#================================================
#     Macro file for test42 PbWO4
#     10.12.2007 V.Grichine
#================================================
/control/verbose 2
/run/verbose 1
/tracking/verbose 0
#
/testhadr/TargetMat        G4_PbWO4
/testhadr/TargetRadius     100 cm
/testhadr/TargetLength     230 cm
/testhadr/NumberDivZ       10
/testhadr/PrintModulo      10
#
/testhadr/photonBias      500
#
/testhadr/CutsAll          0.7 mm
#/testhadr/Physics          PHYSLIST
#
# Recommended: LHEP, QGSP, QGSC, FTFP, QGSP_BIC, QGSP_BERT
#
/testhadr/Physics          LHEP
#
/run/initialize
#
#/process/eLoss/MscStepLimit 0.2 false
#
/testhadr/HistoName        crystal
/testhadr/HistoType        root
/testhadr/HistoPrint       1
/testhadr/MaxEdep          10 GeV
#
#/process/inactivate Cerenkov
#/process/inactivate Scintillation
#
#/gun/particle e-
/gun/particle proton
#/gun/particle pi-
#/gun/particle pi+
#
/gun/energy 5. GeV
#/gun/energy 0.1 GeV
#/gun/energy 40. GeV
/run/beamOn 50
#
