# $Id: run12.mac,v 1.2 2003-10-10 10:42:36 maire Exp $
#
# Macro file for "TestEm6.cc"
# (can be run in batch, without graphic)
#
#
/control/verbose 2
/run/verbose 2
#
/testem/det/setMat Carbon
/testem/det/setSize 18.5 cm
#
/run/initialize
#
/testem/phys/SetGammaToMuPairFac  1000
/testem/phys/SetAnnihiToMuPairFac 1000
#
/gun/particle e+
/gun/energy 250 GeV
#
/testem/event/printModulo 1000
#
/run/beamOn 20000
