#
# Macro file for "TestEm6.cc"
# (can be run in batch, without graphic)
#
#
/control/verbose 2
/run/verbose 2
#
/testem/det/setMat G4_C
/testem/det/setSize 18.5 cm
#
/testem/phys/addPhysics emstandard_opt1
/run/setCut 1 km
#
/run/initialize
#
/testem/phys/SetGammaToMuPairFac  1000
/testem/phys/SetAnnihiToMuPairFac 1000
#
/gun/particle e+
/gun/energy 250 GeV
#
/run/printProgress 1000
#
/run/beamOn 20000
