# $Id: proton.mac,v 1.11 2008-03-18 09:51:23 maire Exp $
#
# Macro file for "TestEm7.cc"
# (can be run in batch, without graphic)
#
#
/control/verbose 2
/run/verbose 2
#
/testem/det/setMat Water
/testem/det/setSizeX  10 cm
/testem/det/setSizeYZ 10 cm
#
/testem/phys/addPhysics  standard	#em physics
#
/run/initialize
#
/gun/particle proton
/gun/energy 100 MeV
#
# step limit
/testem/stepMax 0.5 mm
#
/testem/event/printModulo 1000
#
#/run/beamOn 10000
