# $Id: run01.mac,v 1.1 2003-04-22 16:25:03 maire Exp $
#
# Macro file for "TestEm7.cc"
# (can be run in batch, without graphic)
#
#
/control/verbose 2
/run/verbose 2
#
/run/initialize
#
/testem/det/setMat Water
/testem/det/setSizeX  20 cm
/testem/det/setSizeYZ 20 cm
/testem/det/update
#
/gun/particle proton
/gun/energy 160 MeV
#
/testem/event/printModulo 1000
/testem/stepMax 1 mm
#
/run/beamOn 10000

