#
# create empty scene
#
/vis/scene/create
#
# Create a scene handler for a specific graphics system
# (Edit the next line(s) to choose another graphic system)
#
/vis/open OGLIX
#
# for drawing the tracks
# (if too many tracks cause core dump => storeTrajectory 0)
/tracking/storeTrajectory 1
/vis/scene/endOfEventAction accumulate
/vis/scene/add/trajectories
#
# draw scene
#
#/vis/viewer/set/viewpointThetaPhi 105 165 deg
/vis/viewer/set/viewpointThetaPhi 75 165 deg
/vis/viewer/zoom 2.0
/vis/drawVolume worlds

