                                                          
      PARAMETER (NBIN= 50)                                                      
      COMMON/CELOSS/ SEL1(NBIN), SEL1C(NBIN), SER1(NBIN), SER1C(NBIN),          
     +               SEL2(NBIN), SEL2C(NBIN), SER2(NBIN), SER2C(NBIN),                                         
     +               DEDL(NBIN), DEDR(NBIN) , FNPAT(NBIN,3), 
     +               STRCH,STRCH1,STRCH2,STRNE,STRNE1,STRNE2                
