
      COMMON/PVOLUM/ IMAT,NLTOT,NRTOT,DLX0,DRX0,X0,Z1,R1  
*                                                               
*  IMAT   = GEANT material number.                              (data card MATE)
*  NLTOT  = total number of longitudinal bins.                  (data card BINS)
*  NRTOT  = total number of radial bins.                        (data card BINS)
*  DLX0   = longitudinal bin length , in radiation length unit. (data card BINS)
*  DRX0   = radial bin length       , in radiation length unit. (data card BINS)
*                                                                               
