/control/verbose 2
/run/initialize
/run/setCutForRegion Calor-A 0.2 mm
/run/setCutForRegion Calor-B 2 mm
/run/setCutForRegion Calor-C 2 cm

### retrieve physics table
###  set store format : 0 binary   1 ascii
/run/particle/setStoredInAscii 0
#/run/particle/verbose 3 
/run/particle/retrievePhysicsTable physTable

### dump couples
#/tracking/verbose 1
/run/beamOn 1
/run/dumpRegion
/run/dumpCouples

###  10 events
/tracking/verbose 0
/run/beamOn 10

