/control/verbose 1
/run/verbose 1
/event/verbose 0
/tracking/verbose 0
# create empty scene
#
#/vis/scene/create
#
# Create a scene handler for a specific graphics system
# (Edit the next line(s) to choose another graphic system)
#/control/saveHistory
#
#/vis/open OGLIX
#/vis/open DAWNFILE
#/vis/viewer/flush
#/vis/viewer/update
/tracking/storeTrajectory 1
#/vis/scene/endOfEventAction accumulate
/target/setTargetThick 0.5 cm
/target/setTargetMat  Lead
/target/update
/gun/particle e-
/gun/energy 10 MeV
/run/beamOn 1000

