/control/verbose 0
/run/verbose 0
/event/verbose 0
/tracking/verbose 0
# create empty scene
#
#/vis/scene/create
#
# Create a scene handler for a specific graphics system
# (Edit the next line(s) to choose another graphic system)
#/control/saveHistory
#
#/vis/open OGLIX
#/vis/open DAWNFILE
#/vis/viewer/flush
#/vis/viewer/update
/tracking/storeTrajectory 1
#/vis/scene/endOfEventAction accumulate
/target/setTargetThick 0.53 mm
/target/setTargetMat  Silicon
/target/update
/le/cutE 7. micrometer
/gun/particle e-
/gun/energy 1. MeV
/run/beamOn 10000

