#cosi' e' possibile mettere la configurazione per il calcolo del CSDA range e d#e gli Stopping Power degli elettroni.
/control/verbose 0
/run/verbose 0
/gun/particle e-
/gun/energy 30.  MeV 
#esempio di energia
/gun/position 0. 0. 0.
/gun/randomDirection on 
/target/setTargetThick 1500. cm
/target/setTargetX 1500. cm
/target/setTargetY 1500. cm
/target/setMaxStep 0.01 micrometer
#/le/range_processes off
/le/cutE 1. m
/target/update
/run/beamOn 10