#
# Macro file for the initialization phase of "exampleN03.cc"
# when runing in interactive mode
#
# Sets some default verbose
#
#
#/control/verbose 2
#/run/verbose 2
# create empty scene
#
/vis/scene/create
#
# Create a scene handler for a specific graphics system
# (Edit the next line(s) to choose another graphic system)
#/control/saveHistory
#
#/vis/open OGLIX
#/vis/open DAWNFILE
#/vis/viewer/flush
#/vis/viewer/update

#
# draw scene/
#

#
# for drawing the tracks
# (if too many tracks cause core dump => storeTrajectory 0)
#/tracking/storeTrajectory 1
#/vis/scene/endOfEventAction accumulate

#/vis/viewer/update

# create 30 30 view
#/vis/viewer/set/viewpointThetaPhi 30 30
/run/beamOn 1000



