#cosi' e' possibile calcolare lo StoppingPower degli elettroni in un mezzo.
#se i processi sono Standard fare
#/process/eLoss/fluct false
/control/verbose 0
/run/verbose 0
/gun/particle e-
/gun/position 0. 0. 0.
/gun/randomDirection on 
/target/setTargetMat Hydrogen
/target/setTargetThick 1500. cm
/target/setTargetX 1500. cm
/target/setTargetY 1500. cm
/target/setMaxStep 0.000001 cm
#cut alto sempre per il test in range
/le/cutE 1. m
/target/update
/gun/energy 0.01 MeV 
/run/beamOn 1
/gun/energy 0.02 MeV
/run/beamOn 1
/gun/energy 0.03 MeV
/run/beamOn 1
/gun/energy 0.04 MeV
/run/beamOn 1
/gun/energy 0.05 MeV