### HTB177 cell line - irradiation with He4 ions

/process/dna/e-SolvationSubType Meesungnoen2002
#/process/dna/e-SolvationSubType Ritchie1994
#/process/dna/e-SolvationSubType Terrisol1990

/run/verbose 1
/control/verbose 1

/world/worldSize 50 um
/cell/radiusSize 17 2.5 13 um
/scheduler/endTime 5.0 ns
/scheduler/maxNullTimeSteps 10000000
/dnageom/radicalKillDistance 9 nm
/dnageom/interactionDirectRange 2 angstrom

/dnageom/placementSize 77 77 77 nm
/dnageom/fractalScaling 77 77 77 nm
/dnageom/definitionFile geometries/cube-centred-X-8.txt
/dnageom/placementVolume turn geometries/turned_solenoid_770_withHistone.txt
/dnageom/placementVolume turntwist geometries/turned_twisted_solenoid_770_withHistone.txt true
/dnageom/placementVolume straight geometries/straight_solenoid_770_withHistone.txt

/dnadamage/directDamageLower 5 eV
/dnadamage/directDamageUpper 37.5 eV

/dnadamage/indirectOHBaseChance 1.0
/dnadamage/indirectOHStrandChance 0.405
/dnadamage/inductionOHChance 0.00

/dnadamage/indirectHBaseChance 1.0
/dnadamage/indirectHStrandChance 0.0
/dnadamage/inductionHChance 0.00

/dnadamage/indirectEaqBaseChance 1.0
/dnadamage/indirectEaqStrandChance 0.0
/dnadamage/inductionEaqChance 0.00


/chromosome/add cell ellipse 8550 2500 6425 0 0 0 nm 0 0 0


/run/initialize
/run/printProgress 1

# Source Geometry
/gps/pos/type Plane
/gps/pos/shape Circle
/gps/pos/centre 0 3000 0 nm
/gps/pos/rot1 0 0 1 
/gps/pos/rot2 1 0 0 
/gps/pos/radius 8550 nm
/gps/direction 0 -1 0

# Source Energy
/gps/particle ion
/gps/ion 2 4 2 ### Helium

/analysisDNA/fileName HTB5MeV #LET 80.3
/gps/energy 5 MeV
/run/beamOn 150

/analysisDNA/fileName HTB7p5MeV #65.9
/gps/energy 7.5 MeV
/run/beamOn 180

/analysisDNA/fileName HTB10MeV #53.3
/gps/energy 10 MeV
/run/beamOn 220

/analysisDNA/fileName HTB15MeV #39.2
/gps/energy 15 MeV
/run/beamOn 300

/analysisDNA/fileName HTB20MeV #31.4
/gps/energy 20 MeV
/run/beamOn 390

/analysisDNA/fileName HTB30MeV #22.8
/gps/energy 30 MeV
/run/beamOn 550

/analysisDNA/fileName HTB60MeV #13.05
/gps/energy 60 MeV
/run/beamOn 930

/analysisDNA/fileName HTB261MeV #4
/gps/energy 261 MeV
/run/beamOn 3000

