#
# Macro file for A01app
#
# Set verbosity
#
/control/verbose 2
# /vis/verbose confirmations
#
# Create a scene handler and viewer for HepRep
#
/vis/open HepRepFile
#/vis/open DAWNFILE
#
# Draw detector
#
/vis/drawVolume
#
# Declare that trajectories and hits should be added to the scene
#
/vis/scene/add/trajectories
#/vis/scene/add/hits
/vis/scene/endOfEventAction accumulate

/mydet/randomizePrimary FALSE
/gun/particle e-

/run/beamOn 3
