# *********************************************************************
# MANDATORY SETTINGS
# (before kernel initialization)
#
# MT
/run/numberOfThreads 10
#
# Phantom file name
/phantom/fileName phantoms/phantom.dat
#
# World volume size
/world/sizeXY 1 mm
/world/sizeZ 100 um
#
# Cellular medium size
/phantom/mediumSizeXY 900 um
/phantom/mediumSizeZ 95 um
#
# *********************************************************************
# OPTIONAL SETTINGS
# (before kernel initialization)
#
# Change cellular medium material
#/phantom/mediumMat G4_AIR
#
# Change phantom densities
#/phantom/redDen 2.0 g/cm3  	# red volume density
#/phantom/greenDen 1.0 g/cm3	# green volume density
#/phantom/blueDen 3.0 g/cm3		# blue volume density
#
# Phantom shift
#/phantom/shiftX 100 um
#/phantom/shiftY 50 um
#/phantom/shiftZ 1.4 um
#
/run/verbose 1
/event/verbose 0
/tracking/verbose 0
#
# *********************************************************************
# RUN
#
/run/initialize
#
# Set cuts OUTSIDE the phantom region
/run/setCut 1 mm
#
# Set cut for the phantom region
/run/setCutForRegion phantomRegion 1 nm
#
# Print a summary of particles/regions/cuts
/run/dumpCouples
#
/gps/particle proton
/gps/energy 3.5 MeV
#
# Square plane source
/gps/pos/type Plane
/gps/pos/shape Square
/gps/direction 0 0 1
/gps/pos/rot1 1 0 0
/gps/pos/rot2 0 1 0
/gps/pos/centre 0. 0. -50 um
/gps/pos/halfx 350 um
/gps/pos/halfy 350 um
#/gps/pos/halfx 0 um
#/gps/pos/halfy 0 um
#
# *********************************************************************
# VISUALIZATION SETTINGS
#
# Use this open statement to create an OpenGL view:
/vis/open OGL 600x600-0+0
#
# Use this open statement to create a .prim file suitable for
# viewing in DAWN:
#/vis/open DAWNFILE
#
# Use this open statement to create a .wrl file suitable for
# viewing in a VRML viewer:
#/vis/open VRML2FILE
#
# Disable auto refresh and quieten vis messages whilst scene and
# trajectories are established:
/vis/viewer/set/autoRefresh false
/vis/verbose errors
#
# Draw geometry:
/vis/drawVolume
#
# Specify style (surface or wireframe):
/vis/viewer/set/style wireframe
#
# Theta and phi camera angle:
/vis/viewer/set/viewpointThetaPhi 30 45
#
# Specify zoom value:
/vis/viewer/zoom 1
#
# Specify viewpoint:
#/vis/viewer/set/viewpointVector 400 0 105.79
#
# Specify target point (so a viewpoint rotation keeps it in view)
#/vis/viewer/set/targetPoint -1461.42 0.0 -386.51 mm
#
# Draw coordinate axes:
#/vis/scene/add/axes 0 0 0 1 m
#
# Draw smooth trajectories at end of event, showing trajectory points
# as markers 2 pixels wide:
/vis/scene/add/trajectories smooth
/vis/modeling/trajectories/create/drawByCharge
/vis/modeling/trajectories/drawByCharge-0/default/setDrawStepPts true
/vis/modeling/trajectories/drawByCharge-0/default/setStepPtsSize 2
# (if too many tracks cause core dump => /tracking/storeTrajectory 0)
#
# Draw hits at end of event:
/vis/scene/add/hits
#
# To draw only gammas:
#/vis/filtering/trajectories/create/particleFilter
#/vis/filtering/trajectories/particleFilter-0/add gamma
#
# To invert the above, drawing all particles except gammas,
# keep the above two lines but also add:
#/vis/filtering/trajectories/particleFilter-0/invert true
#
# Many other options are available with /vis/modeling and /vis/filtering.
# For example, to select colour by particle ID:
#/vis/modeling/trajectories/create/drawByParticleID
#/vis/modeling/trajectories/drawByParticleID-0/set e- blue
#
# To superimpose all of the events from a given run:
/vis/scene/endOfEventAction accumulate
#
# Re-establish auto refreshing and verbosity:
/vis/viewer/set/autoRefresh true
/vis/verbose warnings
#
# For file-based drivers, use this to create an empty detector view:
#/vis/viewer/flush
