# $Id: anni.mac,v 1.3 2006/04/24 16:48:54 maire Exp $
#
# Macro file for "TestEm13.cc"
# (can be run in batch, without graphic)
#
# e+ e- ---> gamma gamma
#
/control/verbose 2
/run/verbose 2
#
/testem/det/setMat Aluminium
/testem/det/setSize 5 cm
#
/run/initialize
#
/process/inactivate eIoni
/process/inactivate eBrem
#
/gun/particle e+
/gun/energy 100 MeV
#
##/tracking/verbose 2
##/run/beamOn 1
#
/run/beamOn 100000
