# $Id: electron.mac,v 1.3 2006-04-24 16:48:54 maire Exp $
#
# Macro file for "TestEm13.cc"
# (can be run in batch, without graphic)
#
/control/verbose 2
/run/verbose 2
#
/testem/det/setMat Aluminium
/testem/det/setSize 1 cm
#
/run/initialize
#
/testem/phys/setCuts 500 um

###/process/inactivate eIoni
###/process/inactivate eBrem
#
/gun/particle e-
/gun/energy 100 MeV
#
###/tracking/verbose 2
###/run/beamOn 1
#
/run/beamOn 100000
