# $Id: gamma.mac,v 1.4 2007/06/24 22:26:54 maire Exp $
#
# Macro file for "TestEm13.cc"
# (can be run in batch, without graphic)
#
# photon 100 keV; all processes
#
/control/verbose 2
/run/verbose 2
#
/testem/det/setMat Water
/testem/det/setSize 1 cm
#
/testem/phys/addPhysics standard
#
/run/initialize
#
/gun/particle gamma
/gun/energy 100 keV
/run/beamOn 100000
#
/testem/det/setSize 5 cm
/run/beamOn 100000
