# number of events and ouput file
/B08/nevents 10
/B08/resultsfile B08ScoreResults.txt
# set the upper and lower limit for the weight window sampling
# if both are set to 1 the scores "av w/tr rel." and
# "av w/co rel" should be 1.
/B08/upperlimit 5     
/B08/lowerlimit 0.2
# paricle energy, only for higher energies a particle may create
# neutrons with weight not according to the importance values.
/gun/energy 300.0 MeV
#
# setting of the importance values = pow(base,exp)
#
/B08/importance/cell_02/base 1
/B08/importance/cell_02/exp 0
#
/B08/importance/cell_03/base 1
/B08/importance/cell_03/exp 1
#
/B08/importance/cell_04/base 1
/B08/importance/cell_04/exp 2
#
/B08/importance/cell_05/base 1
/B08/importance/cell_05/exp 3
#
/B08/importance/cell_06/base 1
/B08/importance/cell_06/exp 4
#
/B08/importance/cell_07/base 1
/B08/importance/cell_07/exp 5
#
/B08/importance/cell_08/base 1
/B08/importance/cell_08/exp 6
#
/B08/importance/cell_09/base 1
/B08/importance/cell_09/exp 7
#
/B08/importance/cell_10/base 1
/B08/importance/cell_10/exp 8
#
/B08/importance/cell_11/base 2
/B08/importance/cell_11/exp 1
#
/B08/importance/cell_12/base 2
/B08/importance/cell_12/exp 2
#
/B08/importance/cell_13/base 2
/B08/importance/cell_13/exp 3
#
/B08/importance/cell_14/base 2
/B08/importance/cell_14/exp 4
#
/B08/importance/cell_15/base 2
/B08/importance/cell_15/exp 5
#
/B08/importance/cell_16/base 2
/B08/importance/cell_16/exp 6
#
/B08/importance/cell_17/base 2
/B08/importance/cell_17/exp 7
#
/B08/importance/cell_18/base 2
/B08/importance/cell_18/exp 8
#
/B08/importance/cell_19/base 2
/B08/importance/cell_19/exp 9
#

