#================================================
# Macro file for the Air test of "hTest.cc"
#         10.04.01 V.Ivanchneko
#================================================ 
/control/verbose 2
/run/verbose 2
/step/verbose 0
/tracking/verbose 0
/stepping/verbose 0
/event/verbose 0
/hTest/verbose 0
#
/hTest/physics/cutGamma    1.0 cm
/hTest/physics/cutElectron 0.1 mm
/hTest/physics/MaxStep     0.1 mm
/hTest/physics/EMList      LowEnergy
/hTest/physics/HadronList  LowEnergy
/hTest/AbsorberMaterial    Air
/hTest/WorldMaterial       Vacuum
/hTest/HistoName           air3.paw 
/hTest/NumberOfEvents      1000
#
#/gun/particle e-
#/gun/particle gamma
#/gun/particle proton
/gun/particle alpha
#/gun/particle triton
#/gun/particle IonC12
/gun/energy 5.0 MeV
#/gun/energy 0.001 MeV
#/gun/energy 175.0 MeV
#/gun/energy 360.0 MeV
#/gun/energy 3240.0 MeV
#
#/run/beamOn 10

