#================================================
# Macro file for the Air test of "hTest.cc"
#         10.04.01 V.Ivanchneko
#================================================ 
/control/verbose 2
/run/verbose 2
/step/verbose 0
/tracking/verbose 0
/stepping/verbose 0
/event/verbose 0
/hTest/verbose 0
#
/hTest/physics/cutGamma    1.0 cm
/hTest/physics/cutElectron 0.01 mm
/hTest/physics/MaxStep     1.0 mm
#/hTest/physics/EMList      LowEnergy
/hTest/physics/EMList      Standard
/hTest/physics/HadronList  LowEnergy
/hTest/AbsorberMaterial    Air
#/hTest/AbsorberMaterial    Silicon
/hTest/WorldMaterial       Vacuum
/hTest/AbsorberThick       1.0 mm
/hTest/AbsorberXY          20.0 cm
/hTest/NumberOfAbsorbers   300
/hTest/HistoName           air.paw 
/hTest/gun/beamE           5.0 MeV
/hTest/NumberOfEvents      1000
#
#/gun/particle e-
#/gun/particle gamma
#/gun/particle proton
#/gun/particle pi+
/gun/particle alpha
#/gun/particle triton
#/gun/particle IonC12

