#
# Macro file for the initialization phase of "hTest.cc"
#
# It creates the default geometry (simple absorber box) 
#
/control/verbose 2
#control/saveHistory
/run/verbose 2
#/step/verbose 2
#/tracking/verbose 2
#/stepping/verbose 2
#/event/verbose 2
#
#/run/initialize
#
#/calor/setAbsMat Silicon   
#/calor/setAbsThick 50. mum  
#/calor/setAbsYZ 10. cm
#/calor/update
#
#  PLOT: angle distr. of transmitted particles
#/plots/setnbinTh 60
#/plots/setThlow 0.0 deg
#/plots/setThhigh 6.0 deg
#
#/calor/cutG 2130.0 micrometer
#/calor/cutE 50.0 mm
#/calor/cutG 10.0 mm
#/calor/cutE 0.015 mm
#  hist file name
/plots/sethistName C360le.paw 
#/plots/sethistName enb.paw 
#/plots/sethistName c12le.paw 
/run/initialize
#/run/particle/dumpCutValues
#/event/drawTracks none
#
#/gun/particle e-
#/gun/particle gamma
#/gun/particle proton
/gun/particle IonC12
/gun/energy 360.0 MeV
#/gun/energy 3240.0 MeV
#
/run/beamOn 1000




