#=======================================================
# Macro file "mylar.mac" for the Mylar test by hTest.cc
# 10.04.01 V.Ivanchenko
#======================================================= 
/control/verbose           2
/run/verbose               2
/step/verbose              0
/tracking/verbose          0
/stepping/verbose          0
/event/verbose             0
/hTest/verbose             0
#
/hTest/physics/cutGamma    0.01  mm
/hTest/physics/cutElectron 0.001 mm
/hTest/physics/MaxStep     1.0 mm
/hTest/physics/EMList      LowEnergy
/hTest/physics/HadronList  LowEnergy
/hTest/AbsorberMaterial    Mylar
/hTest/AbsorberThick       0.001 mm
/hTest/NumberOfAbsorbers   60
/hTest/WorldMaterial       Vacuum
/hTest/numberAbsToSave     60
/hTest/HistoName           mylar.paw 
/hTest/NumberOfEvents      1000
#
/gun/particle              proton
/gun/energy                2 MeV

