# $Id: run02.mac,v 1.1 2002-12-16 11:41:45 stesting Exp $
#
# Macro file for "TestEm2.cc" 
# (can be run in batch, without graphic)
#
# Al L = 13.5 radl  R = 1.35 radl; electron 1 GeV
#
#  Experimental results: Electron-induced cascade showers
#                        J&H Crannel - Phys. Rev. 184-2 - August69
#
/control/verbose 2
#
/testem/phys/addPhysics  model
#/testem/phys/addPhysics  standard
#
/testem/phys/setCuts 2.0 mm
/run/initialize
#
/testem/det/setMat Al
/testem/det/setLbin 12 1.1245
/testem/det/setRbin 12 0.11245
/testem/det/update
#
/run/verbose 2
/testem/event/printModulo 10
#
/gun/particle e-
/gun/energy 1 GeV
/run/beamOn 500


