# 									
# Demonstrate that isotopes produced in hadronic processes
# can be treated by RadioactiveDecay.  
#
# To register hadronic processes, uncomment corresponding lines
# in PhysicsList.cc
#                                                                         
/control/verbose 2
/run/verbose 1
#
# set the target/detector geometry
/rdecay02/det/setTargetMate G4_SODIUM_IODIDE
#
/run/initialize
#
/process/list
#
# rdm is applied only to the target volume
/grdm/noVolumes
/grdm/selectVolume Target

/gun/particle neutron 
/gun/energy 10 eV
/gun/position 0. 0. -2.4 cm
#
/analysis/setFileName neutron
/run/printProgress 1000
/run/beamOn 10000


 





