#################################################################################
#                                                                              	#
# ESA-CERN GEANT4 RADIOACTIVE DECAY MODULE                                     	#
# 									                                            #	
# 									      										#
# THIS example  DEMONSTRATE THE use of user data for radioactive decay			#
# 	for decay of nuclei with Z>100 in this case the decay of No252 excited 	    # 
#                                                    is simulated              	#
#  Desorgher  Laurent, 4 November 2011                                    		#
#                                                                              	#
#################################################################################

/histo/setHisto 0 50 0 1 MeV
/histo/setHisto 1 50 0 15 MeV
/histo/setHisto 2 50 0 15 MeV
/histo/setHisto 3 50 0 15 MeV
/histo/setHisto 4 50 0 1 MeV
/histo/setHisto 5 50 0 15 MeV
/histo/setHisto 6 50 0 15 MeV
/exrdm/det/setTargetRadius 1e10 pc
/exrdm/det/setTargetLength 1e10 pc
/exrdm/det/setDetectorThickness 1e10 pc
/exrdm/det/setDetectorLength  1e10 pc
/run/initialize

/run/setCutForRegion Target 50 cm
/run/setCutForRegion Detector 50 cm

/process/inactivate  msc
/process/inactivate hIoni
#/process/inactivate ionIoni
/process/inactivate eIoni
/process/inactivate  eBrem
/process/inactivate annihil
/process/inactivate phot
/process/inactivate compt
/process/inactivate conv
/process/inactivate  hBrems
/process/inactivate hPairProd
/process/inactivate CoulombScat
/process/inactivate Decay

/run/verbose 0
/event/verbose 0
/grdm/verbose 0
/grdm/noVolumes
/grdm/selectVolume Target

#
#Next lines needed to have  atomic relaxation working 
#
/process/em/fluo true
/process/em/auger true




/gps/position 0 0 0
/gps/energy 0 keV
/gps/particle ion 
/gps/ion  102 252 0 3.2070e+02
/grdm/setPhotoEvaporationFile 102 252 UserEvapData_z102.a252


#
# Only some 
/histo/fileName userNo252
/tracking/verbose 1
/run/beamOn 10










