#################################################################################
#                                                                              	#
# ESA-CERN GEANT4 RADIOACTIVE DECAY MODULE                                     	#
# 									                                            #	
# 									      										#
# THIS example  DEMONSTRATE THE use of user data for radioactive decay			#
# 																				# 
#                                                                              	#
#  Desorgher  Laurent, 4 November 2011                                    		#
#                                                                              	#
#################################################################################

/histo/setHisto 0 50 0 1 MeV
/histo/setHisto 1 50 0 15 MeV
/histo/setHisto 2 50 0 15 MeV
/histo/setHisto 3 50 0 15 MeV
/histo/setHisto 4 50 0 1 MeV
/histo/setHisto 5 50 0 15 MeV
/histo/setHisto 6 50 0 15 MeV
/exrdm/det/setTargetRadius 1e10 pc
/exrdm/det/setTargetLength 1e10 pc
/exrdm/det/setDetectorThickness 1e10 pc
/exrdm/det/setDetectorLength  1e10 pc
/run/initialize

/run/setCutForRegion Target 50 cm
/run/setCutForRegion Detector 50 cm

/process/inactivate  msc
/process/inactivate hIoni
#/process/inactivate ionIoni
/process/inactivate eIoni
/process/inactivate  eBrem
/process/inactivate annihil
/process/inactivate phot
/process/inactivate compt
/process/inactivate conv
/process/inactivate  hBrems
/process/inactivate hPairProd
/process/inactivate CoulombScat
/process/inactivate Decay


#
#Define user radioactive data 
#The data files should be defined before definition of the ion source 
#otherwise the mean life time will not be selected correctly
#
/grdm/setRadioactiveDecayFile 82 210 UserRadData_z82.a210

#
#Next lines needed to have  atomic relaxation working 
#
/process/em/fluo true
/process/em/auger true



/run/verbose 0
/event/verbose 0
/grdm/verbose 0
/grdm/noVolumes
/grdm/selectVolume Target


/gps/position 0 0 0
/gps/energy 0 keV
/gps/particle ion 
/gps/ion 82 210 0  0


#
# Only some 
/histo/fileName userPb210
/tracking/verbose 0
/grdm/nucleusLimits 210 210 82 82 

/run/beamOn 2
/run/beamOn 10000










