#
# Macro file gflasha example
# when runing in batch mode
#

/exgflash/det/setLbin 40 0.5
/exgflash/det/setRbin 50 0.1

/gps/pos/centre 0 0 0
/gps/particle  e-
/gps/energy    50 GeV
/gps/direction  0. 0. 1.0

# Paramatrisation on 
/GFlash/flag 1


# for drawing the tracks
# (if too many tracks cause core dump => storeTrajectory 0)
#/tracking/storeTrajectory 1

#/vis/scene/endOfEventAction accumulate
/tracking/verbose 0

/run/beamOn 10
