#
# Macro file gflasha example
# when runing in batch mode
#
/exgflash/verbose 1

# set calo material
/exgflash/det/setMat G4_PbWO4

#detector geometry 5 x 5 cristal ~5 Rm and ~28 X0

/exgflash/det/setNbCrys 5
/exgflash/det/setCrysWidth 3.52 cm
/exgflash/det/setCrysLength 25.0 cm

/exgflash/det/setLbin 56 0.5
/exgflash/det/setRbin 50 0.1

/analysis/h1/set 0 100 90. 110.     none # total energy deposit(percent of Einc) 

/run/initialize

/gps/pos/centre 0 0 0
/gps/particle  e-
/gps/energy    50 GeV
/gps/direction  0. 0. 1.0

# Paramatrisation on
/GFlash/flag 1


# for drawing the tracks
# (if too many tracks cause core dump => storeTrajectory 0)
#/tracking/storeTrajectory 1

#/vis/scene/endOfEventAction accumulate
/tracking/verbose 0

/run/beamOn 100

# Paramatrisation off
/GFlash/flag 0
/analysis/setFileName gflash00


/run/beamOn 100
