test_selection_volumes.log
################################################################################
#                                                                              #
# ESA-CERN GEANT4 RADIOACTIVE DECAY MODULE                                     #
# VALIDATION TEST NUMBER 01                                                    #
#                                                                              #
# TEST  THE SELECTION OF VOLUMES											   #
#          			                                        	               #
#                                                                              #
# L Desorgher, SpaceIT, 26 JULY 2012                                           #
#                                                                              #
################################################################################
#
#
# NOTE THAT THE FIRST RECORD IN THIS MACROFILE IS THE OUTPUT LOG-FILE NAME.
# NOW SET VERBOSE LEVELS FOR RUN, EVENT, TRACKING AND THE RDM PROCESS.
#
/run/verbose 0
/event/verbose 0
/tracking/verbose 1
/grdm/verbose 0
#
#
# 
#
#
#
# Decay of NA-24 Ground state in all volumes
# 
#
/grdm/nucleusLimits 24 24 11 11
/grdm/ion 24 11 0
/run/beamOn 1

# No volumes selected
/grdm/noVolumes
/run/beamOn 1

# Sphere1 selected
/grdm/selectVolume aSphere_L1
/run/beamOn 1


