test_ion_life_time.log
################################################################################
#                                                                              #
# ESA-CERN GEANT4 RADIOACTIVE DECAY MODULE                                     #
# VALIDATION TEST NUMBER 01                                                    #
#                                                                              #
# THIS TEST GENERATES SOME EXCITED SATE OF NUCLEI AND DECAY THEM FROM   GRDM   #				                                                       #
# TO CHECK IF THE LIFETIME IS CORRECTLY SELECTED FROM THE RADDECAY OR          #
# EVAPORATION DATABASE.                                        	               #
#                                                                              #
# L Desorgher, SpaceIT, 26 JULY 2012                                           #
#                                                                              #
################################################################################
#
#
# NOTE THAT THE FIRST RECORD IN THIS MACROFILE IS THE OUTPUT LOG-FILE NAME.
# NOW SET VERBOSE LEVELS FOR RUN, EVENT, TRACKING AND THE RDM PROCESS.
#
/run/verbose 0
/event/verbose 0
/tracking/verbose 1
/grdm/verbose 0
/particle/verbose 2
#
#
# 
#
#
#
# NA-24 Ground state
# Present in the RDM database
#
/grdm/nucleusLimits 24 24 11 11
/grdm/ion 24 11 0
 
#
#
# NA-24 (472 KEV METASTABLE STATE) BETA+ DECAY AND IT.
# Present in the RDM database
#
/grdm/nucleusLimits 24 24 11 11
/grdm/ion 24 11 472.2
/run/beamOn 1
#
#
# F-17 495.33 KeV
# Not present in the raddecay data but in photo-evaporation 
#
/grdm/nucleusLimits 17 17 9 9
/grdm/ion 17 9 495.33
/run/beamOn 1

