# $Id: run1.mac,v 1.2 2005-05-23 16:16:30 link Exp $
#
#

/run/initialize

#/mydet/SelectDetector Torus
#/mydet/SelectDetector Box
#/mydet/SelectDetector Sphere
#/mydet/SelectDetector Tube
#/mydet/SelectDetector Orb
#/mydet/SelectDetector Cone
#/mydet/SelectDetector TwistedTubs 
#/mydet/SelectDetector  TwistedBox
#/mydet/SelectDetector TwistedTrd
#/mydet/SelectDetector  TwistedTrap
#/mydet/SelectDetector TwistedTrap2
/mydet/SelectDetector TwistedTrap3



/gun/particle geantino
/run/beamOn 10
