/tracking/verbose 0


/run/initialize

/mydet/SelectDetector Torus
#/mydet/SelectDetector Box
#/mydet/SelectDetector Sphere
#/mydet/SelectDetector Tubs
#/mydet/SelectDetector Orb
#/mydet/SelectDetector Cons
#/mydet/SelectDetector TwistedTubs 
#/mydet/SelectDetector  TwistedBox
#/mydet/SelectDetector TwistedTrd
#/mydet/SelectDetector  TwistedTrap
#/mydet/SelectDetector TwistedTrap2
#/mydet/SelectDetector TwistedTrap3


/run/beamOn 43

