#
# Macro file for the initialization phase of "TestEm2.cc"
#
# Sets some default verbose
# and initializes the graphic.
#
/control/verbose 2
#
# Edit the next line(s) to choose another graphic system
#
#/vis~/create_view/new_graphics_system DAWNFILE
#/vis~/create_view/new_graphics_system VRML1FILE
/vis~/create_view/new_graphics_system OGLIX
/vis~/camera/viewpoint 90 180
/vis~/draw/axes 0 0 0 20
/vis~/camera/zoom 1.
/vis~/draw/current
/vis~/show/view
#
# for drawing the tracks
# if too many tracks cause core dump => storeTrajectory 0
/tracking/storeTrajectory 1
/event/drawTracks charged
#
/run/verbose 2
