#
# Macro file for the initialization phase of "TestEm1.cc"
#
# Sets some default verbose
# and initializes the graphic.
#
/control/verbose 2
#
/run/initialize
#
/process/eLoss/StepFunction 0.183  170 micrometer
/calor/cutG 2.2 mm
####/calor/cutE 1.4 micrometer     #before beta03-00  (17.11.98)
/calor/cutE 6.05 micrometer     #from beta03-00  (17.11.98)
/run/initialize
/run/particle/dumpCutValues
#
# Edit the next line(s) to choose another graphic system
#
/vis~/create_view/new_graphics_system OGLIX
/vis~/camera/zoom 1.5
/vis~/draw/current
/vis~/show/view
#
# for drawing the tracks
# if too many tracks cause core dump => storeTrajectory 0
/tracking/storeTrajectory 1
/event/drawTracks all
#
/run/verbose 2
