# $Id: run09.mac,v 1.1 1999-01-08 16:32:40 gunter Exp $
#
# Macro file for "TestEm1.cc"
# (can be run in batch, without graphic)
#
# electron 1 GeV; all processes
#
/control/verbose 2
#
/run/initialize
#
/process/eLoss/StepFunction 0.183 170 micrometer
/calor/cutG 2.2 mm
####/calor/cutE 1.4 micrometer     #before beta03-00  (17.11.98)
/calor/cutE 6.05 micrometer     #from beta03-00  (17.11.98)
/run/initialize
/run/particle/dumpCutValues
#
/run/verbose 2
/event/drawTracks none
#
/gun/particle e-
/gun/energy 1 GeV
/run/beamOn 100
