/tracking/verbose 6

/lowenergy/lowlimGE 250 eV
/lowenergy/cutG 1.5 mum
/lowenergy/cutE 1.5 mum


/gps/type Beam
#/gps/centre -10 5.1 0
/gps/centre -10 0 0
/gps/particle gamma

/gps/monoenergy 3.5 keV
#/gps/monoenergy 400 keV

/gps/shape Circle
/gps/sigmaposr  0.5 mm


#/gps/shape Rectangle
#/gps/sigmaposy 0.3 cm
#/gps/sigmaposx 0.3 cm

/gps/posrot1 0 0 1
/gps/posrot2 0 1 0 

#/gps/angtype beam2d
#/gps/sigmaangx -10 deg
#/gps/sigmaangy -10 deg

/gps/angtype beam1d
/gps/sigmaangr 0 deg

/gps/angrot1 0 0 1
/gps/angrot2 0 1 0

#/run/beamOn 100

/run/beamOn 1000000






