# test21
#
/run/initialize
#
/gps/particle geantino

# source
/gps/pos/type Plane
/gps/pos/shape Square
/gps/pos/centre 1. 2. 1. cm
/gps/pos/halfx 2. cm
/gps/pos/halfy 2. cm

# angular distribution
/gps/ang/type cos

# energy distribution
/gps/ene/type Arb
/gps/hist/type arb
/gps/hist/point 1.0 2
/gps/hist/point 2.0 5.
/gps/hist/point 7.0 1.
/gps/hist/point 10. 1.
/gps/hist/inter Exp

# commands below are independent of gps
#
/analysis/setFileName test21
/analysis/h1/set 1 100 0 15 MeV
/analysis/h2/set 1 100 -5 5 cm none linear 100 -5 5 cm none linear #x-y
/analysis/h2/set 4 120 0 360 deg none linear 100 -1 1 none none linear
#
#/control/execute vis.mac
#
/run/printProgress 10000
#
/run/beamOn 100000
