# test13
#
/run/initialize
#
/gps/particle geantino

# source
/gps/pos/type Volume
/gps/pos/shape Para
/gps/pos/centre 2. 2. 2. cm
/gps/pos/halfx 2. cm
/gps/pos/halfy 3. cm
/gps/pos/halfz 4. cm
/gps/pos/paralp 0.523599
/gps/pos/parthe 0.523599
/gps/pos/parphi 0.523599
/gps/pos/parphi 0.523599

# angular distribution
/gps/ang/type cos

# energy distribution
/gps/ene/type Exp
/gps/ene/min 2. MeV
/gps/ene/max 10. MeV
/gps/ene/ezero 6.

# commands below are independent of gps
#
/analysis/setFileName test10
/analysis/h1/set 1 100 1 15 MeV
/analysis/h2/set 4 120 0 360 deg none linear 100 -1 1 none none linear
#
#/control/execute vis.mac
#
/run/printProgress 10000
#
/run/beamOn 100000
