# test28
#
/run/initialize
#
/gps/particle ion
/gps/ion 2 3 1 0.

# source
/gps/pos/type Plane
/gps/pos/shape Square
/gps/pos/centre 1. 2. 1. cm
/gps/pos/halfx 2. cm
/gps/pos/halfy 2. cm

# angular distribution
/gps/ang/type iso

# energy distribution
/gps/energy 5 MeV

# commands below are independent of gps
#
/analysis/setFileName test28
/analysis/h1/set 1 100 0 10 MeV
/analysis/h2/set 1 100 -5 5 cm none linear 100 -5 5 cm none linear #x-y
/analysis/h2/set 4 120 0 360 deg none linear 100 -1 1 none none linear
#
#/control/execute vis.mac
#
/run/printProgress 10000
#
/run/beamOn 100000

