# test30 : 1D accelerator beam
#
/run/initialize
#
/gps/particle proton

# source
/gps/pos/type Beam
# the incident surface is in the y-z plane
/gps/pos/rot1 0 1 0
/gps/pos/rot2 0 0 1
#
# the beam spot is centered at the origin and is 
# of 1d gaussian shape with a 3mm central plateau
/gps/pos/shape Circle 
/gps/pos/centre 0. 0. 0. mm
/gps/pos/radius 3. mm
/gps/pos/sigma_r .2 mm

# angular distribution
# the beam is travelling along the x-axis with 5 degrees dispersion
/gps/ang/rot1 0 0 1
/gps/ang/rot2 0 1 0
/gps/ang/type beam1d  
/gps/ang/sigma_r 5. deg

# energy distribution  
# the beam energy is in gaussian profile centered at 400 MeV
/gps/ene/type Gauss
/gps/ene/mono 400 MeV
/gps/ene/sigma 50. MeV

#
# commands below are independent of gps
#
/analysis/setFileName test30
/analysis/h1/set 1 100 200 800 MeV
/analysis/h2/set 1 100 -5 5 mm none linear 100 -5 5 mm none linear #x-y
/analysis/h2/set 2 100 -5 5 mm none linear 100 -5 5 mm none linear #y-z
/analysis/h2/set 3 100 -5 5 mm none linear 100 -5 5 mm none linear #z-x
/analysis/h2/set 5 120 0 360 deg none linear 60 60 120 deg none linear
#
#/control/execute vis.mac
#/tracking/verbose 1
#
/run/printProgress 10000
#
/run/beamOn 100000
