# test14
#
/run/initialize
#
/gps/particle geantino

# source
/gps/pos/type Plane
/gps/pos/shape Circle
/gps/pos/centre 2. 2. 2. cm
/gps/pos/radius 2. cm
/gps/pos/rot1 1. 0. -0.57735

# angular distribution
/gps/ang/type iso

# energy distribution
/gps/ene/type Exp
/gps/ene/min 2. MeV
/gps/ene/max 10. MeV
/gps/ene/ezero 1.

# commands below are independent of gps
#
/analysis/setFileName test14
/analysis/h1/set 1 100 1 15 MeV
/analysis/h2/setX 4 120 0 360 deg
/analysis/h2/setY 4 100 -1 1 none
#
#/control/execute vis.mac
#
/run/printProgress 10000
#
/run/beamOn 100000
