/gps/particle geantino
/gps/pos/type Plane
/gps/pos/shape Square
/gps/pos/centre 1. 2. 1. cm
/gps/pos/halfx 2. cm
/gps/pos/halfy 2. cm
/gps/ang/type cos
/gps/ang/mintheta 1. rad
/gps/ang/maxtheta 2. rad
/gps/ang/minphi 1.5 rad
/gps/ang/maxphi 3. rad
/gps/ene/type Lin
/gps/ene/min 2. MeV
/gps/ene/max 10. MeV
/gps/ene/gradient 1.
/gps/ene/intercept 1.
/gps/hist/type biase
/gps/hist/point 0. 0.
/gps/hist/point 0.25 1.
/gps/hist/point 0.5 2.
/gps/hist/point 0.75 1.
/gps/hist/point 1. 0.1
/gps/number 3

# commands below are independent of gps
#
/analysis/filename test26a.aida
/analysis/maxeng 15 MeV
/analysis/mineng 1 MeV
/analysis/maxpos 5 cm 
/analysis/minpos -5 cm
/event/printModulo 10000
#/control/execute display.mac
/run/beamOn 100000

