# test38
#
/control/verbose 2
/run/initialize
#
/gps/particle geantino

# source
/gps/pos/type Plane
/gps/pos/shape Square
/gps/pos/centre 1. 2. 1. cm
/gps/pos/halfx 2. cm
/gps/pos/halfy 2. cm

# angular distribution
/gps/ang/type cos

# energy distribution
/gps/ene/type Arb
/gps/hist/file ./macros/spectrum.dat
/gps/hist/inter Exp

# commands below are independent of gps
#
/analysis/setFileName test38
/analysis/h1/set 1 110 0 110 MeV
/analysis/h2/set 1 100 -5 5 cm none linear 100 -5 5 cm none linear #x-y
/analysis/h2/set 2 100 -5 5 cm none linear 100 -5 5 cm none linear #y-z
/analysis/h2/set 4 120 0 360 deg none linear 100 -1 1 none none linear
# 
###/control/execute vis.mac
#
/run/printProgress 10000
#
/run/beamOn 100000
