# test35
#
/run/initialize
#
/gps/particle geantino

# source
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/pos/centre 2. 2. 2. cm
/gps/pos/radius 2.5 cm
/gps/pos/halfz 4. cm

# angular distribution
/gps/ang/type iso

# energy distribution
/gps/ene/type Pow
/gps/ene/min 0.01 MeV
/gps/ene/max 100 MeV
/gps/ene/alpha -2.5

# commands below are independent of gps
#
#
/analysis/setFileName test35a
/analysis/h1/set 1 110 0 110 MeV
/analysis/h2/set 1 100 -8 8 cm none linear 100 -8 8 cm none linear #x-y
/analysis/h2/set 2 100 -8 8 cm none linear 100 -8 8 cm none linear #y-z
/analysis/h2/set 4 120 0 360 deg none linear 100 -1 1 none none linear
# 
###/control/execute vis.mac
#
/run/printProgress 10000
#
/run/beamOn 100000

/analysis/setFileName test35b
/analysis/h1/set 1 110 0 110 MeV
#
/gps/ene/biasAlpha -1.
#
/run/beamOn 100000
