# test04
#
/run/initialize
#
/gps/particle geantino

#circular plane source
/gps/pos/type Plane
/gps/pos/shape Circle
/gps/pos/centre 2. 1. 0. cm
/gps/pos/radius 3. cm

# cosine-law 
/gps/ang/type cos

# exponetial energy distri.
/gps/ene/type Exp
/gps/ene/min 2. MeV
/gps/ene/max 10. MeV
/gps/ene/ezero 2.

# commands below are independent of gps
#
/analysis/setFileName test04
/analysis/h1/set 1 100 1 15 MeV
/analysis/h2/setX 1 100 -5 5 cm  #x-y
/analysis/h2/setY 1 100 -5 5 cm  #x-y
/analysis/h2/setX 4 120 0 360 deg 
/analysis/h2/setY 4 100 -1 1 none 
#
#/control/execute vis.mac
#
/run/printProgress 10000
#
/run/beamOn 100000
