# test06
#
/run/initialize
#
/gps/particle geantino

# surface source
/gps/pos/type Surface
/gps/pos/shape Sphere
/gps/pos/centre -2. 2. 2. cm
/gps/pos/radius 2.5 cm

#isotropic angular distribution
/gps/ang/type iso

# black body energy distr.
/gps/ene/type Bbody
/gps/ene/min 2. MeV
/gps/ene/max 10. MeV
/gps/ene/temp 2e10
/gps/ene/calculate

# commands below are independent of gps
#
/analysis/setFileName test06
/analysis/h1/set 1 100 1 15 MeV
/analysis/h2/set 1 100 -5 5 cm none linear 100 -5 5 cm none linear
/analysis/h2/set 2 100 -5 5 cm none linear 100 -5 5 cm none linear
/analysis/h2/set 3 100 -5 5 cm none linear 100 -5 5 cm none linear
/analysis/h2/set 4 120 0 360 deg none linear 100 -1 1 none none linear
#
#/control/execute vis.mac
#
/run/printProgress 10000
#
/run/beamOn 100000

