# test11
#
/run/initialize
#
/gps/particle geantino

# source
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/pos/centre 2. 2. 2. cm
/gps/pos/radius 2.5 cm
/gps/pos/halfz 4. cm

# angular distribution
/gps/ang/type iso

# energy distribution
/gps/ene/type Pow
/gps/ene/min 2. MeV
/gps/ene/max 10. MeV
/gps/alpha -2.

# commands below are independent of gps
#
/analysis/setFileName test11
/analysis/h1/set 1 100 1 15 MeV
/analysis/h2/setX 4 120 0 360 deg
/analysis/h2/setY 4 100 -1 1 none
#
#/control/execute vis.mac
#
/run/printProgress 10000
#
/run/beamOn 100000
