#
# Macro file for the visualisation 
# create empty scene
#
/vis/scene/create
/vis/open OGLIX
#/vis/open VRML1
#/vis/open DAWNFILE 
/vis/viewer/flush
#
# draw scene/
#
#
# for drawing the tracks
/vis/viewer/set/viewpointThetaPhi 90 180 deg
/vis/viewer/zoom 1.4
/tracking/storeTrajectory 1
/vis/scene/endOfEventAction accumulate
/vis/viewer/update
/vis/scene/transientsAction none
##/primary/energy Iodium   
##/source/switch Iodium
/vis/viewer/zoom 5
/run/beamOn 100

